# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import typing
import _sigil.weave
__all__: list[str] = ['each', 'line', 'lines', 'range', 'regex', 'sentence', 'text', 'word', 'words']

def each(unit: _sigil.weave.Unit) -> _sigil.weave.Selector:
    ...

def line(index: typing.SupportsInt) -> _sigil.weave.Selector:
    ...

def lines(start: typing.SupportsInt, end: typing.SupportsInt) -> _sigil.weave.Selector:
    ...

def range(start: typing.SupportsInt, end: typing.SupportsInt) -> _sigil.weave.Selector:
    ...

def regex(pattern: str) -> _sigil.weave.Selector:
    ...

def sentence(index: typing.SupportsInt) -> _sigil.weave.Selector:
    ...

def text(text: str) -> _sigil.weave.Selector:
    ...

def word(index: typing.SupportsInt) -> _sigil.weave.Selector:
    ...

def words(start: typing.SupportsInt, end: typing.SupportsInt) -> _sigil.weave.Selector:
    ...
