# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import typing
import _sigil.skia
import _sigil.weave
__all__: list[str] = ['circle', 'coverage', 'ellipse', 'path', 'rectangle']

def circle(bounds: _t.RectLike) -> _sigil.weave.Silhouette:
    ...

def coverage(image: _sigil.skia.Image, bounds: _t.RectLike, threshold: typing.SupportsFloat=0.5) -> _sigil.weave.Silhouette:
    ...

def ellipse(bounds: _t.RectLike) -> _sigil.weave.Silhouette:
    ...

def path(path: _sigil.skia.Path) -> _sigil.weave.Silhouette:
    ...

def rectangle(bounds: _t.RectLike) -> _sigil.weave.Silhouette:
    ...
