# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import _sigil.draw
import _sigil.geometry.mesh
import _sigil.geometry.mesh.camera
import _sigil.material
import _sigil.motion
import _sigil.skia
from . import kit
from . import light
from . import selectors
__all__: list[str] = ['Backface', 'Element', 'Frame', 'Pass', 'Scene', 'SceneStats', 'Selection', 'Selector', 'geometryPass', 'kit', 'light', 'postPass', 'selectors']

class Backface:
    """
    Members:

      Hidden

      Visible
    """
    Hidden: typing.ClassVar[Backface]
    Visible: typing.ClassVar[Backface]
    __members__: typing.ClassVar[dict[str, Backface]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Element:

    def __init__(self) -> None:
        ...

    def at(self, position: _t.Vec3Like) -> Element:
        ...

    def backface(self, facing: Backface) -> Element:
        ...

    def camera(self, camera: _sigil.geometry.mesh.camera.Camera) -> Element:
        ...

    @typing.overload
    def children(self, children: collections.abc.Iterable[Element], /) -> Element:
        ...

    @typing.overload
    def children(self, *children: Element) -> Element:
        ...

    def copy(self) -> Element:
        ...

    def emission(self, red: _t.ScalarLike, green: _t.ScalarLike, blue: _t.ScalarLike) -> Element:
        ...

    def exposure(self, value: _t.ScalarLike) -> Element:
        ...

    @typing.overload
    def fill(self, material: _sigil.material.Material) -> Element:
        ...

    @typing.overload
    def fill(self, materials: collections.abc.Sequence[_sigil.material.Material]) -> Element:
        ...

    def intensity(self, value: _t.ScalarLike) -> Element:
        ...

    def key(self, key: str) -> Element:
        ...

    def light(self, light: light.Light) -> Element:
        ...

    def mesh(self, mesh: _sigil.geometry.mesh.Mesh) -> Element:
        ...

    def rotate(self, axis: _t.Vec3Like, degrees: _t.ScalarLike) -> Element:
        ...

    def rotateX(self, value: _t.ScalarLike) -> Element:
        ...

    def rotateY(self, value: _t.ScalarLike) -> Element:
        ...

    def rotateZ(self, value: _t.ScalarLike) -> Element:
        ...

    def scale(self, value: _t.ScalarLike) -> Element:
        ...

    def scaleX(self, value: _t.ScalarLike) -> Element:
        ...

    def scaleY(self, value: _t.ScalarLike) -> Element:
        ...

    def scaleZ(self, value: _t.ScalarLike) -> Element:
        ...

    def tag(self, tag: str) -> Element:
        ...

    def transform(self, matrix: _sigil.geometry.mesh.camera.Matrix) -> Element:
        ...

    def transformOrigin(self, origin: _t.Vec3Like) -> Element:
        ...

    def transition(self, transition: _sigil.motion.Transition) -> Element:
        ...

    def translateX(self, value: _t.ScalarLike) -> Element:
        ...

    def translateY(self, value: _t.ScalarLike) -> Element:
        ...

    def translateZ(self, value: _t.ScalarLike) -> Element:
        ...

class Frame:

    def __init__(self, scene: Element=...) -> None:
        ...

    def camera(self, camera: _sigil.geometry.mesh.camera.Camera) -> Frame:
        ...

    def copy(self) -> Frame:
        ...

    def extent(self, size: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], 'FixedSize(2)']) -> Frame:
        ...

    def pass_(self, pass_: Pass) -> Frame:
        ...

    def present(self, resource: str) -> Frame:
        ...

    def scene(self, scene: Element) -> Frame:
        ...

class Pass:

    def blur(self, sigma: typing.SupportsFloat) -> Pass:
        ...

    def clear(self, color: _t.ColorLike) -> Pass:
        ...

    def composite(self, mode: _sigil.skia.BlendMode, opacity: typing.SupportsFloat=1) -> Pass:
        ...

    def copy(self) -> Pass:
        ...

    def levels(self, gain: typing.SupportsFloat, lift: typing.SupportsFloat, tint: _t.ColorLike='#ffffff') -> Pass:
        ...

    def only(self, selector: Selector) -> Pass:
        ...

    def previous(self, resource: str) -> Pass:
        ...

    @typing.overload
    def reads(self, resources: collections.abc.Iterable[str], /) -> Pass:
        ...

    @typing.overload
    def reads(self, *resources: str) -> Pass:
        ...

    def realise(self, selection: Selection) -> Pass:
        ...

    def variant(self, material: _sigil.material.Material) -> Pass:
        ...

    @typing.overload
    def writes(self, resources: collections.abc.Iterable[str], /) -> Pass:
        ...

    @typing.overload
    def writes(self, *resources: str) -> Pass:
        ...

class Scene:

    def __init__(self) -> None:
        ...

    def advance(self, seconds: typing.SupportsFloat) -> None:
        ...

    def draw(self, pen: _sigil.draw.Pen) -> None:
        ...

    def handleOf(self, key: str) -> int:
        ...

    def image(self, size: typing.Annotated[collections.abc.Sequence[typing.SupportsInt], 'FixedSize(2)'], background: _t.ColorLike='#00000000') -> _sigil.skia.Image:
        ...

    def referencesOf(self, key: str) -> int:
        ...

    @typing.overload
    def render(self, frame: Frame) -> None:
        ...

    @typing.overload
    def render(self, scene: Element) -> None:
        ...

    def transformOf(self, key: str) -> _sigil.geometry.mesh.camera.Matrix | None:
        ...

    @property
    def camera(self) -> _sigil.geometry.mesh.camera.Camera | None:
        ...

    @property
    def error(self) -> str:
        ...

    @property
    def lights(self) -> list[light.Light]:
        ...

    @property
    def stats(self) -> SceneStats:
        ...

class SceneStats:

    @property
    def aliased(self) -> int:
        ...

    @property
    def baked(self) -> int:
        ...

    @property
    def barriers(self) -> int:
        ...

    @property
    def cooked(self) -> int:
        ...

    @property
    def drawn(self) -> int:
        ...

    @property
    def extracted(self) -> int:
        ...

    @property
    def nodes(self) -> int:
        ...

    @property
    def passes(self) -> int:
        ...

    @property
    def replayed(self) -> int:
        ...

    @property
    def resources(self) -> int:
        ...

    @property
    def rounds(self) -> int:
        ...

    @property
    def surfaces(self) -> int:
        ...

class Selection:
    """
    Members:

      Auto

      All

      Cull

      Mask

      Variant
    """
    All: typing.ClassVar[Selection]
    Auto: typing.ClassVar[Selection]
    Cull: typing.ClassVar[Selection]
    Mask: typing.ClassVar[Selection]
    Variant: typing.ClassVar[Selection]
    __members__: typing.ClassVar[dict[str, Selection]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Selector:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __and__(self, other: Selector) -> Selector:
        ...

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self) -> None:
        ...

    def __invert__(self) -> Selector:
        ...

    def __or__(self, other: Selector) -> Selector:
        ...

def geometryPass(name: str) -> Pass:
    ...

def postPass(name: str) -> Pass:
    ...
