# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import typing
import _sigil.world
__all__: list[str] = ['Rig', 'Set', 'Turntable', 'litSet', 'threePoint', 'turntable']

class Rig:

    @property
    def at(self) -> _t.Vec3:
        ...

    @at.setter
    def at(self, value: _t.Vec3Like) -> None:
        ...

    def __init__(self, *, at: _t.Vec3Like=..., back: typing.SupportsFloat=..., bearing: typing.SupportsFloat=..., color: _t.ColorLike | _t.Vec4Like=..., distance: typing.SupportsFloat=..., elevation: typing.SupportsFloat=..., extent: typing.SupportsFloat=..., fill: typing.SupportsFloat=..., intensity: typing.SupportsFloat=...) -> None:
        ...

    def copy(self) -> Rig:
        ...

    @property
    def back(self) -> float:
        ...

    @back.setter
    def back(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def bearing(self) -> float:
        ...

    @bearing.setter
    def bearing(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def color(self) -> _t.Vec4:
        ...

    @color.setter
    def color(self, value: _t.ColorLike | _t.Vec4Like) -> None:
        ...

    @property
    def distance(self) -> float:
        ...

    @distance.setter
    def distance(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def elevation(self) -> float:
        ...

    @elevation.setter
    def elevation(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def extent(self) -> float:
        ...

    @extent.setter
    def extent(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def fill(self) -> float:
        ...

    @fill.setter
    def fill(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def intensity(self) -> float:
        ...

    @intensity.setter
    def intensity(self, value: typing.SupportsFloat, /) -> None:
        ...

class Set:
    rig: Rig
    surface: _sigil.material.Material | None
    table: Turntable

    def __init__(self, *, rig: Rig=..., surface: _sigil.material.Material | None=..., table: Turntable=..., drop: typing.SupportsFloat=..., ground: typing.SupportsFloat=...) -> None:
        ...

    def copy(self) -> Set:
        ...

    @property
    def drop(self) -> float:
        ...

    @drop.setter
    def drop(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def ground(self) -> float:
        ...

    @ground.setter
    def ground(self, value: typing.SupportsFloat, /) -> None:
        ...

class Turntable:

    @property
    def at(self) -> _t.Vec3:
        ...

    @at.setter
    def at(self, value: _t.Vec3Like) -> None:
        ...

    def __init__(self, *, at: _t.Vec3Like=..., fovYDeg: typing.SupportsFloat=..., height: typing.SupportsFloat=..., period: typing.SupportsFloat=..., radius: typing.SupportsFloat=..., stations: typing.SupportsInt=...) -> None:
        ...

    def copy(self) -> Turntable:
        ...

    @property
    def fovYDeg(self) -> float:
        ...

    @fovYDeg.setter
    def fovYDeg(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def height(self) -> float:
        ...

    @height.setter
    def height(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def period(self) -> float:
        ...

    @period.setter
    def period(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def radius(self) -> float:
        ...

    @radius.setter
    def radius(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def stations(self) -> int:
        ...

    @stations.setter
    def stations(self, value: typing.SupportsInt, /) -> None:
        ...

def litSet(subject: _sigil.world.Element, set: Set=..., seconds: _t.FloatLike=0) -> _sigil.world.Element:
    ...

def threePoint(rig: Rig=...) -> _sigil.world.Element:
    ...

def turntable(table: Turntable, seconds: typing.SupportsFloat) -> _sigil.world.Element:
    ...
