import collections.abc
import typing

@typing.overload
def row(children: collections.abc.Iterable[_t.NodeLike], /) -> Element: ...
@typing.overload
def row(*children: _t.NodeLike) -> Element: ...
@typing.overload
def column(children: collections.abc.Iterable[_t.NodeLike], /) -> Element: ...
@typing.overload
def column(*children: _t.NodeLike) -> Element: ...
