import collections.abc
import typing

@typing.overload
def row(children: collections.abc.Iterable[Element], /) -> Element: ...
@typing.overload
def row(*children: Element) -> Element: ...
@typing.overload
def column(children: collections.abc.Iterable[Element], /) -> Element: ...
@typing.overload
def column(*children: Element) -> Element: ...
