# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
from . import field
from . import kit
from . import pattern
from . import skia
__all__: list[str] = ['Material', 'field', 'kit', 'pattern', 'skia']

class Material:

    def copy(self) -> Material:
        ...
