# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import typing
import _sigil.material
__all__: list[str] = ['CrtOverlayParameters', 'crtOverlay', 'grain', 'halftoneRamp', 'noise', 'ripple']

class CrtOverlayParameters:

    def __init__(self, *, uBeamFalloff: typing.SupportsFloat=..., uBeamPitch: typing.SupportsFloat=..., uBeamStrength: typing.SupportsFloat=..., uBeatFalloff: typing.SupportsFloat=..., uBeatPitch: typing.SupportsFloat=..., uBeatStrength: typing.SupportsFloat=..., uGrain: typing.SupportsFloat=..., uScanPitch: typing.SupportsFloat=..., uScanStrength: typing.SupportsFloat=..., uSqueeze: typing.SupportsFloat=..., uVigInner: typing.SupportsFloat=..., uVigOuter: typing.SupportsFloat=..., uVigStrength: typing.SupportsFloat=...) -> None:
        ...

    def copy(self) -> CrtOverlayParameters:
        ...

    @property
    def uBeamFalloff(self) -> float:
        ...

    @uBeamFalloff.setter
    def uBeamFalloff(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uBeamPitch(self) -> float:
        ...

    @uBeamPitch.setter
    def uBeamPitch(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uBeamStrength(self) -> float:
        ...

    @uBeamStrength.setter
    def uBeamStrength(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uBeatFalloff(self) -> float:
        ...

    @uBeatFalloff.setter
    def uBeatFalloff(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uBeatPitch(self) -> float:
        ...

    @uBeatPitch.setter
    def uBeatPitch(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uBeatStrength(self) -> float:
        ...

    @uBeatStrength.setter
    def uBeatStrength(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uGrain(self) -> float:
        ...

    @uGrain.setter
    def uGrain(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uScanPitch(self) -> float:
        ...

    @uScanPitch.setter
    def uScanPitch(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uScanStrength(self) -> float:
        ...

    @uScanStrength.setter
    def uScanStrength(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uSqueeze(self) -> float:
        ...

    @uSqueeze.setter
    def uSqueeze(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uVigInner(self) -> float:
        ...

    @uVigInner.setter
    def uVigInner(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uVigOuter(self) -> float:
        ...

    @uVigOuter.setter
    def uVigOuter(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def uVigStrength(self) -> float:
        ...

    @uVigStrength.setter
    def uVigStrength(self, value: typing.SupportsFloat, /) -> None:
        ...

def crtOverlay(parameters: CrtOverlayParameters=...) -> _sigil.material.Material:
    ...

def grain(frequency: typing.SupportsFloat, octaves: typing.SupportsInt=4, seed: typing.SupportsFloat=1, contrast: typing.SupportsFloat=1, stretch: typing.SupportsFloat=1) -> _sigil.material.Material:
    ...

def halftoneRamp(spacing: typing.SupportsFloat, rMin: typing.SupportsFloat, rMax: typing.SupportsFloat, color: _t.ColorLike, angleDeg: typing.SupportsFloat=0.0, rampFrom: typing.SupportsFloat=0.0, rampTo: typing.SupportsFloat=1.0) -> _sigil.material.Material:
    ...

def noise(frequency: typing.SupportsFloat, octaves: typing.SupportsInt=4, seed: typing.SupportsFloat=1, turbulence: bool=False) -> _sigil.material.Material:
    ...

def ripple(amplitudePx: typing.SupportsFloat, wavelengthPx: typing.SupportsFloat, phase: typing.SupportsFloat=0.0, vertical: bool=False) -> _sigil.material.Material:
    ...
