# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import typing
import _sigil.material.skia
import _sigil.skia
__all__: list[str] = ['Tile', 'checker', 'gridLines', 'halftone', 'stripes']

class Tile:

    def image(self) -> _sigil.skia.Image:
        ...

    def offset(self, offset: _sigil.skia.Point) -> Tile:
        ...

    def paint(self) -> _sigil.material.skia.Paint:
        ...

    def rotate(self, degrees: typing.SupportsFloat) -> Tile:
        ...

    def scale(self, factor: typing.SupportsFloat) -> Tile:
        ...

    def seed(self, seed: typing.SupportsInt) -> Tile:
        ...

def checker(cell: typing.SupportsFloat, a: _t.ColorLike, b: _t.ColorLike) -> Tile:
    ...

def gridLines(spacing: typing.SupportsFloat, width: typing.SupportsFloat, color: _t.ColorLike) -> Tile:
    ...

def halftone(spacing: typing.SupportsFloat, radius: typing.SupportsFloat, color: _t.ColorLike, staggered: bool=True) -> Tile:
    ...

def stripes(on: typing.SupportsFloat, off: typing.SupportsFloat, color: _t.ColorLike) -> Tile:
    ...
