# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import typing
import _sigil.material.skia
import _sigil.skia
__all__: list[str] = ['Tile', 'checker', 'gridLines', 'halftone', 'stripes']

class Tile:

    def image(self) -> _sigil.skia.Image:
        ...

    def offset(self, arg0: _sigil.skia.Point) -> Tile:
        ...

    def paint(self) -> _sigil.material.skia.Paint:
        ...

    def rotate(self, arg0: typing.SupportsFloat) -> Tile:
        ...

    def scale(self, arg0: typing.SupportsFloat) -> Tile:
        ...

    def seed(self, arg0: typing.SupportsInt) -> Tile:
        ...

def checker(arg0: typing.SupportsFloat, arg1: _t.ColorLike, arg2: _t.ColorLike) -> Tile:
    ...

def gridLines(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: _t.ColorLike) -> Tile:
    ...

def halftone(spacing: typing.SupportsFloat, radius: typing.SupportsFloat, color: _t.ColorLike, staggered: bool=True) -> Tile:
    ...

def stripes(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: _t.ColorLike) -> Tile:
    ...
