# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import _sigil.material
import _sigil.skia
__all__: list[str] = ['BloomParameters', 'Effect', 'Fit', 'Paint', 'bloom']

class BloomParameters:

    def __init__(self, *, deepening: typing.SupportsFloat=..., dilation: typing.SupportsFloat=..., knee: typing.SupportsFloat=..., maxOpacity: typing.SupportsFloat=..., sigma: typing.SupportsFloat=..., softness: typing.SupportsFloat=..., spread: typing.SupportsFloat=..., strength: typing.SupportsFloat=..., tail: typing.SupportsFloat=..., threshold: typing.SupportsFloat=..., whitening: typing.SupportsFloat=...) -> None:
        ...

    def copy(self) -> BloomParameters:
        ...

    @property
    def deepening(self) -> float:
        ...

    @deepening.setter
    def deepening(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def dilation(self) -> float:
        ...

    @dilation.setter
    def dilation(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def knee(self) -> float:
        ...

    @knee.setter
    def knee(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def maxOpacity(self) -> float:
        ...

    @maxOpacity.setter
    def maxOpacity(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def sigma(self) -> float:
        ...

    @sigma.setter
    def sigma(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def softness(self) -> float:
        ...

    @softness.setter
    def softness(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def spread(self) -> float:
        ...

    @spread.setter
    def spread(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def strength(self) -> float:
        ...

    @strength.setter
    def strength(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def tail(self) -> float:
        ...

    @tail.setter
    def tail(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def threshold(self) -> float:
        ...

    @threshold.setter
    def threshold(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def whitening(self) -> float:
        ...

    @whitening.setter
    def whitening(self, value: typing.SupportsFloat, /) -> None:
        ...

class Effect:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    @staticmethod
    @typing.overload
    def blur(sigmaMap: Paint | _sigil.material.Material, maxSigma: typing.SupportsFloat) -> Effect:
        ...

    @staticmethod
    @typing.overload
    def blur(sigma: typing.SupportsFloat) -> Effect:
        ...

    @staticmethod
    def brightPass(threshold: typing.SupportsFloat=0.6800000071525574, knee: typing.SupportsFloat=0.30000001192092896) -> Effect:
        ...

    @staticmethod
    def deepen(amount: typing.SupportsFloat) -> Effect:
        ...

    @staticmethod
    def dilate(pixels: typing.SupportsFloat) -> Effect:
        ...

    @staticmethod
    def directionalBlur(sigma: typing.SupportsFloat, angleDeg: typing.SupportsFloat, across: typing.SupportsFloat=0.0) -> Effect:
        ...

    @staticmethod
    def glow(ink: _t.ColorLike, sigma: typing.SupportsFloat) -> Effect:
        ...

    @staticmethod
    def phosphorBloom(radius: typing.SupportsFloat=9.0, threshold: typing.SupportsFloat=0.5199999809265137, intensity: typing.SupportsFloat=0.46000000834465027, chroma: typing.SupportsFloat=0.800000011920929, hueDrift: typing.SupportsFloat=0.0, tail: typing.SupportsFloat=0.0) -> Effect:
        ...

    @staticmethod
    def recipe(material: _sigil.material.Material) -> Effect:
        ...

    @staticmethod
    def shader(effect: _sigil.skia.RuntimeEffect, uniforms: collections.abc.Sequence[tuple[str, typing.SupportsFloat]]=[]) -> Effect:
        ...

    @staticmethod
    def whiten(amount: typing.SupportsFloat, threshold: typing.SupportsFloat=0.20000000298023224, knee: typing.SupportsFloat=0.20000000298023224) -> Effect:
        ...

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self) -> None:
        ...

    def emit(self, light: Effect, mode: _sigil.skia.BlendMode=...) -> Effect:
        ...

    def isAnimated(self) -> bool:
        ...

    def slot(self, name: str, paint: Paint | _sigil.material.Material) -> Effect:
        ...

    def then(self, effect: Effect) -> Effect:
        ...

    def uniform(self, name: str, value: _t.ScalarLike | collections.abc.Sequence[_t.FloatLike]) -> Effect:
        ...

    def usesWorldSpace(self) -> bool:
        ...

class Fit:
    """
    Members:

      Contain

      Cover

      Stretch

      Native
    """
    Contain: typing.ClassVar[Fit]
    Cover: typing.ClassVar[Fit]
    Native: typing.ClassVar[Fit]
    Stretch: typing.ClassVar[Fit]
    __members__: typing.ClassVar[dict[str, Fit]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Paint:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    @staticmethod
    def blend(layers: collections.abc.Sequence[tuple[Paint | _sigil.material.Material, _sigil.skia.BlendMode]]) -> Paint:
        ...

    @staticmethod
    def conical(start: _t.PointLike, startRadius: typing.SupportsFloat, end: _t.PointLike, endRadius: typing.SupportsFloat, stops: _t.GradientStops) -> Paint:
        ...

    @staticmethod
    def glowUnit(center: _t.PointLike, radius: typing.SupportsFloat, stops: _t.GradientStops) -> Paint:
        ...

    @staticmethod
    def image(image: _sigil.skia.Image, tileX: _sigil.skia.TileMode=..., tileY: _sigil.skia.TileMode=..., local: _sigil.skia.Matrix=...) -> Paint:
        ...

    @staticmethod
    def linear(from_: _t.PointLike, to: _t.PointLike, stops: _t.GradientStops, tile: _sigil.skia.TileMode=...) -> Paint:
        ...

    @staticmethod
    def linearUnit(start: _t.PointLike, end: _t.PointLike, stops: _t.GradientStops) -> Paint:
        ...

    @staticmethod
    def radial(center: _t.PointLike, radius: typing.SupportsFloat, stops: _t.GradientStops, tile: _sigil.skia.TileMode=...) -> Paint:
        ...

    @staticmethod
    def radialUnit(center: _t.PointLike, radius: typing.SupportsFloat, stops: _t.GradientStops) -> Paint:
        ...

    @staticmethod
    def recipe(material: _sigil.material.Material) -> Paint:
        ...

    @staticmethod
    def sksl(effect: str | _sigil.skia.RuntimeEffect, uniforms: dict[str, _t.UniformValue]={}) -> Paint:
        ...

    @staticmethod
    def solid(color: _t.ColorLike) -> Paint:
        ...

    @staticmethod
    def sweep(center: _t.PointLike, stops: _t.GradientStops, start: typing.SupportsFloat=0, end: typing.SupportsFloat=360) -> Paint:
        ...

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, paint: Paint) -> None:
        ...

    @typing.overload
    def __init__(self, material: _sigil.material.Material) -> None:
        ...

    def amount(self, amount: typing.SupportsFloat) -> Paint:
        ...

    def copy(self) -> Paint:
        ...

    def fit(self, fit: Fit) -> Paint:
        ...

    def isAnimated(self) -> bool:
        ...

    def isNone(self) -> bool:
        ...

    def quantizeTime(self, hz: typing.SupportsFloat) -> Paint:
        ...

    def slot(self, name: str, paint: Paint | _sigil.material.Material) -> Paint:
        ...

    def uniform(self, name: str, value: _t.UniformValue) -> Paint:
        ...

    def worldSpace(self, on: bool=True) -> Paint:
        ...

def bloom(parameters: BloomParameters=...) -> Effect:
    ...
