# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import builtins
import typing
import _sigil.skia
__all__: list[str] = ['Cell', 'Turn', 'along', 'cellAt', 'cellRect', 'moduleSize', 'onEllipse', 'onRing', 'step']

class Cell:

    def __init__(self, column: typing.SupportsInt=0, row: typing.SupportsInt=0) -> None:
        ...

    @property
    def column(self) -> int:
        ...

    @column.setter
    def column(self, arg0: typing.SupportsInt) -> None:
        ...

    @property
    def row(self) -> int:
        ...

    @row.setter
    def row(self, arg0: typing.SupportsInt) -> None:
        ...

class Turn:
    """
    Members:

      Open

      Closed
    """
    Closed: typing.ClassVar[Turn]
    Open: typing.ClassVar[Turn]
    __members__: typing.ClassVar[dict[str, Turn]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

def along(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsInt, arg3: typing.SupportsInt, arg4: Turn) -> float:
    ...

def cellAt(arg0: typing.SupportsInt, arg1: typing.SupportsInt) -> Cell:
    ...

def cellRect(cell: Cell, module: _sigil.skia.Size, gap: _sigil.skia.Size=..., origin: _sigil.skia.Point=..., columnSpan: typing.SupportsInt=1, rowSpan: typing.SupportsInt=1) -> _sigil.skia.Rect:
    ...

def moduleSize(arg0: _sigil.skia.Size, arg1: typing.SupportsInt, arg2: typing.SupportsInt, arg3: _sigil.skia.Size) -> _sigil.skia.Size:
    ...

def onEllipse(arg0: _sigil.skia.Point, arg1: _sigil.skia.Point, arg2: typing.SupportsFloat) -> _sigil.skia.Point:
    ...

def onRing(arg0: typing.SupportsInt, arg1: typing.SupportsInt, arg2: _sigil.skia.Point, arg3: _sigil.skia.Point, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: Turn) -> _sigil.skia.Point:
    ...

def step(arg0: typing.SupportsFloat, arg1: typing.SupportsInt, arg2: Turn) -> float:
    ...
