# Generated by src/common/protocol/definition/generate.py from protocol.fbs;
# edit the definition, not this file.

"""The Sigil protocol's Python client.

One class per domain over a caller — Clock, Host, Registry, Session —
each method sending one command and answering its result's table. The
tables and enumerations of a domain stand in that domain's module:
``sigil.protocol.clock.SetPolicyParameters``.
"""

from __future__ import annotations

from .clock import Clock
from .host import Host
from .messages import Caller, Json, MessageError
from .registry import Registry
from .session import Session
from .shared import Empty, Error, ErrorCode, ProtocolError, Revision

__all__ = [
    "Caller",
    "Clock",
    "Empty",
    "Error",
    "ErrorCode",
    "Host",
    "Json",
    "MessageError",
    "ProtocolError",
    "Registry",
    "Revision",
    "Session",
]
