# Generated by src/common/protocol/definition/generate.py from protocol.fbs;
# edit the definition, not this file.

"""The clock a session's frames are drawn at: who moves it, how fast,
and when it is held. The one seam a run is made repeatable through —
a sketch reads only whether its clock is the wall's, and never which
client drives it.
"""

from __future__ import annotations

import collections.abc
import dataclasses
import enum

from . import messages


class Policy(enum.Enum):
    """How a host's clock moves."""

    Wall = "Wall"
    """The wall clock: a frame advances by the time that passed since the
    last. What a person watching a window sees.
    """

    Advance = "Advance"
    """The client's clock: nothing moves except by step, so every frame's
    time is a function of the steps alone.
    """

    Pause = "Pause"
    """Frozen: no frame advances, and the recordings a hub plays hold
    where they are.
    """

    PauseWhileLoading = "PauseWhileLoading"
    """The wall clock, except that it does not move while a page, a font
    or a resource the session asked for is still arriving.
    """


@dataclasses.dataclass(frozen=True, kw_only=True)
class BudgetExpiredEvent:
    """The budget setPolicy set has run out."""

    seconds: float = 0.0
    """Clock seconds when it ran out."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["seconds"] = self.seconds
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> BudgetExpiredEvent:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "BudgetExpiredEvent")
        return cls(
            seconds=messages.real(fields, "seconds", 0.0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class CurrentResult:
    """The clock as it stands."""

    policy: Policy = Policy.Wall
    """The policy it moves by."""

    seconds: float = 0.0
    """Clock seconds since the session opened."""

    frame: int = 0
    """Frames drawn since the session opened."""

    paused: bool = False
    """Whether pause holds it."""

    time_scale: float = 1.0
    """Clock seconds per wall second."""

    budget_remaining: float | None = None
    """Clock seconds of the budget still to run; absent where none was
    set or it has run out.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["policy"] = self.policy.value
        out["seconds"] = self.seconds
        out["frame"] = self.frame
        out["paused"] = self.paused
        out["time_scale"] = self.time_scale
        if self.budget_remaining is not None:
            out["budget_remaining"] = self.budget_remaining
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> CurrentResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "CurrentResult")
        return cls(
            policy=Policy(messages.text(fields, "policy", "Wall")),
            seconds=messages.real(fields, "seconds", 0.0),
            frame=messages.integer(fields, "frame", 0),
            paused=messages.boolean(fields, "paused", False),
            time_scale=messages.real(fields, "time_scale", 1.0),
            budget_remaining=messages.optional_real(fields, "budget_remaining"),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class PauseParameters:
    """What pause is asked."""

    paused: bool = True
    """True to hold the clock where it is, false to let it move again by
    its policy.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["paused"] = self.paused
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> PauseParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "PauseParameters")
        return cls(
            paused=messages.boolean(fields, "paused", True),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class SetPolicyParameters:
    """What setPolicy is asked."""

    policy: Policy = Policy.Wall
    """The policy from now on."""

    budget_seconds: float | None = None
    """Seconds of clock time after which budgetExpired is sent, once;
    absent for no budget. A budget that runs out with nothing still
    moving is how a client learns the session settled.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["policy"] = self.policy.value
        if self.budget_seconds is not None:
            out["budget_seconds"] = self.budget_seconds
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> SetPolicyParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "SetPolicyParameters")
        return cls(
            policy=Policy(messages.text(fields, "policy", "Wall")),
            budget_seconds=messages.optional_real(fields, "budget_seconds"),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class StepParameters:
    """What step is asked: frames, or seconds taken as frames of one rate."""

    frames: int = 1
    """Frames to advance, where seconds is absent."""

    seconds: float | None = None
    """Seconds to advance, in frames of one over rate; absent to step by
    frames.
    """

    rate: float = 60.0
    """Frames per second the steps are taken at: each frame advances the
    clock by one over this.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["frames"] = self.frames
        if self.seconds is not None:
            out["seconds"] = self.seconds
        out["rate"] = self.rate
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> StepParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "StepParameters")
        return cls(
            frames=messages.integer(fields, "frames", 1),
            seconds=messages.optional_real(fields, "seconds"),
            rate=messages.real(fields, "rate", 60.0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class StepResult:
    """Where step left the clock."""

    seconds: float = 0.0
    """Clock seconds since the session opened."""

    frame: int = 0
    """Frames drawn since the session opened."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["seconds"] = self.seconds
        out["frame"] = self.frame
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> StepResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "StepResult")
        return cls(
            seconds=messages.real(fields, "seconds", 0.0),
            frame=messages.integer(fields, "frame", 0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class TimeScaleParameters:
    """What setTimeScale is asked."""

    scale: float = 1.0
    """Clock seconds per wall second: one is real time, a half is half
    speed. The Advance policy steps by its own rate and ignores it.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["scale"] = self.scale
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> TimeScaleParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "TimeScaleParameters")
        return cls(
            scale=messages.real(fields, "scale", 1.0),
        )


class Clock:
    """The clock a session's frames are drawn at: who moves it, how fast,
    and when it is held. The one seam a run is made repeatable through —
    a sketch reads only whether its clock is the wall's, and never which
    client drives it.

    One method per command, sending its parameters through the caller
    and answering its result's table, and one per event, handing each
    to a listener.
    """

    def __init__(self, caller: messages.Caller) -> None:
        self._caller = caller

    def setPolicy(
        self,
        *,
        policy: Policy = Policy.Wall,
        budget_seconds: float | None = None,
    ) -> None:
        """Replaces how the clock moves, from the next frame on."""
        self._caller.call("clock.setPolicy", SetPolicyParameters(policy=policy, budget_seconds=budget_seconds).toJson())

    def step(
        self,
        *,
        frames: int = 1,
        seconds: float | None = None,
        rate: float = 60.0,
    ) -> StepResult:
        """Advances the clock by frames or by seconds, drawing each frame, and
        answers once the last is drawn. Refused unless the policy is
        Advance.

        Answered once the work is done.
        """
        return StepResult.fromJson(
            self._caller.call("clock.step", StepParameters(frames=frames, seconds=seconds, rate=rate).toJson())
        )

    def current(self) -> CurrentResult:
        """The clock as it stands."""
        return CurrentResult.fromJson(
            self._caller.call("clock.current", {})
        )

    def pause(self, *, paused: bool = True) -> None:
        """Holds the clock or lets it go, keeping its policy: the pause a
        person presses.
        """
        self._caller.call("clock.pause", PauseParameters(paused=paused).toJson())

    def setTimeScale(self, *, scale: float = 1.0) -> None:
        """Sets how many clock seconds pass per wall second."""
        self._caller.call("clock.setTimeScale", TimeScaleParameters(scale=scale).toJson())

    def enable(self) -> None:
        """Starts this client's clock events."""
        self._caller.call("clock.enable", {})

    def disable(self) -> None:
        """Stops this client's clock events."""
        self._caller.call("clock.disable", {})

    def onBudgetExpired(
        self, listener: collections.abc.Callable[[BudgetExpiredEvent], None]
    ) -> None:
        """The budget setPolicy set has run out.

        Every one is handed to the listener once this
        client has called enable.
        """
        self._caller.listen(
            "clock.budgetExpired", lambda value: listener(BudgetExpiredEvent.fromJson(value))
        )
