# Generated by src/common/protocol/definition/generate.py from protocol.fbs;
# edit the definition, not this file.

"""The host itself: what it is, which domains it mounts, and where it
keeps its state. describe is the first command a client sends.
"""

from __future__ import annotations

import collections.abc
import dataclasses

from . import messages
from . import clock as _clock
from . import session as _session
from . import shared as _shared


@dataclasses.dataclass(frozen=True, kw_only=True)
class DescribeResult:
    """Everything a client asks first, in one answer."""

    version: VersionResult
    """Which definition and which program answer."""

    domains: tuple[str, ...] = ()
    """The domains this host mounts an agent for, by name. A command of
    any other answers notMounted.
    """

    clock: _clock.Policy = _clock.Policy.Wall
    """How the host's clock moves."""

    state_root: str = ""
    """Where the host keeps its state."""

    sessions: tuple[_session.Summary, ...] = ()
    """The sessions open."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["version"] = self.version.toJson()
        out["domains"] = [item for item in self.domains]
        out["clock"] = self.clock.value
        out["state_root"] = self.state_root
        out["sessions"] = [item.toJson() for item in self.sessions]
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> DescribeResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "DescribeResult")
        return cls(
            version=VersionResult.fromJson(messages.required(fields, "version", "DescribeResult")),
            domains=messages.texts(fields, "domains"),
            clock=_clock.Policy(messages.text(fields, "clock", "Wall")),
            state_root=messages.text(fields, "state_root", ""),
            sessions=tuple(_session.Summary.fromJson(item) for item in messages.items(fields, "sessions")),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class DetachedEvent:
    """The host has let this client go."""

    reason: str = ""
    """Why: the host is closing, or another client took its place."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["reason"] = self.reason
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> DetachedEvent:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "DetachedEvent")
        return cls(
            reason=messages.text(fields, "reason", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class StateRootResult:
    """Where the host keeps its state."""

    path: str = ""
    """The directory: thumbnails, pipeline sets, the build cache, settings,
    the protocol's address file and every still a client asks for.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["path"] = self.path
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> StateRootResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "StateRootResult")
        return cls(
            path=messages.text(fields, "path", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class VersionResult:
    """Which definition and which program answer."""

    revision: _shared.Revision
    """The definition the host was built from."""

    program: str = ""
    """The program: Sketchbook, Seer or the receiver."""

    program_version: str = ""
    """The program's own version."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["revision"] = self.revision.toJson()
        out["program"] = self.program
        out["program_version"] = self.program_version
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> VersionResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "VersionResult")
        return cls(
            revision=_shared.Revision.fromJson(messages.required(fields, "revision", "VersionResult")),
            program=messages.text(fields, "program", ""),
            program_version=messages.text(fields, "program_version", ""),
        )


class Host:
    """The host itself: what it is, which domains it mounts, and where it
    keeps its state. describe is the first command a client sends.

    One method per command, sending its parameters through the caller
    and answering its result's table, and one per event, handing each
    to a listener.
    """

    def __init__(self, caller: messages.Caller) -> None:
        self._caller = caller

    def describe(self) -> DescribeResult:
        """Everything a client asks first: the version, the domains mounted,
        the clock's policy, the state root and the sessions open.
        """
        return DescribeResult.fromJson(
            self._caller.call("host.describe", {})
        )

    def stateRoot(self) -> StateRootResult:
        """Where the host keeps its state."""
        return StateRootResult.fromJson(
            self._caller.call("host.stateRoot", {})
        )

    def version(self) -> VersionResult:
        """Which definition and which program answer."""
        return VersionResult.fromJson(
            self._caller.call("host.version", {})
        )

    def enable(self) -> None:
        """Starts this client's host events."""
        self._caller.call("host.enable", {})

    def disable(self) -> None:
        """Stops this client's host events."""
        self._caller.call("host.disable", {})

    def onDetached(
        self, listener: collections.abc.Callable[[DetachedEvent], None]
    ) -> None:
        """The host has let this client go: nothing more arrives on its
        connection.

        Every one is handed to the listener once this
        client has called enable.
        """
        self._caller.listen(
            "host.detached", lambda value: listener(DetachedEvent.fromJson(value))
        )
