# Generated by src/common/protocol/definition/generate.py from protocol.fbs;
# edit the definition, not this file.

"""What every generated module of the protocol client stands on.

The JSON a message is made of, the caller a client speaks through, and the
readings that take one field of a decoded JSON object and answer it as the
type the definition declares, raising ValueError where it is not that.
"""

from __future__ import annotations

import collections.abc
import typing

type Json = None | bool | int | float | str | list[Json] | dict[str, Json]


class Caller(typing.Protocol):
    """What a generated client speaks through.

    ``call`` sends one command, its method and its parameters' JSON object,
    and answers the result's JSON object, raising ProtocolError where the
    host answered an error; ``listen`` hands every event of a method to a
    listener as its JSON object. The socket client and the in-process
    dispatcher are two.
    """

    def call(self, method: str, parameters: dict[str, Json]) -> Json: ...

    def listen(
        self, method: str, listener: collections.abc.Callable[[Json], None]
    ) -> None: ...


def members(value: Json, table: str) -> dict[str, Json]:
    """The members of the JSON object a table is read from."""
    if not isinstance(value, dict):
        raise ValueError(f"{table} is read from a JSON object")
    return value


def required(fields: dict[str, Json], name: str, table: str) -> Json:
    """A field the definition requires, which the object must carry."""
    if name not in fields:
        raise ValueError(f"{table} requires {name}")
    return fields[name]


def required_text(fields: dict[str, Json], name: str, table: str) -> str:
    """Text the definition requires, which the object must carry."""
    return text({name: required(fields, name, table)}, name, "")


def boolean(fields: dict[str, Json], name: str, default: bool) -> bool:
    value = fields.get(name, default)
    if not isinstance(value, bool):
        raise ValueError(f"{name} is true or false")
    return value


def integer(fields: dict[str, Json], name: str, default: int) -> int:
    value = fields.get(name, default)
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{name} is a whole number")
    return value


def real(fields: dict[str, Json], name: str, default: float) -> float:
    value = fields.get(name, default)
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise ValueError(f"{name} is a number")
    return float(value)


def text(fields: dict[str, Json], name: str, default: str) -> str:
    value = fields.get(name, default)
    if not isinstance(value, str):
        raise ValueError(f"{name} is text")
    return value


def optional_boolean(fields: dict[str, Json], name: str) -> bool | None:
    return None if fields.get(name) is None else boolean(fields, name, False)


def optional_integer(fields: dict[str, Json], name: str) -> int | None:
    return None if fields.get(name) is None else integer(fields, name, 0)


def optional_real(fields: dict[str, Json], name: str) -> float | None:
    return None if fields.get(name) is None else real(fields, name, 0.0)


def optional_text(fields: dict[str, Json], name: str) -> str | None:
    return None if fields.get(name) is None else text(fields, name, "")


def items(fields: dict[str, Json], name: str) -> list[Json]:
    """The entries of a field that holds many."""
    value = fields.get(name, [])
    if not isinstance(value, list):
        raise ValueError(f"{name} is a list")
    return value


def booleans(fields: dict[str, Json], name: str) -> tuple[bool, ...]:
    return tuple(boolean({name: item}, name, False) for item in items(fields, name))


def integers(fields: dict[str, Json], name: str) -> tuple[int, ...]:
    return tuple(integer({name: item}, name, 0) for item in items(fields, name))


def reals(fields: dict[str, Json], name: str) -> tuple[float, ...]:
    return tuple(real({name: item}, name, 0.0) for item in items(fields, name))


def texts(fields: dict[str, Json], name: str) -> tuple[str, ...]:
    return tuple(text({name: item}, name, "") for item in items(fields, name))
