# Generated by src/common/protocol/definition/generate.py from protocol.fbs;
# edit the definition, not this file.

"""The sketches a host can open: every one it was built with, and the
browser's rows for them.
"""

from __future__ import annotations

import collections.abc
import dataclasses

from . import messages
from . import shared as _shared


@dataclasses.dataclass(frozen=True, kw_only=True)
class CatalogParameters:
    """What catalog is asked."""

    paths: tuple[str, ...] = ()
    """Files beyond the registry to catalog as well."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["paths"] = list(self.paths)
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> CatalogParameters:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            paths=messages.texts(fields, "paths"),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class CatalogResult:
    """The catalog's rows: the registry's first, then the files asked for."""

    rows: tuple[CatalogRow, ...] = ()
    """Each row."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["rows"] = [item.to_json() for item in self.rows]
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> CatalogResult:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            rows=messages.tables(fields, "rows", CatalogRow.from_json),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class CatalogRow:
    """One row of the catalog a browser shows before a sketch is opened."""

    name: str = ""
    """The name it is shown under."""

    key: str = ""
    """The key its thumbnail and its settings are kept under."""

    folder: str = ""
    """The folder it is filed in."""

    blurb: str = ""
    """The one line its header opens with."""

    path: str = ""
    """Its source file."""

    kind: str = ""
    """The runtime it draws through; empty for a file not yet built."""

    available: bool = False
    """Whether this build can open it."""

    reason: str = ""
    """Why it cannot, where it cannot."""

    external: bool = False
    """Whether it is a file the run was pointed at rather than one the
    registry holds.
    """

    lines: int = 0
    """Lines of source."""

    subject: str = ""
    """What its header says it is about."""

    tags: tuple[str, ...] = ()
    """The tags its header gives it."""

    canvas: str = ""
    """The canvas it declared, as width by height; empty until built."""

    background: str = ""
    """The background it declared; empty until built."""

    moment: float = -1.0
    """The moment it declared, in seconds; negative where none."""

    plate: str = ""
    """Where its thumbnail is, where one has been taken."""

    video_exportable: bool = False
    """Whether it can be written out as a video."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["name"] = self.name
        out["key"] = self.key
        out["folder"] = self.folder
        out["blurb"] = self.blurb
        out["path"] = self.path
        out["kind"] = self.kind
        out["available"] = self.available
        out["reason"] = self.reason
        out["external"] = self.external
        out["lines"] = self.lines
        out["subject"] = self.subject
        out["tags"] = list(self.tags)
        out["canvas"] = self.canvas
        out["background"] = self.background
        out["moment"] = self.moment
        out["plate"] = self.plate
        out["video_exportable"] = self.video_exportable
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> CatalogRow:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            name=messages.text(fields, "name", ""),
            key=messages.text(fields, "key", ""),
            folder=messages.text(fields, "folder", ""),
            blurb=messages.text(fields, "blurb", ""),
            path=messages.text(fields, "path", ""),
            kind=messages.text(fields, "kind", ""),
            available=messages.boolean(fields, "available", False),
            reason=messages.text(fields, "reason", ""),
            external=messages.boolean(fields, "external", False),
            lines=messages.integer(fields, "lines", 0),
            subject=messages.text(fields, "subject", ""),
            tags=messages.texts(fields, "tags"),
            canvas=messages.text(fields, "canvas", ""),
            background=messages.text(fields, "background", ""),
            moment=messages.real(fields, "moment", -1.0),
            plate=messages.text(fields, "plate", ""),
            video_exportable=messages.boolean(fields, "video_exportable", False),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class ChangedEvent:
    """The registry changed."""

    names: tuple[str, ...] = ()
    """The sketches added, removed or rebuilt."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["names"] = list(self.names)
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> ChangedEvent:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            names=messages.texts(fields, "names"),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class Entry:
    """One sketch the registry holds."""

    name: str = ""
    """The name it is opened by."""

    stem: str = ""
    """Its file's stem, or its directory's."""

    kind: str = ""
    """The runtime it draws through: canvas or set."""

    available: bool = False
    """Whether this build can open it."""

    reason: str = ""
    """Why it cannot, where it cannot."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["name"] = self.name
        out["stem"] = self.stem
        out["kind"] = self.kind
        out["available"] = self.available
        out["reason"] = self.reason
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> Entry:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            name=messages.text(fields, "name", ""),
            stem=messages.text(fields, "stem", ""),
            kind=messages.text(fields, "kind", ""),
            available=messages.boolean(fields, "available", False),
            reason=messages.text(fields, "reason", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class ListParameters:
    """What list is asked."""

    kind: str = ""
    """The runtime to list, canvas or set; empty for every one."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["kind"] = self.kind
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> ListParameters:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            kind=messages.text(fields, "kind", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class ListResult:
    """The sketches the registry holds."""

    sketches: tuple[Entry, ...] = ()
    """Each one, in the registry's order."""

    def to_json(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["sketches"] = [item.to_json() for item in self.sketches]
        return out

    @classmethod
    def from_json(cls, value: messages.Json) -> ListResult:
        """The table a JSON object carries; MessageError where it does not fit."""
        fields = messages.members(value, cls)
        return cls(
            sketches=messages.tables(fields, "sketches", Entry.from_json),
        )


class Registry:
    """The sketches a host can open: every one it was built with, and the
    browser's rows for them.

    One method per command, sending its parameters through the caller
    and answering its result's table, and one per event, handing each
    to a listener.
    """

    def __init__(self, caller: messages.Caller) -> None:
        self._caller = caller

    def list(self, *, kind: str = "") -> ListResult:
        """The sketches the registry holds, of one runtime or of all."""
        parameters = ListParameters(kind=kind)
        answer = self._caller.call("registry.list", parameters.to_json())
        return _shared.answer("registry.list", ListResult.from_json, answer)

    def catalog(self, *, paths: tuple[str, ...] = ()) -> CatalogResult:
        """The rows a browser shows before a sketch is opened.

        EXPERIMENTAL: its shape may still change.
        """
        parameters = CatalogParameters(paths=paths)
        answer = self._caller.call("registry.catalog", parameters.to_json())
        return _shared.answer("registry.catalog", CatalogResult.from_json, answer)

    def enable(self) -> None:
        """Starts this client's registry events."""
        answer = self._caller.call("registry.enable", {})
        _shared.answer("registry.enable", _shared.Empty.from_json, answer)

    def disable(self) -> None:
        """Stops this client's registry events."""
        answer = self._caller.call("registry.disable", {})
        _shared.answer("registry.disable", _shared.Empty.from_json, answer)

    def on_changed(
        self, listener: collections.abc.Callable[[ChangedEvent], None]
    ) -> None:
        """Sketches were added, removed or rebuilt.

        Every one is handed to the listener once this
        client has called enable.
        """
        hear = _shared.hearing(
            self._caller, "registry.changed", ChangedEvent.from_json, listener
        )
        self._caller.listen("registry.changed", hear)
