# Generated by src/common/protocol/definition/generate.py from protocol.fbs;
# edit the definition, not this file.

"""The one running sketch a host holds: opening it, pinning what a
repeatable run needs pinned, photographing it, and reading back what
its last frame cost.
"""

from __future__ import annotations

import collections.abc
import dataclasses
import enum

from . import messages


class Device(enum.Enum):
    """What a session draws with."""

    Cpu = "Cpu"
    """Skia's raster backend: the reference every plate is judged
    against.
    """

    Gpu = "Gpu"
    """The GPU, through the host's device."""


class Promotion(enum.Enum):
    """When the runtime may re-bake a node it was not asked to."""

    Off = "Off"
    """Never: a byte-identical still asks for this."""

    Auto = "Auto"
    """By the runtime's own measure of what is expensive, which differs
    from machine to machine.
    """

    Eager = "Eager"
    """Every node the runtime may bake, whatever it costs."""


@dataclasses.dataclass(frozen=True, kw_only=True)
class ClosedEvent:
    """A session closed."""

    sketch: str = ""
    """The registry name, or the path, it was opened from."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["sketch"] = self.sketch
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> ClosedEvent:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "ClosedEvent")
        return cls(
            sketch=messages.text(fields, "sketch", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class CompositeCountsResult:
    """The composite-count plane of the next frame."""

    path: str = ""
    """Where the plane was written, under the state root: one saturating
    byte per device pixel, as a grey image.
    """

    width: int = 0
    """The plane's width in pixels."""

    height: int = 0
    """The plane's height in pixels."""

    maximum: int = 0
    """The most composites any one pixel passed through."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["path"] = self.path
        out["width"] = self.width
        out["height"] = self.height
        out["maximum"] = self.maximum
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> CompositeCountsResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "CompositeCountsResult")
        return cls(
            path=messages.text(fields, "path", ""),
            width=messages.integer(fields, "width", 0),
            height=messages.integer(fields, "height", 0),
            maximum=messages.integer(fields, "maximum", 0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class DeviceParameters:
    """What pinDevice is asked."""

    device: Device = Device.Cpu
    """The device the session draws with from now on."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["device"] = self.device.value
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> DeviceParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "DeviceParameters")
        return cls(
            device=Device(messages.text(fields, "device", "Cpu")),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class FailedEvent:
    """A session could not be opened, or could not be rebuilt after an edit."""

    sketch: str = ""
    """The registry name, or the path, it was asked for."""

    message: str = ""
    """What stopped it, in the compiler's or the runtime's own words."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["sketch"] = self.sketch
        out["message"] = self.message
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> FailedEvent:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "FailedEvent")
        return cls(
            sketch=messages.text(fields, "sketch", ""),
            message=messages.text(fields, "message", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class LaneCost:
    """What one lane of a frame cost, named by the runtime that spent it."""

    name: str = ""
    """The lane, in the runtime's own word."""

    milliseconds: float = 0.0
    """Milliseconds it spent."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["name"] = self.name
        out["milliseconds"] = self.milliseconds
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> LaneCost:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "LaneCost")
        return cls(
            name=messages.text(fields, "name", ""),
            milliseconds=messages.real(fields, "milliseconds", 0.0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class MeasuredResult:
    """The numbers a sketch measured about its own execution."""

    values: tuple[MeasuredValue, ...] = ()
    """Each one, in the order the sketch measured them."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["values"] = [item.toJson() for item in self.values]
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> MeasuredResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "MeasuredResult")
        return cls(
            values=tuple(MeasuredValue.fromJson(item) for item in messages.items(fields, "values")),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class MeasuredValue:
    """One number a sketch measured about its own execution."""

    name: str = ""
    """The name the sketch gave it."""

    value: float = 0.0
    """The value it measured."""

    pinned: float = 0.0
    """The value a repeatable run shows in its place."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["name"] = self.name
        out["value"] = self.value
        out["pinned"] = self.pinned
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> MeasuredValue:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "MeasuredValue")
        return cls(
            name=messages.text(fields, "name", ""),
            value=messages.real(fields, "value", 0.0),
            pinned=messages.real(fields, "pinned", 0.0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class OpenParameters:
    """What open is asked."""

    sketch: str
    """A registry name, or the path to a sketch file or directory, which
    is compiled and loaded as a person's edit would be.
    """

    kind: str = ""
    """The runtime to open it through, canvas or set; empty for whichever
    it declares.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["sketch"] = self.sketch
        out["kind"] = self.kind
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> OpenParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "OpenParameters")
        return cls(
            sketch=messages.required_text(fields, "sketch", "OpenParameters"),
            kind=messages.text(fields, "kind", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class OpenedEvent:
    """A session opened."""

    summary: Summary
    """The session."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["summary"] = self.summary.toJson()
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> OpenedEvent:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "OpenedEvent")
        return cls(
            summary=Summary.fromJson(messages.required(fields, "summary", "OpenedEvent")),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class PromotionParameters:
    """What pinPromotion is asked."""

    promotion: Promotion = Promotion.Auto
    """When the runtime may re-bake from now on."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["promotion"] = self.promotion.value
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> PromotionParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "PromotionParameters")
        return cls(
            promotion=Promotion(messages.text(fields, "promotion", "Auto")),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class SequenceParameters:
    """What sequence is asked."""

    frames: int = 1
    """Frames to photograph, one after another."""

    rate: float = 60.0
    """Frames per second the clock advances between them."""

    density: float = 1.0
    """Device pixels per canvas unit."""

    directory: str = ""
    """The directory the frames are written into, under the state root;
    empty for one the host picks.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["frames"] = self.frames
        out["rate"] = self.rate
        out["density"] = self.density
        out["directory"] = self.directory
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> SequenceParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "SequenceParameters")
        return cls(
            frames=messages.integer(fields, "frames", 1),
            rate=messages.real(fields, "rate", 60.0),
            density=messages.real(fields, "density", 1.0),
            directory=messages.text(fields, "directory", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class SequenceResult:
    """The frames, written."""

    paths: tuple[str, ...] = ()
    """Where each frame was written, in order."""

    width: int = 0
    """Each frame's width in pixels."""

    height: int = 0
    """Each frame's height in pixels."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["paths"] = [item for item in self.paths]
        out["width"] = self.width
        out["height"] = self.height
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> SequenceResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "SequenceResult")
        return cls(
            paths=messages.texts(fields, "paths"),
            width=messages.integer(fields, "width", 0),
            height=messages.integer(fields, "height", 0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class StillParameters:
    """What still is asked."""

    density: float = 1.0
    """Device pixels per canvas unit."""

    path: str = ""
    """Where the still is written, under the state root; empty for a name
    the host picks.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["density"] = self.density
        out["path"] = self.path
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> StillParameters:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "StillParameters")
        return cls(
            density=messages.real(fields, "density", 1.0),
            path=messages.text(fields, "path", ""),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class StillResult:
    """The still, written."""

    path: str = ""
    """Where it was written."""

    width: int = 0
    """Its width in pixels."""

    height: int = 0
    """Its height in pixels."""

    seconds: float = 0.0
    """Clock seconds when it was taken."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["path"] = self.path
        out["width"] = self.width
        out["height"] = self.height
        out["seconds"] = self.seconds
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> StillResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "StillResult")
        return cls(
            path=messages.text(fields, "path", ""),
            width=messages.integer(fields, "width", 0),
            height=messages.integer(fields, "height", 0),
            seconds=messages.real(fields, "seconds", 0.0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class Summary:
    """A session as a list shows it."""

    sketch: str = ""
    """The registry name, or the path, it was opened from."""

    kind: str = ""
    """The runtime it draws through: canvas or set."""

    width: float = 0.0
    """The canvas width it declared, in canvas units."""

    height: float = 0.0
    """The canvas height it declared, in canvas units."""

    moment: float = -1.0
    """The moment it declared it is photographed at, in seconds; negative
    where it declared none.
    """

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["sketch"] = self.sketch
        out["kind"] = self.kind
        out["width"] = self.width
        out["height"] = self.height
        out["moment"] = self.moment
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> Summary:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "Summary")
        return cls(
            sketch=messages.text(fields, "sketch", ""),
            kind=messages.text(fields, "kind", ""),
            width=messages.real(fields, "width", 0.0),
            height=messages.real(fields, "height", 0.0),
            moment=messages.real(fields, "moment", -1.0),
        )


@dataclasses.dataclass(frozen=True, kw_only=True)
class TimingResult:
    """How the last frame split."""

    total_milliseconds: float = 0.0
    """Everything the frame cost, in milliseconds."""

    update_milliseconds: float = 0.0
    """What the sketch's own body did."""

    draw_milliseconds: float = 0.0
    """What its runtime then did with what the body described."""

    lanes: tuple[LaneCost, ...] = ()
    """What each lane cost; empty for a runtime that keeps no breakdown."""

    def toJson(self) -> dict[str, messages.Json]:
        """This table as the JSON object the wire carries."""
        out: dict[str, messages.Json] = {}
        out["total_milliseconds"] = self.total_milliseconds
        out["update_milliseconds"] = self.update_milliseconds
        out["draw_milliseconds"] = self.draw_milliseconds
        out["lanes"] = [item.toJson() for item in self.lanes]
        return out

    @classmethod
    def fromJson(cls, value: messages.Json) -> TimingResult:
        """The table a JSON object carries; ValueError where it does not fit."""
        fields = messages.members(value, "TimingResult")
        return cls(
            total_milliseconds=messages.real(fields, "total_milliseconds", 0.0),
            update_milliseconds=messages.real(fields, "update_milliseconds", 0.0),
            draw_milliseconds=messages.real(fields, "draw_milliseconds", 0.0),
            lanes=tuple(LaneCost.fromJson(item) for item in messages.items(fields, "lanes")),
        )


class Session:
    """The one running sketch a host holds: opening it, pinning what a
    repeatable run needs pinned, photographing it, and reading back what
    its last frame cost.

    One method per command, sending its parameters through the caller
    and answering its result's table, and one per event, handing each
    to a listener.
    """

    def __init__(self, caller: messages.Caller) -> None:
        self._caller = caller

    def open(self, *, sketch: str, kind: str = "") -> Summary:
        """Opens a sketch by registry name or by path, replacing the session
        open, and answers once its first frame is drawn.

        Answered once the work is done.
        """
        return Summary.fromJson(
            self._caller.call("session.open", OpenParameters(sketch=sketch, kind=kind).toJson())
        )

    def pinDevice(self, *, device: Device = Device.Cpu) -> None:
        """Pins the device the session draws with."""
        self._caller.call("session.pinDevice", DeviceParameters(device=device).toJson())

    def pinPromotion(self, *, promotion: Promotion = Promotion.Auto) -> None:
        """Pins when the runtime may re-bake a node it was not asked to."""
        self._caller.call("session.pinPromotion", PromotionParameters(promotion=promotion).toJson())

    def still(self, *, density: float = 1.0, path: str = "") -> StillResult:
        """Photographs the session at the clock as it stands.

        Answered once the work is done.
        """
        return StillResult.fromJson(
            self._caller.call("session.still", StillParameters(density=density, path=path).toJson())
        )

    def sequence(
        self,
        *,
        frames: int = 1,
        rate: float = 60.0,
        density: float = 1.0,
        directory: str = "",
    ) -> SequenceResult:
        """Photographs frames one after another, stepping the clock between
        them.

        Answered once the work is done.
        """
        return SequenceResult.fromJson(
            self._caller.call("session.sequence", SequenceParameters(frames=frames, rate=rate, density=density, directory=directory).toJson())
        )

    def timing(self) -> TimingResult:
        """How the last frame split."""
        return TimingResult.fromJson(
            self._caller.call("session.timing", {})
        )

    def measured(self) -> MeasuredResult:
        """The numbers the sketch measured about its own execution.

        EXPERIMENTAL: its shape may still change.
        """
        return MeasuredResult.fromJson(
            self._caller.call("session.measured", {})
        )

    def compositeCounts(self) -> CompositeCountsResult:
        """Counts the composites each pixel of the next frame passes through,
        and answers the plane once that frame is drawn.

        Answered once the work is done.
        """
        return CompositeCountsResult.fromJson(
            self._caller.call("session.compositeCounts", {})
        )

    def enable(self) -> None:
        """Starts this client's session events."""
        self._caller.call("session.enable", {})

    def disable(self) -> None:
        """Stops this client's session events."""
        self._caller.call("session.disable", {})

    def onOpened(
        self, listener: collections.abc.Callable[[OpenedEvent], None]
    ) -> None:
        """A session opened, by a client or by a person.

        Every one is handed to the listener once this
        client has called enable.
        """
        self._caller.listen(
            "session.opened", lambda value: listener(OpenedEvent.fromJson(value))
        )

    def onClosed(
        self, listener: collections.abc.Callable[[ClosedEvent], None]
    ) -> None:
        """The session closed.

        Every one is handed to the listener once this
        client has called enable.
        """
        self._caller.listen(
            "session.closed", lambda value: listener(ClosedEvent.fromJson(value))
        )

    def onFailed(
        self, listener: collections.abc.Callable[[FailedEvent], None]
    ) -> None:
        """A session could not be opened, or rebuilt after an edit.

        Every one is handed to the listener once this
        client has called enable.
        """
        self._caller.listen(
            "session.failed", lambda value: listener(FailedEvent.fromJson(value))
        )
