# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import types
import _sigil.compose
import _sigil.compose.kit
import _sigil.skia
import _sigil.weave
__all__: list[str] = ['Cell', 'Comparison', 'ComparisonCase', 'Page', 'Palette', 'PanelGrid', 'Provide', 'Recess', 'Register', 'Relief', 'Run', 'Spacing', 'Stage', 'Theme', 'TypeScale', 'Voice', 'Well', 'WellContent', 'caption', 'cell', 'cells', 'comparison', 'houseFace', 'houseTheme', 'page', 'panelGrid', 'stage', 'studyTheme', 'theme', 'well']

class Cell:

    def __init__(self, *, measure: _t.FloatLike | None=..., plate: Well=...) -> None:
        ...

    def copy(self) -> Cell:
        ...

    @property
    def measure(self) -> float | None:
        ...

    @measure.setter
    def measure(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def plate(self) -> Well:
        ...

    @plate.setter
    def plate(self, value: Well, /) -> None:
        ...

class Comparison:

    def __init__(self, *, cases: collections.abc.Sequence[ComparisonCase]=..., gap: _t.FloatLike | None=..., measure: _t.FloatLike=..., trackGap: _t.FloatLike | None=...) -> None:
        ...

    def copy(self) -> Comparison:
        ...

    @property
    def cases(self) -> list[ComparisonCase]:
        ...

    @cases.setter
    def cases(self, value: collections.abc.Sequence[ComparisonCase], /) -> None:
        ...

    @property
    def gap(self) -> float | None:
        ...

    @gap.setter
    def gap(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def measure(self) -> float:
        ...

    @measure.setter
    def measure(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def trackGap(self) -> float | None:
        ...

    @trackGap.setter
    def trackGap(self, value: _t.FloatLike | None, /) -> None:
        ...

class ComparisonCase:

    def __init__(self, *, control: str=..., figure: _sigil.compose.Element=..., note: str=..., title: str=...) -> None:
        ...

    def copy(self) -> ComparisonCase:
        ...

    @property
    def control(self) -> str:
        ...

    @control.setter
    def control(self, value: str, /) -> None:
        ...

    @property
    def figure(self) -> _sigil.compose.Element:
        ...

    @figure.setter
    def figure(self, value: _sigil.compose.Element, /) -> None:
        ...

    @property
    def note(self) -> str:
        ...

    @note.setter
    def note(self, value: str, /) -> None:
        ...

    @property
    def title(self) -> str:
        ...

    @title.setter
    def title(self, value: str, /) -> None:
        ...

class Page:

    def __init__(self, *, footer: str=..., ground: _t.SurfacePaintLike | None=..., key: str=..., ruled: bool=..., subtitle: str=..., title: str=...) -> None:
        ...

    def copy(self) -> Page:
        ...

    @property
    def footer(self) -> str:
        ...

    @footer.setter
    def footer(self, value: str, /) -> None:
        ...

    @property
    def ground(self) -> _sigil.compose.SurfacePaint | None:
        ...

    @ground.setter
    def ground(self, value: _t.SurfacePaintLike | None, /) -> None:
        ...

    @property
    def key(self) -> str:
        ...

    @key.setter
    def key(self, value: str, /) -> None:
        ...

    @property
    def ruled(self) -> bool:
        ...

    @ruled.setter
    def ruled(self, value: bool, /) -> None:
        ...

    @property
    def subtitle(self) -> str:
        ...

    @subtitle.setter
    def subtitle(self, value: str, /) -> None:
        ...

    @property
    def title(self) -> str:
        ...

    @title.setter
    def title(self, value: str, /) -> None:
        ...

class Palette:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self, *, ash: _t.ColorLike=..., cellGround: _t.ColorLike=..., figure: _t.ColorLike=..., ground: _t.ColorLike=..., ink: _t.ColorLike=..., rule: _t.ColorLike=...) -> None:
        ...

    def copy(self) -> Palette:
        ...

    @property
    def ash(self) -> _sigil.skia.Color:
        ...

    @ash.setter
    def ash(self, value: _t.ColorLike, /) -> None:
        ...

    @property
    def cellGround(self) -> _sigil.skia.Color:
        ...

    @cellGround.setter
    def cellGround(self, value: _t.ColorLike, /) -> None:
        ...

    @property
    def figure(self) -> _sigil.skia.Color:
        ...

    @figure.setter
    def figure(self, value: _t.ColorLike, /) -> None:
        ...

    @property
    def ground(self) -> _sigil.skia.Color:
        ...

    @ground.setter
    def ground(self, value: _t.ColorLike, /) -> None:
        ...

    @property
    def ink(self) -> _sigil.skia.Color:
        ...

    @ink.setter
    def ink(self, value: _t.ColorLike, /) -> None:
        ...

    @property
    def rule(self) -> _sigil.skia.Color:
        ...

    @rule.setter
    def rule(self, value: _t.ColorLike, /) -> None:
        ...

class PanelGrid:

    def __init__(self, *, align: _t.AlignLike=..., cells: collections.abc.Sequence[_sigil.compose.Element]=..., columns: typing.SupportsInt=..., gap: _t.FloatLike | None=..., measure: _t.DimensionLike=..., rowGap: _t.FloatLike | None=..., ruled: bool=...) -> None:
        ...

    def copy(self) -> PanelGrid:
        ...

    @property
    def align(self) -> _sigil.compose.Align:
        ...

    @align.setter
    def align(self, value: _t.AlignLike, /) -> None:
        ...

    @property
    def cells(self) -> list[_sigil.compose.Element]:
        ...

    @cells.setter
    def cells(self, value: collections.abc.Sequence[_sigil.compose.Element], /) -> None:
        ...

    @property
    def columns(self) -> int:
        ...

    @columns.setter
    def columns(self, value: typing.SupportsInt, /) -> None:
        ...

    @property
    def gap(self) -> float | None:
        ...

    @gap.setter
    def gap(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def measure(self) -> _sigil.compose.Dimension:
        ...

    @measure.setter
    def measure(self, value: _t.DimensionLike, /) -> None:
        ...

    @property
    def rowGap(self) -> float | None:
        ...

    @rowGap.setter
    def rowGap(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def ruled(self) -> bool:
        ...

    @ruled.setter
    def ruled(self, value: bool, /) -> None:
        ...

class Provide:

    def __enter__(self) -> Provide:
        ...

    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> bool:
        ...

    def __init__(self, theme: Theme) -> None:
        ...

    def close(self) -> None:
        ...

    @property
    def active(self) -> bool:
        ...

class Recess:

    def __init__(self, *, blur: _t.FloatLike=..., lipDark: _t.ColorLike | None=..., lipLight: _t.ColorLike | None=..., lipWidth: _t.FloatLike=..., offset: _t.PointLike=..., shade: _t.FillLike=...) -> None:
        ...

    def copy(self) -> Recess:
        ...

    @property
    def blur(self) -> float:
        ...

    @blur.setter
    def blur(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def lipDark(self) -> _sigil.skia.Color | None:
        ...

    @lipDark.setter
    def lipDark(self, value: _t.ColorLike | None, /) -> None:
        ...

    @property
    def lipLight(self) -> _sigil.skia.Color | None:
        ...

    @lipLight.setter
    def lipLight(self, value: _t.ColorLike | None, /) -> None:
        ...

    @property
    def lipWidth(self) -> float:
        ...

    @lipWidth.setter
    def lipWidth(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def offset(self) -> _sigil.skia.Point:
        ...

    @offset.setter
    def offset(self, value: _t.PointLike, /) -> None:
        ...

    @property
    def shade(self) -> _sigil.compose.Fill:
        ...

    @shade.setter
    def shade(self, value: _t.FillLike, /) -> None:
        ...

class Register:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self, *, face: _sigil.skia.Typeface=..., mono: bool=..., size: _t.FloatLike=..., track: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Register:
        ...

    @property
    def face(self) -> _sigil.skia.Typeface:
        ...

    @face.setter
    def face(self, value: _sigil.skia.Typeface, /) -> None:
        ...

    @property
    def mono(self) -> bool:
        ...

    @mono.setter
    def mono(self, value: bool, /) -> None:
        ...

    @property
    def size(self) -> float:
        ...

    @size.setter
    def size(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def track(self) -> float:
        ...

    @track.setter
    def track(self, value: _t.FloatLike, /) -> None:
        ...

class Relief:

    def __init__(self, *, angleDeg: _t.FloatLike=..., blur: _t.FloatLike=..., depth: _t.FloatLike=..., light: _t.ColorLike=..., shade: _t.ColorLike=...) -> None:
        ...

    def copy(self) -> Relief:
        ...

    @property
    def angleDeg(self) -> float:
        ...

    @angleDeg.setter
    def angleDeg(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def blur(self) -> float:
        ...

    @blur.setter
    def blur(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def depth(self) -> float:
        ...

    @depth.setter
    def depth(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def light(self) -> _sigil.skia.Color:
        ...

    @light.setter
    def light(self, value: _t.ColorLike, /) -> None:
        ...

    @property
    def shade(self) -> _sigil.skia.Color:
        ...

    @shade.setter
    def shade(self, value: _t.ColorLike, /) -> None:
        ...

class Run:

    def __init__(self, *, align: _t.AlignLike=..., cells: collections.abc.Sequence[_sigil.compose.Element]=..., column: bool=..., gap: _t.FloatLike | None=..., ruled: bool=...) -> None:
        ...

    def copy(self) -> Run:
        ...

    @property
    def align(self) -> _sigil.compose.Align:
        ...

    @align.setter
    def align(self, value: _t.AlignLike, /) -> None:
        ...

    @property
    def cells(self) -> list[_sigil.compose.Element]:
        ...

    @cells.setter
    def cells(self, value: collections.abc.Sequence[_sigil.compose.Element], /) -> None:
        ...

    @property
    def column(self) -> bool:
        ...

    @column.setter
    def column(self, value: bool, /) -> None:
        ...

    @property
    def gap(self) -> float | None:
        ...

    @gap.setter
    def gap(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def ruled(self) -> bool:
        ...

    @ruled.setter
    def ruled(self, value: bool, /) -> None:
        ...

class Spacing:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self, *, barHeight: _t.FloatLike=..., bezel: _t.FloatLike=..., captionGap: _t.FloatLike=..., captionNoteGap: _t.FloatLike=..., cellGap: _t.FloatLike=..., chipCorners: _t.FloatLike=..., chipPaddingX: _t.FloatLike=..., chipPaddingY: _t.FloatLike=..., contentGap: _t.FloatLike=..., labelGap: _t.FloatLike=..., marginBottom: _t.FloatLike=..., marginTop: _t.FloatLike=..., marginX: _t.FloatLike=..., panelCorners: _t.FloatLike=..., panelPadding: _t.FloatLike=..., rowGap: _t.FloatLike=..., screenCorners: _t.FloatLike=..., subtitleGap: _t.FloatLike=..., swatchSide: _t.FloatLike=..., tickReach: _t.FloatLike=..., wellPadding: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Spacing:
        ...

    @property
    def barHeight(self) -> float:
        ...

    @barHeight.setter
    def barHeight(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def bezel(self) -> float:
        ...

    @bezel.setter
    def bezel(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def captionGap(self) -> float:
        ...

    @captionGap.setter
    def captionGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def captionNoteGap(self) -> float:
        ...

    @captionNoteGap.setter
    def captionNoteGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def cellGap(self) -> float:
        ...

    @cellGap.setter
    def cellGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def chipCorners(self) -> float:
        ...

    @chipCorners.setter
    def chipCorners(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def chipPaddingX(self) -> float:
        ...

    @chipPaddingX.setter
    def chipPaddingX(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def chipPaddingY(self) -> float:
        ...

    @chipPaddingY.setter
    def chipPaddingY(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def contentGap(self) -> float:
        ...

    @contentGap.setter
    def contentGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def labelGap(self) -> float:
        ...

    @labelGap.setter
    def labelGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def marginBottom(self) -> float:
        ...

    @marginBottom.setter
    def marginBottom(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def marginTop(self) -> float:
        ...

    @marginTop.setter
    def marginTop(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def marginX(self) -> float:
        ...

    @marginX.setter
    def marginX(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def panelCorners(self) -> float:
        ...

    @panelCorners.setter
    def panelCorners(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def panelPadding(self) -> float:
        ...

    @panelPadding.setter
    def panelPadding(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def rowGap(self) -> float:
        ...

    @rowGap.setter
    def rowGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def screenCorners(self) -> float:
        ...

    @screenCorners.setter
    def screenCorners(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def subtitleGap(self) -> float:
        ...

    @subtitleGap.setter
    def subtitleGap(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def swatchSide(self) -> float:
        ...

    @swatchSide.setter
    def swatchSide(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def tickReach(self) -> float:
        ...

    @tickReach.setter
    def tickReach(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def wellPadding(self) -> float:
        ...

    @wellPadding.setter
    def wellPadding(self, value: _t.FloatLike, /) -> None:
        ...

class Stage:

    def __init__(self, *, background: _t.ColorLike | None=..., captureAt: _t.FloatLike=..., nonlinearPicture: bool=..., oversample: typing.SupportsInt=..., plateOnly: bool=..., size: _t.SizeLike=...) -> None:
        ...

    def copy(self) -> Stage:
        ...

    @property
    def background(self) -> _sigil.skia.Color | None:
        ...

    @background.setter
    def background(self, value: _t.ColorLike | None, /) -> None:
        ...

    @property
    def captureAt(self) -> float:
        ...

    @captureAt.setter
    def captureAt(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def nonlinearPicture(self) -> bool:
        ...

    @nonlinearPicture.setter
    def nonlinearPicture(self, value: bool, /) -> None:
        ...

    @property
    def oversample(self) -> int:
        ...

    @oversample.setter
    def oversample(self, value: typing.SupportsInt, /) -> None:
        ...

    @property
    def plateOnly(self) -> bool:
        ...

    @plateOnly.setter
    def plateOnly(self, value: bool, /) -> None:
        ...

    @property
    def size(self) -> _sigil.skia.Size:
        ...

    @size.setter
    def size(self, value: _t.SizeLike, /) -> None:
        ...

class Theme:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self, *, captionWhere: _sigil.compose.kit.CaptionWhere=..., palette: Palette=..., spacing: Spacing=..., type: TypeScale=...) -> None:
        ...

    def copy(self) -> Theme:
        ...

    @typing.overload
    def font(self, register: Register) -> _sigil.weave.Type:
        ...

    @typing.overload
    def font(self, line: Register, ink: _t.ColorLike) -> _sigil.weave.Type:
        ...

    def style(self, line: Register, ink: _t.ColorLike) -> _sigil.weave.TextStyle:
        ...

    def styleSheet(self) -> _sigil.weave.StyleSheet:
        ...

    def voice(self, noteMeasure: typing.SupportsFloat) -> _sigil.compose.kit.Caption:
        ...

    @property
    def captionWhere(self) -> _sigil.compose.kit.CaptionWhere:
        ...

    @captionWhere.setter
    def captionWhere(self, value: _sigil.compose.kit.CaptionWhere, /) -> None:
        ...

    @property
    def palette(self) -> Palette:
        ...

    @palette.setter
    def palette(self, value: Palette, /) -> None:
        ...

    @property
    def spacing(self) -> Spacing:
        ...

    @spacing.setter
    def spacing(self, value: Spacing, /) -> None:
        ...

    @property
    def type(self) -> TypeScale:
        ...

    @type.setter
    def type(self, value: TypeScale, /) -> None:
        ...

class TypeScale:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object, /) -> bool:
        ...

    def __init__(self, *, captionLabel: Register=..., captionNote: Register=..., eyebrow: Register=..., footer: Register=..., mono: _sigil.skia.Typeface=..., sans: _sigil.skia.Typeface=..., section: Register=..., subtitle: Register=..., title: Register=...) -> None:
        ...

    def copy(self) -> TypeScale:
        ...

    @property
    def captionLabel(self) -> Register:
        ...

    @captionLabel.setter
    def captionLabel(self, value: Register, /) -> None:
        ...

    @property
    def captionNote(self) -> Register:
        ...

    @captionNote.setter
    def captionNote(self, value: Register, /) -> None:
        ...

    @property
    def eyebrow(self) -> Register:
        ...

    @eyebrow.setter
    def eyebrow(self, value: Register, /) -> None:
        ...

    @property
    def footer(self) -> Register:
        ...

    @footer.setter
    def footer(self, value: Register, /) -> None:
        ...

    @property
    def mono(self) -> _sigil.skia.Typeface:
        ...

    @mono.setter
    def mono(self, value: _sigil.skia.Typeface, /) -> None:
        ...

    @property
    def sans(self) -> _sigil.skia.Typeface:
        ...

    @sans.setter
    def sans(self, value: _sigil.skia.Typeface, /) -> None:
        ...

    @property
    def section(self) -> Register:
        ...

    @section.setter
    def section(self, value: Register, /) -> None:
        ...

    @property
    def subtitle(self) -> Register:
        ...

    @subtitle.setter
    def subtitle(self, value: Register, /) -> None:
        ...

    @property
    def title(self) -> Register:
        ...

    @title.setter
    def title(self, value: Register, /) -> None:
        ...

class Voice:
    """
    Members:

      Book

      Terminal

      Interface
    """
    Book: typing.ClassVar[Voice]
    Interface: typing.ClassVar[Voice]
    Terminal: typing.ClassVar[Voice]
    __members__: typing.ClassVar[dict[str, Voice]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Well:

    def __init__(self, *, clip: bool=..., content: _sigil.sketch.kit.WellContent | None=..., corners: _t.FloatLike | None=..., ground: _t.SurfacePaintLike | None=..., height: _t.DimensionLike=..., keyline: _t.FillLike | None=..., keylineWidth: _t.FloatLike=..., padding: _t.FloatLike | None=..., paddingY: _t.FloatLike | None=..., placed: bool=..., recess: _sigil.sketch.kit.Recess | None=..., relief: _sigil.sketch.kit.Relief | None=..., width: _t.DimensionLike=...) -> None:
        ...

    def copy(self) -> Well:
        ...

    @property
    def clip(self) -> bool:
        ...

    @clip.setter
    def clip(self, value: bool, /) -> None:
        ...

    @property
    def content(self) -> _sigil.sketch.kit.WellContent | None:
        ...

    @content.setter
    def content(self, value: _sigil.sketch.kit.WellContent | None, /) -> None:
        ...

    @property
    def corners(self) -> float | None:
        ...

    @corners.setter
    def corners(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def ground(self) -> _sigil.compose.SurfacePaint | None:
        ...

    @ground.setter
    def ground(self, value: _t.SurfacePaintLike | None, /) -> None:
        ...

    @property
    def height(self) -> _sigil.compose.Dimension:
        ...

    @height.setter
    def height(self, value: _t.DimensionLike, /) -> None:
        ...

    @property
    def keyline(self) -> _sigil.compose.Fill | None:
        ...

    @keyline.setter
    def keyline(self, value: _t.FillLike | None, /) -> None:
        ...

    @property
    def keylineWidth(self) -> float:
        ...

    @keylineWidth.setter
    def keylineWidth(self, value: _t.FloatLike, /) -> None:
        ...

    @property
    def padding(self) -> float | None:
        ...

    @padding.setter
    def padding(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def paddingY(self) -> float | None:
        ...

    @paddingY.setter
    def paddingY(self, value: _t.FloatLike | None, /) -> None:
        ...

    @property
    def placed(self) -> bool:
        ...

    @placed.setter
    def placed(self, value: bool, /) -> None:
        ...

    @property
    def recess(self) -> _sigil.sketch.kit.Recess | None:
        ...

    @recess.setter
    def recess(self, value: _sigil.sketch.kit.Recess | None, /) -> None:
        ...

    @property
    def relief(self) -> _sigil.sketch.kit.Relief | None:
        ...

    @relief.setter
    def relief(self, value: _sigil.sketch.kit.Relief | None, /) -> None:
        ...

    @property
    def width(self) -> _sigil.compose.Dimension:
        ...

    @width.setter
    def width(self, value: _t.DimensionLike, /) -> None:
        ...

class WellContent:

    def __init__(self, *, across: _t.AlignLike=..., down: _t.JustifyLike=...) -> None:
        ...

    def copy(self) -> WellContent:
        ...

    @property
    def across(self) -> _sigil.compose.Align:
        ...

    @across.setter
    def across(self, value: _t.AlignLike, /) -> None:
        ...

    @property
    def down(self) -> _sigil.compose.Justify:
        ...

    @down.setter
    def down(self, value: _t.JustifyLike, /) -> None:
        ...

def caption(measure: typing.SupportsFloat, label: str, note: str, body: _sigil.compose.Element) -> _sigil.compose.Element:
    ...

def cell(plate: Cell, label: str, note: str, picture: _sigil.compose.Element) -> _sigil.compose.Element:
    ...

def cells(run: Run) -> _sigil.compose.Element:
    ...

def comparison(comparison: Comparison) -> _sigil.compose.Element:
    ...

def houseFace(voice: Voice, weight: typing.SupportsInt=400, italic: bool=False) -> _sigil.skia.Typeface:
    ...

def houseTheme() -> Theme:
    ...

def page(sheet: Page, content: _sigil.compose.Element) -> _sigil.compose.Element:
    ...

def panelGrid(grid: PanelGrid) -> _sigil.compose.Element:
    ...

def stage(context: _sigil.Context, stage: Stage) -> None:
    ...

def studyTheme() -> Theme:
    ...

def theme() -> Theme:
    ...

@typing.overload
def well(specification: Well) -> _sigil.compose.Element:
    ...

@typing.overload
def well(specification: Well, surface: _sigil.compose.Element) -> _sigil.compose.Element:
    ...
