# Generated by typing/generate.py; edit typing/surface.py and
# typing/additions, not this file.

"""Native JSON/table snapshots, domain mappings and SQL query views.

Cells are Python numbers, strings, booleans or native Instant values. Column
indexing and values() use None for missing cells; at() preserves the native
placeholder and missing() reports absence separately. All returned JSON members,
columns and tables are detached native value copies. Database views retain their
native connection and query results are detached tables.
"""

from _sigil.data import (
    Column,
    ColumnType,
    CsvOptions,
    Database,
    Engine,
    Flag,
    Group,
    Instant,
    Interval,
    Json,
    JsonKind,
    Order,
    Overflow,
    Scale,
    Schema,
    Table,
    Transform,
    decodeArtNet,
    decodeCsv,
    decodeInstant,
    decodeJson,
    decodeMidi,
    decodeOsc,
    encodeArtNet,
    encodeJson,
    encodeMidi,
    encodeOsc,
    engineOf,
    maxOscPacketBytes,
    registerDecoders,
    tableFromJson,
)

Value = float | str | bool | Instant


__all__ = [
    "Column",
    "ColumnType",
    "CsvOptions",
    "Database",
    "Engine",
    "Flag",
    "Group",
    "Instant",
    "Interval",
    "Json",
    "JsonKind",
    "Order",
    "Overflow",
    "Scale",
    "Schema",
    "Table",
    "Transform",
    "Value",
    "decodeArtNet",
    "decodeCsv",
    "decodeInstant",
    "decodeJson",
    "decodeMidi",
    "decodeOsc",
    "encodeArtNet",
    "encodeJson",
    "encodeMidi",
    "encodeOsc",
    "engineOf",
    "maxOscPacketBytes",
    "registerDecoders",
    "tableFromJson",
]
