from typing import TypeAlias

from _sigil.data import (
    Column,
    ColumnType,
    CsvOptions,
    Database,
    Engine,
    Flag,
    Group,
    Instant,
    Interval,
    Json,
    JsonKind,
    Order,
    Overflow,
    Scale,
    Table,
    Transform,
    decodeCsv,
    decodeInstant,
    decodeJson,
    encodeJson,
    engineOf,
    tableFromJson,
)

Value: TypeAlias = float | str | bool | Instant

__all__ = [
    "Column",
    "ColumnType",
    "CsvOptions",
    "Database",
    "Engine",
    "Flag",
    "Group",
    "Instant",
    "Interval",
    "Json",
    "JsonKind",
    "Order",
    "Overflow",
    "Scale",
    "Table",
    "Transform",
    "Value",
    "decodeCsv",
    "decodeInstant",
    "decodeJson",
    "encodeJson",
    "engineOf",
    "tableFromJson",
]
