#pragma once

/** @file
 * The one font context a test process shares, and the instrument faces it
 * shapes with when the answer must not depend on the machine.
 */

#include <include/core/SkFontMgr.h>
#include <include/core/SkTypeface.h>
#include <sigilweave/fonts/FontContext.h>
#include <sigilweave/ports/SystemFontManager.h>

#include <string>

namespace sigil::test {

/** THE PROCESS'S FONT CONTEXT.
 *
 *  A FontContext memoises shaping and strike lookups, so one per process
 *  is what a test wants: a second one re-shapes everything the first one
 *  already knows, and a per-case one turns a cache claim into a claim
 *  about a cold cache. Leaked on purpose — Skia's font manager outlives
 *  static destruction on some platforms, and a test process that has
 *  finished reporting has nothing left to free it for.
 *
 *  Any binary that includes this links the system font port, and a face it
 *  resolves through the manager's own family list is the machine's: a case
 *  whose claim depends on WHICH face it got names an instrument below
 *  instead, or says with the `fonts` label that the machine's font manager
 *  is the thing it is testing.
 */
inline weave::FontContext& fonts() {
  static auto* context =
      new weave::FontContext(weave::ports::systemFontManager());
  return *context;
}

/** THE FACES COMMITTED UNDER src/test/assets/, one property each.
 *
 *  Each is a few kilobytes of rectangles generated by the script beside
 *  them, carrying exactly what one case has to ask about and nothing more,
 *  so the case gets the same answer on every machine and skips on none.
 *  The system font manager is the loader here and nothing else — a file is
 *  read, not a family matched — so none of these is the machine's.
 *
 *  Null only when the asset failed to load, which is a broken checkout
 *  rather than a machine without a font, so a case asserts rather than
 *  skips on it.
 */
namespace instrument {

/// One face from the instrument directory, held for the process.
inline sk_sp<SkTypeface> face(const char* fileName) {
  const std::string path =
      std::string(SIGIL_TEST_INSTRUMENT_DIR "/") + fileName;
  return weave::ports::systemFontManager()->makeFromFile(path.c_str());
}

/// Letters on one known advance, an x-height of 500 and a cap height of
/// 700 against 1000 units per em, `ffi` ligated under `liga`, and figures
/// that are proportional until `tnum` equalises them. Covers Latin only:
/// asked for a Han character or a kana it answers nothing, which is what
/// a case about fallback needs its primary face to do.
inline sk_sp<SkTypeface> sans() {
  static const sk_sp<SkTypeface> held = face("Sans.ttf");
  return held;
}

/// Three axes: `wght` and `wdth` MOVE advances, `GRAD` holds every advance
/// and moves ink alone. The one face a case about axes reaching the shaper
/// needs, and the one a case about the advance-invariance gate needs on
/// both sides of its verdict.
inline sk_sp<SkTypeface> variable() {
  static const sk_sp<SkTypeface> held = face("Variable.ttf");
  return held;
}

/// An A and a V whose diagonals leave more white between them than this
/// face's own `n` beside itself, which is the reference an optical kerner
/// closes every pair to.
inline sk_sp<SkTypeface> optical() {
  static const sk_sp<SkTypeface> held = face("Optical.ttf");
  return held;
}

/// Latin bases and the whole combining-diacritics block, every mark
/// carrying no advance and none of them composed into a base: a stack adds
/// glyphs and ink without adding width.
inline sk_sp<SkTypeface> marks() {
  static const sk_sp<SkTypeface> held = face("Marks.ttf");
  return held;
}

/// The letters of a right-to-left sentence, with lam followed by alef
/// ligated under `rlig`.
inline sk_sp<SkTypeface> arabic() {
  static const sk_sp<SkTypeface> held = face("Arabic.ttf");
  return held;
}

/// The letters of a conjunct-forming word, virama included.
inline sk_sp<SkTypeface> devanagari() {
  static const sk_sp<SkTypeface> held = face("Devanagari.ttf");
  return held;
}

/// Four characters beyond the basic plane, so every one of them is a
/// surrogate pair in the UTF-16 a cluster value indexes.
inline sk_sp<SkTypeface> cuneiform() {
  static const sk_sp<SkTypeface> held = face("Cuneiform.ttf");
  return held;
}

/// One Han character and one kana. Its pair below carries the same
/// coverage under a different family, so a fallback resolver asked twice
/// has two faces to tell apart.
inline sk_sp<SkTypeface> hanSans() {
  static const sk_sp<SkTypeface> held = face("HanSans.ttf");
  return held;
}

/// The second Han face — see `hanSans`.
inline sk_sp<SkTypeface> hanSerif() {
  static const sk_sp<SkTypeface> held = face("HanSerif.ttf");
  return held;
}

}  // namespace instrument

}  // namespace sigil::test
