# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import typing
import _sigil.material
__all__: list[str] = ['grain', 'noise']

def grain(frequency: typing.SupportsFloat, octaves: typing.SupportsInt=4, seed: typing.SupportsFloat=1, contrast: typing.SupportsFloat=1, stretch: typing.SupportsFloat=1) -> _sigil.material.Material:
    ...

def noise(frequency: typing.SupportsFloat, octaves: typing.SupportsInt=4, seed: typing.SupportsFloat=1, turbulence: bool=False) -> _sigil.material.Material:
    ...
