from collections.abc import Iterable
from typing import overload

from _sigil.compose import (
    Align,
    Backface,
    Boundary,
    Cache,
    CellSpan,
    Composer,
    ComposerStats,
    Corners,
    Decoration,
    Dimension,
    Element,
    Fill,
    Fit,
    Justify,
    LayerStyle,
    MotionPath,
    PathFormat,
    Shadow,
    Shape,
    Spans,
    SurfacePaint,
    TextPath,
    TextSettling,
    VarRef,
    autoDimension,
    box,
    frame,
    graphics,
    heldPath,
    image,
    layout,
    memo,
    pathFigure,
    pct,
    pen,
    ph,
    picture,
    positioned,
    pw,
    selectors,
    shadow,
    shape,
    slot,
    spans,
    stack,
    stroke,
    text,
    var,
)

from . import document, kit, layouts

@overload
def row(children: Iterable[Element], /) -> Element: ...
@overload
def row(*children: Element) -> Element: ...
@overload
def column(children: Iterable[Element], /) -> Element: ...
@overload
def column(*children: Element) -> Element: ...

__all__ = [
    "Align",
    "Backface",
    "Boundary",
    "Cache",
    "CellSpan",
    "Composer",
    "ComposerStats",
    "Corners",
    "Decoration",
    "Dimension",
    "Element",
    "Fill",
    "Fit",
    "Justify",
    "LayerStyle",
    "MotionPath",
    "PathFormat",
    "Shadow",
    "Shape",
    "Spans",
    "SurfacePaint",
    "TextPath",
    "TextSettling",
    "VarRef",
    "autoDimension",
    "box",
    "column",
    "document",
    "frame",
    "graphics",
    "heldPath",
    "image",
    "kit",
    "layout",
    "layouts",
    "memo",
    "pathFigure",
    "pct",
    "pen",
    "ph",
    "picture",
    "positioned",
    "pw",
    "row",
    "selectors",
    "shadow",
    "shape",
    "slot",
    "spans",
    "stack",
    "stroke",
    "text",
    "var",
]
