# Generated by typing/generate.py; edit typing/surface.py and
# typing/additions, not this file.

"""The typed front door onto the CSS selector grammar over elements."""

from _sigil.compose.select import (
    any,
    child,
    has,
    is_,
    next,
    notAnyOf,
    role,
    sibling,
    styleClass,
    where,
)

__all__ = [
    "any",
    "child",
    "has",
    "is_",
    "next",
    "notAnyOf",
    "role",
    "sibling",
    "styleClass",
    "where",
]
