# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import _sigil.geometry.mesh
import _sigil.geometry.mesh.camera
import _sigil.material
import _sigil.skia
__all__: list[str] = ['Light', 'MeshStyle', 'Mode', 'drawImagePanel', 'drawMesh']

class Light:

    @property
    def color(self) -> _sigil.material.Color:
        ...

    @color.setter
    def color(self, value: _t.ColorLike) -> None:
        ...

    @property
    def direction(self) -> _t.Vec3:
        ...

    @direction.setter
    def direction(self, value: _t.Vec3Like) -> None:
        ...

    def __init__(self, direction: _t.Vec3Like=(-0.5, -0.800000011920929, -0.4000000059604645), color: _t.ColorLike=..., intensity: typing.SupportsFloat=1) -> None:
        ...

    @property
    def intensity(self) -> float:
        ...

    @intensity.setter
    def intensity(self, value: typing.SupportsFloat, /) -> None:
        ...

class MeshStyle:

    @property
    def ambient(self) -> _sigil.material.Color:
        ...

    @ambient.setter
    def ambient(self, value: _t.ColorLike) -> None:
        ...
    backfaceCull: bool

    @property
    def baseColor(self) -> _sigil.material.Color:
        ...

    @baseColor.setter
    def baseColor(self, value: _t.ColorLike) -> None:
        ...
    depthSort: bool
    lit: bool
    mode: Mode
    texture: _sigil.skia.Image
    tileTexture: bool
    uvTransform: _sigil.skia.Matrix

    def __init__(self) -> None:
        ...

    @property
    def lights(self) -> list[Light]:
        ...

    @lights.setter
    def lights(self, value: collections.abc.Sequence[Light], /) -> None:
        ...

    @property
    def metallic(self) -> float:
        ...

    @metallic.setter
    def metallic(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def rim(self) -> float:
        ...

    @rim.setter
    def rim(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def roughness(self) -> float:
        ...

    @roughness.setter
    def roughness(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def shininess(self) -> float:
        ...

    @shininess.setter
    def shininess(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def specular(self) -> float:
        ...

    @specular.setter
    def specular(self, value: typing.SupportsFloat, /) -> None:
        ...

class Mode:
    """
    Members:

      Lit

      Normals

      Uv
    """
    Lit: typing.ClassVar[Mode]
    Normals: typing.ClassVar[Mode]
    Uv: typing.ClassVar[Mode]
    __members__: typing.ClassVar[dict[str, Mode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

def drawImagePanel(pen: _sigil.draw.Pen, image: _sigil.skia.Image, width: typing.SupportsFloat, height: typing.SupportsFloat, model: _sigil.geometry.mesh.camera.Matrix, camera: _sigil.geometry.mesh.camera.Camera, opacity: typing.SupportsFloat=1) -> None:
    ...

def drawMesh(pen: _sigil.draw.Pen, mesh: _sigil.geometry.mesh.Mesh, model: _sigil.geometry.mesh.camera.Matrix, camera: _sigil.geometry.mesh.camera.Camera, style: MeshStyle=...) -> None:
    ...
