#!/usr/bin/env python3
"""Write what the checkout carries of the protocol definition.

    generate.py --description <protocol_description.json> [--check]

reads the description sigil_protocol wrote into the build tree from the
definition's reflected schema, and writes two committed trees out of it:
the Python client under apps/python/sigil/sigil/protocol/, one module per
domain beside the tables every domain shares and the pieces they stand
on, and one reference page per domain under ../reference/domains/. Both
are regenerated by hand after the definition changes and committed.

With --check nothing is written: the trees are generated in memory and
compared with the checkout, a unified difference is printed for every
file that differs, is missing or is no longer written, and the exit
status is 1 when anything did. That is the drift case ctest runs.

The generation logic lives here and nowhere else; the build only writes
the description and runs this.
"""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import sys

import protocol_python
import protocol_reference

HERE = pathlib.Path(__file__).resolve().parent
APPLICATION = HERE.parents[3]
PACKAGE = APPLICATION.parent / "python" / "sigil" / "sigil" / "protocol"
PAGES = HERE.parent / "reference" / "domains"


def trees(description: dict[str, object]) -> dict[pathlib.Path, dict[str, str]]:
    """Every file this pass owns, by the directory it owns wholly."""
    return {
        PACKAGE: protocol_python.package(description),
        PAGES: protocol_reference.pages(description),
    }


def on_disk(directory: pathlib.Path, suffix: str) -> dict[str, str]:
    if not directory.is_dir():
        return {}
    return {
        path.name: path.read_text()
        for path in sorted(directory.iterdir())
        if path.is_file() and path.suffix == suffix
    }


def differs(directory: pathlib.Path, old: dict[str, str], new: dict[str, str]) -> bool:
    changed = False
    for name in sorted(old.keys() | new.keys()):
        if old.get(name) == new.get(name):
            continue
        changed = True
        print(
            "".join(
                difflib.unified_diff(
                    old.get(name, "").splitlines(keepends=True),
                    new.get(name, "").splitlines(keepends=True),
                    fromfile=f"checked-in/{directory.name}/{name}",
                    tofile=f"generated/{directory.name}/{name}",
                )
            ),
            end="",
        )
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--description", type=pathlib.Path, required=True)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()

    if not options.description.is_file():
        print(
            f"generate.py: no description at {options.description}; build"
            " SigilProtocolDefinition first",
            file=sys.stderr,
        )
        return 2
    description = json.loads(options.description.read_text())

    changed = False
    for directory, files in trees(description).items():
        suffix = pathlib.Path(next(iter(files))).suffix
        existing = on_disk(directory, suffix)
        if options.check:
            changed = differs(directory, existing, files) or changed
            continue
        directory.mkdir(parents=True, exist_ok=True)
        for name in existing.keys() - files.keys():
            (directory / name).unlink()
        for name, text in files.items():
            if existing.get(name) != text:
                (directory / name).write_text(text)
        print(f"Wrote {len(files)} files under {directory}.")

    if changed:
        print(
            "The committed protocol client or reference pages differ from what"
            " the definition generates: run src/common/protocol/definition/"
            "generate.py --description <build>/generated/protocol/"
            "protocol_description.json and commit what it writes.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
