"""The Python client, written from the protocol model: one module per
domain holding that domain's tables, enumerations and client class, one
for the tables every domain shares, the readings every module stands on,
and the package index.

A table is a frozen dataclass whose fields are the definition's, in its
order and under its names, with its defaults; `toJson()` and `fromJson()`
cross the JSON object the wire carries. A domain is a class over a caller,
one method per command taking the parameter table's fields as keywords
and answering the result's table, and one `on…` method per event.
"""

from __future__ import annotations

import typing

import protocol_model
from protocol_model import BASE, Command, Documented, Domain, Enumeration, Field, Model, Table

HEADER = (
    "# Generated by src/common/protocol/definition/generate.py from protocol.fbs;\n"
    "# edit the definition, not this file.\n"
)

SHARED = "shared"

MESSAGES = '''"""What every generated module of the protocol client stands on.

The JSON a message is made of, the caller a client speaks through, and the
readings that take one field of a decoded JSON object and answer it as the
type the definition declares, raising ValueError where it is not that.
"""

from __future__ import annotations

import collections.abc
import typing

type Json = None | bool | int | float | str | list[Json] | dict[str, Json]


class Caller(typing.Protocol):
    """What a generated client speaks through.

    ``call`` sends one command, its method and its parameters' JSON object,
    and answers the result's JSON object, raising ProtocolError where the
    host answered an error; ``listen`` hands every event of a method to a
    listener as its JSON object. The socket client and the in-process
    dispatcher are two.
    """

    def call(self, method: str, parameters: dict[str, Json]) -> Json: ...

    def listen(
        self, method: str, listener: collections.abc.Callable[[Json], None]
    ) -> None: ...


def members(value: Json, table: str) -> dict[str, Json]:
    """The members of the JSON object a table is read from."""
    if not isinstance(value, dict):
        raise ValueError(f"{table} is read from a JSON object")
    return value


def required(fields: dict[str, Json], name: str, table: str) -> Json:
    """A field the definition requires, which the object must carry."""
    if name not in fields:
        raise ValueError(f"{table} requires {name}")
    return fields[name]


def required_text(fields: dict[str, Json], name: str, table: str) -> str:
    """Text the definition requires, which the object must carry."""
    return text({name: required(fields, name, table)}, name, "")


def boolean(fields: dict[str, Json], name: str, default: bool) -> bool:
    value = fields.get(name, default)
    if not isinstance(value, bool):
        raise ValueError(f"{name} is true or false")
    return value


def integer(fields: dict[str, Json], name: str, default: int) -> int:
    value = fields.get(name, default)
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{name} is a whole number")
    return value


def real(fields: dict[str, Json], name: str, default: float) -> float:
    value = fields.get(name, default)
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise ValueError(f"{name} is a number")
    return float(value)


def text(fields: dict[str, Json], name: str, default: str) -> str:
    value = fields.get(name, default)
    if not isinstance(value, str):
        raise ValueError(f"{name} is text")
    return value


def optional_boolean(fields: dict[str, Json], name: str) -> bool | None:
    return None if fields.get(name) is None else boolean(fields, name, False)


def optional_integer(fields: dict[str, Json], name: str) -> int | None:
    return None if fields.get(name) is None else integer(fields, name, 0)


def optional_real(fields: dict[str, Json], name: str) -> float | None:
    return None if fields.get(name) is None else real(fields, name, 0.0)


def optional_text(fields: dict[str, Json], name: str) -> str | None:
    return None if fields.get(name) is None else text(fields, name, "")


def items(fields: dict[str, Json], name: str) -> list[Json]:
    """The entries of a field that holds many."""
    value = fields.get(name, [])
    if not isinstance(value, list):
        raise ValueError(f"{name} is a list")
    return value


def booleans(fields: dict[str, Json], name: str) -> tuple[bool, ...]:
    return tuple(boolean({name: item}, name, False) for item in items(fields, name))


def integers(fields: dict[str, Json], name: str) -> tuple[int, ...]:
    return tuple(integer({name: item}, name, 0) for item in items(fields, name))


def reals(fields: dict[str, Json], name: str) -> tuple[float, ...]:
    return tuple(real({name: item}, name, 0.0) for item in items(fields, name))


def texts(fields: dict[str, Json], name: str) -> tuple[str, ...]:
    return tuple(text({name: item}, name, "") for item in items(fields, name))
'''

INTEGERS = {"byte", "ubyte", "short", "ushort", "int", "uint", "long", "ulong"}
REALS = {"float", "double"}


def module_of(space: str) -> str:
    """The module a namespace's tables and enumerations stand in."""
    return SHARED if space == BASE else space.rpartition(".")[2]


class Module:
    """One module's text, and how it spells a name another declares."""

    def __init__(self, model: Model, space: str) -> None:
        self.model = model
        self.space = space
        self.imports: set[str] = set()

    def spell(self, qualified: str) -> str:
        """A table or enumeration as this module spells it: bare where it
        stands here, through a private module alias elsewhere."""
        space = protocol_model.space_of(qualified)
        name = protocol_model.last_word(qualified)
        if space == self.space:
            return name
        module = module_of(space)
        self.imports.add(module)
        return f"_{module}.{name}"


def docstring(part: Documented, indent: str, more: str = "") -> str:
    lines = list(part.documentation)
    if part.experimental:
        lines += ["", "EXPERIMENTAL: its shape may still change."]
    if more:
        lines += ["", *more.splitlines()]
    if not lines:
        return ""
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    body = "".join(f"{indent}{line}\n" if line else "\n" for line in lines[1:])
    return f'{indent}"""{lines[0]}\n{body}{indent}"""\n'


def python_literal(value: object) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, float):
        return repr(value)
    return repr(value)


class FieldForm:
    """How one field reads, writes and is annotated in Python."""

    def __init__(self, module: Module, table: Table, field: Field) -> None:
        self.module = module
        self.table = table
        self.field = field

    @property
    def enumeration(self) -> str:
        return self.module.spell(self.field.reference) if self.is_enumeration else ""

    @property
    def is_enumeration(self) -> bool:
        return bool(self.field.reference) and self.field.type not in {"table", "string"}

    def scalar_annotation(self) -> str:
        kind = self.field.type
        if self.is_enumeration:
            return self.enumeration
        if kind == "table":
            return self.module.spell(self.field.reference)
        if kind == "bool":
            return "bool"
        if kind in INTEGERS:
            return "int"
        if kind in REALS:
            return "float"
        return "str"

    def annotation(self) -> str:
        one = self.scalar_annotation()
        if self.field.vector:
            return f"tuple[{one}, ...]"
        if self.field.optional or (self.field.type == "table" and not self.field.required):
            return f"{one} | None"
        return one

    def default(self) -> str | None:
        """The default a dataclass field is written with; None for a field
        a caller has to give."""
        field = self.field
        if field.vector:
            return "()"
        if field.required:
            return None
        if field.optional or field.type == "table":
            return "None"
        if field.type == "string":
            return '""'
        if self.is_enumeration:
            return f"{self.enumeration}.{field.default}"
        if field.type in REALS:
            return python_literal(float(typing.cast(float, field.default)))
        return python_literal(field.default)

    def reading(self) -> str:
        """The expression that reads this field out of ``fields``."""
        field = self.field
        name = f'"{field.name}"'
        table = protocol_model.last_word(self.table.name)
        kind = field.type
        if field.vector:
            if kind == "table":
                one = self.module.spell(field.reference)
                return f"tuple({one}.fromJson(item) for item in messages.items(fields, {name}))"
            if self.is_enumeration:
                return f"tuple({self.enumeration}(item) for item in messages.texts(fields, {name}))"
            plural = {"bool": "booleans", "string": "texts"}.get(
                kind, "integers" if kind in INTEGERS else "reals"
            )
            return f"messages.{plural}(fields, {name})"
        if kind == "table":
            one = self.module.spell(field.reference)
            if field.required:
                return f'{one}.fromJson(messages.required(fields, {name}, "{table}"))'
            return (
                f"None if fields.get({name}) is None else {one}.fromJson(fields[{name}])"
            )
        if kind == "string" and field.required:
            return f'messages.required_text(fields, {name}, "{table}")'
        word = "text" if kind == "string" or self.is_enumeration else (
            "boolean" if kind == "bool" else "integer" if kind in INTEGERS else "real"
        )
        if field.optional:
            read = f"messages.optional_{word}(fields, {name})"
            if self.is_enumeration:
                return f"None if (value := {read}) is None else {self.enumeration}(value)"
            return read
        if self.is_enumeration:
            return f'{self.enumeration}(messages.text(fields, {name}, "{field.default}"))'
        return f"messages.{word}(fields, {name}, {self.default()})"

    def writing(self, indent: str) -> str:
        """The lines that write this field into ``out``."""
        field = self.field
        here = f"self.{field.name}"
        key = f'out["{field.name}"]'
        if field.vector:
            if field.type == "table":
                return f"{indent}{key} = [item.toJson() for item in {here}]\n"
            if self.is_enumeration:
                return f"{indent}{key} = [item.value for item in {here}]\n"
            return f"{indent}{key} = [item for item in {here}]\n"
        value = here
        if field.type == "table":
            value = f"{here}.toJson()"
        elif self.is_enumeration:
            value = f"{here}.value"
        if field.optional or (field.type == "table" and not field.required):
            return f"{indent}if {here} is not None:\n{indent}    {key} = {value}\n"
        return f"{indent}{key} = {value}\n"


def enumeration_text(enumeration: Enumeration) -> str:
    name = protocol_model.last_word(enumeration.name)
    out = f"class {name}(enum.Enum):\n"
    out += docstring(enumeration, "    ")
    for value in enumeration.values:
        out += f'\n    {value.name} = "{value.name}"\n'
        out += docstring(value, "    ")
    return out


def table_text(module: Module, table: Table) -> str:
    name = protocol_model.last_word(table.name)
    forms = [FieldForm(module, table, field) for field in table.fields]
    out = "@dataclasses.dataclass(frozen=True, kw_only=True)\n"
    out += f"class {name}:\n"
    out += docstring(table, "    ")
    for form in forms:
        default = form.default()
        written = f" = {default}" if default is not None else ""
        out += f"\n    {form.field.name}: {form.annotation()}{written}\n"
        out += docstring(form.field, "    ")
    out += "\n    def toJson(self) -> dict[str, messages.Json]:\n"
    out += '        """This table as the JSON object the wire carries."""\n'
    out += "        out: dict[str, messages.Json] = {}\n"
    for form in forms:
        out += form.writing("        ")
    out += "        return out\n"
    out += "\n    @classmethod\n"
    out += f"    def fromJson(cls, value: messages.Json) -> {name}:\n"
    out += '        """The table a JSON object carries; ValueError where it does not fit."""\n'
    if not forms:
        out += f'        messages.members(value, "{name}")\n'
        out += "        return cls()\n"
        return out
    out += f'        fields = messages.members(value, "{name}")\n'
    out += "        return cls(\n"
    for form in forms:
        out += f"            {form.field.name}={form.reading()},\n"
    out += "        )\n"
    return out


def command_text(module: Module, model: Model, command: Command) -> str:
    parameters = model.table(command.parameters)
    nothing_in = command.parameters == model.empty
    nothing_out = command.result == model.empty
    forms = [FieldForm(module, parameters, field) for field in parameters.fields]
    result = "None" if nothing_out else module.spell(command.result)
    arguments = ["self"]
    if forms:
        arguments.append("*")
        for form in forms:
            default = form.default()
            written = f" = {default}" if default is not None else ""
            arguments.append(f"{form.field.name}: {form.annotation()}{written}")
    signature = f"    def {command.name}({', '.join(arguments)}) -> {result}:\n"
    if len(signature) > 88:
        signature = f"    def {command.name}(\n"
        signature += "".join(f"        {argument},\n" for argument in arguments)
        signature += f"    ) -> {result}:\n"
    more = "Answered once the work is done." if command.asynchronous else ""
    out = "\n" + signature + docstring(command, "        ", more)
    if nothing_in:
        sent = "{}"
    else:
        table = module.spell(command.parameters)
        given = ", ".join(f"{form.field.name}={form.field.name}" for form in forms)
        sent = f"{table}({given}).toJson()"
    call = f'self._caller.call("{command.method}", {sent})'
    if nothing_out:
        out += f"        {call}\n"
    else:
        out += f"        return {result}.fromJson(\n            {call}\n        )\n"
    return out


def event_text(module: Module, event: protocol_model.Event) -> str:
    payload = module.spell(event.payload)
    name = "on" + event.name[0].upper() + event.name[1:]
    out = (
        f"\n    def {name}(\n"
        f"        self, listener: collections.abc.Callable[[{payload}], None]\n"
        f"    ) -> None:\n"
    )
    out += docstring(event, "        ", "Every one is handed to the listener once this\nclient has called enable.")
    out += (
        f'        self._caller.listen(\n'
        f'            "{event.method}", lambda value: listener({payload}.fromJson(value))\n'
        f"        )\n"
    )
    return out


def domain_class_text(module: Module, model: Model, domain: Domain) -> str:
    out = f"class {domain.service}:\n"
    out += docstring(
        domain,
        "    ",
        "One method per command, sending its parameters through the caller\n"
        "and answering its result's table, and one per event, handing each\n"
        "to a listener.",
    )
    out += "\n    def __init__(self, caller: messages.Caller) -> None:\n"
    out += "        self._caller = caller\n"
    for command in domain.commands:
        out += command_text(module, model, command)
    for event in domain.event_list:
        out += event_text(module, event)
    return out


PROTOCOL_ERROR = '''

class ProtocolError(Exception):
    """A command the host refused: the Error it answered, which names the
    seam that refused it and says why in that seam's own words."""

    def __init__(self, error: Error) -> None:
        super().__init__(f"{error.code.value}: {error.message}")
        self.error = error
'''


def module_text(model: Model, space: str, domain: Domain | None) -> str:
    module = Module(model, space)
    body = ""
    for enumeration in model.enumerations_in(space):
        body += "\n\n" + enumeration_text(enumeration)
    for table in model.tables_in(space):
        body += "\n\n" + table_text(module, table)
    if domain is not None:
        body += "\n\n" + domain_class_text(module, model, domain)
    if space == BASE:
        body += PROTOCOL_ERROR
    documentation = (
        domain.documentation
        if domain is not None
        else ("The tables every domain of the protocol shares.",)
    )
    head = HEADER + "\n" + docstring(Documented(documentation, False), "") + "\n"
    head += "from __future__ import annotations\n\n"
    standard = ["dataclasses"]
    if model.enumerations_in(space):
        standard.append("enum")
    if domain is not None and domain.event_list:
        standard.insert(0, "collections.abc")
    head += "".join(f"import {name}\n" for name in standard)
    head += "\nfrom . import messages\n"
    for imported in sorted(module.imports):
        head += f"from . import {imported} as _{imported}\n"
    return head + body


def index_text(model: Model) -> str:
    exported: list[tuple[str, str]] = [("messages", "Caller"), ("messages", "Json")]
    exported += [(SHARED, "ProtocolError")]
    for enumeration in model.enumerations_in(BASE):
        exported.append((SHARED, protocol_model.last_word(enumeration.name)))
    for table in model.tables_in(BASE):
        exported.append((SHARED, protocol_model.last_word(table.name)))
    for domain in model.domains:
        exported.append((domain.name, domain.service))
    out = HEADER + "\n"
    out += (
        '"""The Sigil protocol\'s Python client.\n\n'
        "One class per domain over a caller — Host, Clock, Session, Registry —\n"
        "each method sending one command and answering its result's table. The\n"
        "tables and enumerations of a domain stand in that domain's module:\n"
        "``sigil.protocol.clock.StepParameters``.\n"
        '"""\n\n'
    )
    out += "from __future__ import annotations\n\n"
    for module, name in exported:
        out += f"from .{module} import {name}\n"
    out += "\n__all__ = [\n"
    for _, name in sorted(exported, key=lambda each: each[1]):
        out += f'    "{name}",\n'
    out += "]\n"
    return out


def package(description: dict[str, typing.Any]) -> dict[str, str]:
    """Every file of the Python client, by name."""
    model = protocol_model.read(description)
    files = {
        "__init__.py": index_text(model),
        "messages.py": HEADER + "\n" + MESSAGES,
        f"{SHARED}.py": module_text(model, BASE, None),
    }
    for domain in model.domains:
        files[f"{domain.name}.py"] = module_text(model, domain.space, domain)
    return files
