"""The reference pages, written from the protocol model: one page per
domain, carrying its documentation, where its agent, its clients and its
events are, every command with its parameters and its result, every
event with what it carries, and every table and enumeration the domain
declares that a command or an event does not already show.

A page spells a C++ name qualified only where a header declares it, so
the documentation probe that compiles every page proves the name is
there; the Python names are dotted, and a dotted name is not probed.
"""

from __future__ import annotations

import typing

import protocol_model
from protocol_model import Command, Documented, Domain, Enumeration, Field, Model, Table

HEADER = (
    "<!-- Generated by generate.py beside protocol.fbs; edit the definition,\n"
    "     not this page. -->\n"
)


def prose(part: Documented) -> str:
    """The documentation as one paragraph per blank-line-separated run."""
    paragraphs: list[list[str]] = [[]]
    for line in part.documentation:
        if line.strip():
            paragraphs[-1].append(line.strip())
        elif paragraphs[-1]:
            paragraphs.append([])
    text = "\n\n".join(" ".join(lines) for lines in paragraphs if lines)
    if part.experimental:
        text += "\n\n**Experimental**: its shape may still change."
    return text


def cell(text: str) -> str:
    return text.replace("|", "\\|")


def type_of(model: Model, field: Field) -> str:
    """A field's type as a reader of the page wants it named."""
    if field.type == "table" or field.reference:
        one = protocol_model.last_word(field.reference)
        kind = "table" if field.type == "table" else "enumeration"
        one = f"{one} ({kind})"
    else:
        one = field.type
    if field.vector:
        one = f"list of {one}"
    if field.optional:
        one += ", may be absent"
    if field.required:
        one += ", required"
    return one


def default_of(field: Field) -> str:
    if field.vector:
        return "empty"
    if field.default is None:
        return "absent" if field.optional or field.type == "table" else '""'
    if isinstance(field.default, bool):
        return "true" if field.default else "false"
    return str(field.default)


def fields_table(model: Model, table: Table, heading: str) -> str:
    if not table.fields:
        return ""
    out = f"| {heading} | Type | Default | |\n| --- | --- | --- | --- |\n"
    for field in table.fields:
        out += (
            f"| `{field.name}` | {cell(type_of(model, field))} | "
            f"{cell(default_of(field))} | {cell(prose(field))} |\n"
        )
    return out + "\n"


def command_section(model: Model, domain: Domain, command: Command) -> str:
    out = f"### {command.method}\n\n{prose(command)}\n\n"
    if command.dispatcher:
        out += (
            "Answered by the dispatcher itself, never by the agent: it starts or "
            f"stops this client's {domain.name} events.\n\n"
        )
        return out
    answered = (
        "Answered later, through the reply the agent is handed, once the work "
        "is done."
        if command.asynchronous
        else "Answered at once."
    )
    out += answered + "\n\n"
    parameters = model.table(command.parameters)
    if command.parameters == model.empty:
        out += "Takes nothing.\n\n"
    else:
        name = protocol_model.last_word(parameters.name)
        out += f"Takes `{name}`: {prose(parameters)}\n\n"
        out += fields_table(model, parameters, "Parameter")
    result = model.table(command.result)
    if command.result == model.empty:
        out += "Answers nothing but that it was done.\n\n"
    else:
        name = protocol_model.last_word(result.name)
        out += f"Answers `{name}`: {prose(result)}\n\n"
        out += fields_table(model, result, "Field")
    return out


def enumeration_section(enumeration: Enumeration) -> str:
    name = protocol_model.last_word(enumeration.name)
    out = f"### {name}\n\n{prose(enumeration)}\n\n"
    out += "| Value | |\n| --- | --- |\n"
    for value in enumeration.values:
        out += f"| `{value.name}` | {cell(prose(value))} |\n"
    return out + "\n"


def page(model: Model, domain: Domain) -> str:
    space = domain.space.replace(".", "::")
    agent = f"{space}::{domain.service}Agent"
    out = HEADER + "\n"
    out += f"# The {domain.name} domain\n\n{prose(domain)}\n\n"
    out += "| | |\n| --- | --- |\n"
    out += f"| Namespace in the definition | {domain.space} |\n"
    out += f"| What a host implements | `{agent}`, mounted by `{space}::wire` |\n"
    out += f"| C++ client | `{space}::{domain.service}Client` |\n"
    if domain.event_list:
        out += f"| Events sent through | `{space}::{domain.service}Events` |\n"
    out += f"| Python client | sigil.protocol.{domain.name}.{domain.service} |\n\n"

    out += "## Commands\n\n"
    shown: set[str] = {model.empty}
    for command in domain.commands:
        out += command_section(model, domain, command)
        shown.update({command.parameters, command.result})

    if domain.event_list:
        out += f"## Events\n\n{prose(domain.events)}\n\n"
        for event in domain.event_list:
            payload = model.table(event.payload)
            name = protocol_model.last_word(payload.name)
            out += f"### {event.method}\n\n{prose(event)}\n\n"
            out += f"Carries `{name}`: {prose(payload)}\n\n"
            out += fields_table(model, payload, "Field")
            shown.add(event.payload)

    rest = [table for table in model.tables_in(domain.space) if table.name not in shown]
    enumerations = model.enumerations_in(domain.space)
    if rest or enumerations:
        out += "## Types\n\n"
        for enumeration in enumerations:
            out += enumeration_section(enumeration)
        for table in rest:
            name = protocol_model.last_word(table.name)
            out += f"### {name}\n\n{prose(table)}\n\n"
            out += fields_table(model, table, "Field")
    return out.rstrip("\n") + "\n"


def pages(description: dict[str, typing.Any]) -> dict[str, str]:
    """Every domain's page, by file name."""
    model = protocol_model.read(description)
    return {f"{domain.name}.md": page(model, domain) for domain in model.domains}
