"""The Python client, written from the protocol model: one module per
domain holding that domain's tables, enumerations and client class, one
for the tables every domain shares with what the client refuses, the
readings every module stands on, and the package index.

A table is a frozen dataclass whose fields are the definition's, in its
order and under its names, with its defaults; `to_json()` and
`from_json()` cross the JSON object the wire carries, and `from_json()`
refuses a member the table does not declare, as the C++ reading does. A
domain is a class over a caller, one method per command taking the
parameter table's fields as keywords and answering the result's table,
and one `on_…` method per event. Methods are the package's snake_case;
the method each sends is the definition's own name, `clock.setPolicy`.

Every file is written as `ruff format` leaves it and as `ruff check`
passes it, so the committed client is held by the tree's lint as well as
by the drift case: a call that does not fit one line is split the way
the formatter splits it.
"""

from __future__ import annotations

import pathlib
import typing

import protocol_model
from protocol_model import (
    BASE,
    Command,
    Documented,
    Domain,
    Enumeration,
    Field,
    Model,
    Table,
)

HEADER = (
    "# Generated by src/common/protocol/definition/generate.py from protocol.fbs;\n"
    "# edit the definition, not this file.\n"
)

SHARED = "shared"

CONNECTION = pathlib.Path(__file__).resolve().parent / "client" / "connection.py"
"""The transport every caller of the package speaks through — the envelope,
the socket, connect and launch — written by hand beside the generator and
carried into the package as it stands, since nothing in it derives from the
definition."""

COPIED = (
    "# Copied by src/common/protocol/definition/generate.py from\n"
    "# definition/client/connection.py beside it; edit that file, not this one.\n"
)

LINE = 88

MESSAGES = '''"""What every generated module of the protocol client stands on.

The JSON a message is made of, the caller a client speaks through, and the
readings that take one member of a decoded JSON object and answer it as the
type the definition declares, raising MessageError where it is not that.
"""

from __future__ import annotations

import collections.abc
import dataclasses
import enum
import typing

if typing.TYPE_CHECKING:
    from _typeshed import DataclassInstance

    from .shared import Error

type Json = None | bool | int | float | str | list[Json] | dict[str, Json]


class MessageError(ValueError):
    """JSON that does not read as its table: a member the table does not
    declare, one it requires left out, or a value of the wrong kind."""


class Caller(typing.Protocol):
    """What a generated client speaks through.

    ``call`` sends one command, its method and its parameters' JSON object,
    and answers the result's JSON object, raising ProtocolError where the
    host answered an error; ``listen`` hands every event of a method to a
    listener as its JSON object; ``refused`` is handed the refusal for
    every event that does not read as its table, which no listener hears.
    The socket client and the in-process dispatcher are two.
    """

    def call(self, method: str, parameters: dict[str, Json]) -> Json: ...

    def listen(
        self, method: str, listener: collections.abc.Callable[[Json], None]
    ) -> None: ...

    def refused(self, error: Error) -> None: ...


def members(value: Json, table: type[DataclassInstance]) -> dict[str, Json]:
    """The members of the JSON object a table is read from, every one a
    member the table declares."""
    if not isinstance(value, dict):
        raise MessageError(f"{table.__name__} is read from a JSON object")
    declared = {field.name for field in dataclasses.fields(table)}
    unknown = sorted(value.keys() - declared)
    if unknown:
        raise MessageError(f"{table.__name__} declares no {', '.join(unknown)}")
    return value


def required(fields: dict[str, Json], name: str) -> Json:
    """A member the definition requires, which the object must carry."""
    if name not in fields:
        raise MessageError(f"{name} is required")
    return fields[name]


def boolean(fields: dict[str, Json], name: str, default: bool) -> bool:
    value = fields.get(name, default)
    if not isinstance(value, bool):
        raise MessageError(f"{name} is true or false")
    return value


def integer(fields: dict[str, Json], name: str, default: int) -> int:
    value = fields.get(name, default)
    if isinstance(value, bool) or not isinstance(value, int):
        raise MessageError(f"{name} is a whole number")
    return value


def real(fields: dict[str, Json], name: str, default: float) -> float:
    value = fields.get(name, default)
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise MessageError(f"{name} is a number")
    return float(value)


def text(fields: dict[str, Json], name: str, default: str) -> str:
    value = fields.get(name, default)
    if not isinstance(value, str):
        raise MessageError(f"{name} is text")
    return value


def required_text(fields: dict[str, Json], name: str) -> str:
    """Text the definition requires, which the object must carry."""
    return text({name: required(fields, name)}, name, "")


def enumeration[Value: enum.Enum](
    fields: dict[str, Json], name: str, default: Value
) -> Value:
    """One value of the enumeration @p default is a value of."""
    return one_of(type(default), name, text(fields, name, default.value))


def one_of[Value: enum.Enum](kind: type[Value], name: str, value: str) -> Value:
    try:
        return kind(value)
    except ValueError as error:
        raise MessageError(f"{name} is no {kind.__name__}: {value}") from error


def table[Value](
    fields: dict[str, Json],
    name: str,
    read: collections.abc.Callable[[Json], Value],
) -> Value | None:
    """A table the object may leave out."""
    value = fields.get(name)
    return None if value is None else read(value)


def required_table[Value](
    fields: dict[str, Json],
    name: str,
    read: collections.abc.Callable[[Json], Value],
) -> Value:
    """A table the definition requires, which the object must carry."""
    return read(required(fields, name))


def optional_boolean(fields: dict[str, Json], name: str) -> bool | None:
    return None if fields.get(name) is None else boolean(fields, name, False)


def optional_integer(fields: dict[str, Json], name: str) -> int | None:
    return None if fields.get(name) is None else integer(fields, name, 0)


def optional_real(fields: dict[str, Json], name: str) -> float | None:
    return None if fields.get(name) is None else real(fields, name, 0.0)


def optional_text(fields: dict[str, Json], name: str) -> str | None:
    return None if fields.get(name) is None else text(fields, name, "")


def optional_enumeration[Value: enum.Enum](
    fields: dict[str, Json], name: str, kind: type[Value]
) -> Value | None:
    value = optional_text(fields, name)
    return None if value is None else one_of(kind, name, value)


def items(fields: dict[str, Json], name: str) -> list[Json]:
    """The entries of a member that holds many."""
    value = fields.get(name, [])
    if not isinstance(value, list):
        raise MessageError(f"{name} is a list")
    return value


def booleans(fields: dict[str, Json], name: str) -> tuple[bool, ...]:
    return tuple(boolean({name: item}, name, False) for item in items(fields, name))


def integers(fields: dict[str, Json], name: str) -> tuple[int, ...]:
    return tuple(integer({name: item}, name, 0) for item in items(fields, name))


def reals(fields: dict[str, Json], name: str) -> tuple[float, ...]:
    return tuple(real({name: item}, name, 0.0) for item in items(fields, name))


def texts(fields: dict[str, Json], name: str) -> tuple[str, ...]:
    return tuple(text({name: item}, name, "") for item in items(fields, name))


def enumerations[Value: enum.Enum](
    fields: dict[str, Json], name: str, kind: type[Value]
) -> tuple[Value, ...]:
    return tuple(one_of(kind, name, item) for item in texts(fields, name))


def tables[Value](
    fields: dict[str, Json],
    name: str,
    read: collections.abc.Callable[[Json], Value],
) -> tuple[Value, ...]:
    return tuple(read(item) for item in items(fields, name))
'''

CLIENT_SEAM = '''

class ProtocolError(Exception):
    """A command refused: the Error that says which seam refused it, and
    why in that seam's own words — the host's, or the client's own, whose
    words open with ``client:``."""

    def __init__(self, error: Error) -> None:
        super().__init__(f"{error.code.value}: {error.message}")
        self.error = error


def client_refusal(code: ErrorCode, method: str, what: str) -> Error:
    """A refusal the client made, about the command or event @p method."""
    return Error(code=code, message=f"client: {method}: {what}")


def answer[Result](
    method: str,
    read: collections.abc.Callable[[messages.Json], Result],
    value: messages.Json,
) -> Result:
    """The answer to @p method read as its result; ProtocolError, with the
    code unreadable, where it does not read as one."""
    try:
        return read(value)
    except messages.MessageError as error:
        what = f"the answer does not read as its result: {error}"
        refusal = client_refusal(ErrorCode.unreadable, method, what)
        raise ProtocolError(refusal) from error


def hearing[Event](
    caller: messages.Caller,
    method: str,
    read: collections.abc.Callable[[messages.Json], Event],
    listener: collections.abc.Callable[[Event], None],
) -> collections.abc.Callable[[messages.Json], None]:
    """What hears every event of @p method: each read as its table and
    handed to @p listener, or refused, with the code unreadable, to the
    caller's ``refused``."""

    def hear(value: messages.Json) -> None:
        try:
            event = read(value)
        except messages.MessageError as error:
            what = f"the event does not read as its table: {error}"
            caller.refused(client_refusal(ErrorCode.unreadable, method, what))
            return
        listener(event)

    return hear
'''

INTEGERS = {"byte", "ubyte", "short", "ushort", "int", "uint", "long", "ulong"}
REALS = {"float", "double"}


def module_of(space: str) -> str:
    """The module a namespace's tables and enumerations stand in."""
    return SHARED if space == BASE else space.rpartition(".")[2]


def split(indent: str, head: str, arguments: list[str], tail: str) -> str:
    """``head`` + the arguments + ``tail`` at @p indent, as the formatter
    lays out a call or a signature: on one line where it fits; else the
    arguments together on one line of their own where that fits; else one
    argument to a line, each with a comma after it."""
    one = f"{indent}{head}{', '.join(arguments)}{tail}"
    if len(one) <= LINE:
        return one + "\n"
    inner = indent + "    "
    together = f"{inner}{', '.join(arguments)}"
    if len(together) <= LINE:
        return f"{indent}{head}\n{together}\n{indent}{tail}\n"
    each = "".join(f"{inner}{argument},\n" for argument in arguments)
    return f"{indent}{head}\n{each}{indent}{tail}\n"


class Module:
    """One module's text, and how it spells a name another declares."""

    def __init__(self, model: Model, space: str) -> None:
        self.model = model
        self.space = space
        self.imports: set[str] = set()

    def spell(self, qualified: str) -> str:
        """A table or enumeration as this module spells it: bare where it
        stands here, through a private module alias elsewhere."""
        space = protocol_model.space_of(qualified)
        name = protocol_model.last_word(qualified)
        if space == self.space:
            return name
        return f"{self.alias(module_of(space))}.{name}"

    def alias(self, module: str) -> str:
        """The private alias another module of the package is imported as."""
        self.imports.add(module)
        return f"_{module}"


def docstring(part: Documented, indent: str, more: str = "") -> str:
    lines = list(part.documentation)
    if part.experimental:
        lines += ["", "EXPERIMENTAL: its shape may still change."]
    if more:
        lines += ["", *more.splitlines()]
    if not lines:
        return ""
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    body = "".join(f"{indent}{line}\n" if line else "\n" for line in lines[1:])
    return f'{indent}"""{lines[0]}\n{body}{indent}"""\n'


def python_literal(value: object) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    return repr(value)


class FieldForm:
    """How one field reads, writes and is annotated in Python."""

    def __init__(self, module: Module, field: Field) -> None:
        self.module = module
        self.field = field

    @property
    def is_enumeration(self) -> bool:
        return bool(self.field.reference) and self.field.type not in {
            "table",
            "string",
        }

    @property
    def referenced(self) -> str:
        return self.module.spell(self.field.reference)

    def scalar_annotation(self) -> str:
        kind = self.field.type
        if self.is_enumeration or kind == "table":
            return self.referenced
        if kind == "bool":
            return "bool"
        if kind in INTEGERS:
            return "int"
        if kind in REALS:
            return "float"
        return "str"

    @property
    def may_be_absent(self) -> bool:
        field = self.field
        return field.optional or (field.type == "table" and not field.required)

    def annotation(self) -> str:
        one = self.scalar_annotation()
        if self.field.vector:
            return f"tuple[{one}, ...]"
        if self.may_be_absent:
            return f"{one} | None"
        return one

    def default(self) -> str | None:
        """The default a dataclass field is written with; None for a field
        a caller has to give."""
        field = self.field
        if field.vector:
            return "()"
        if field.required:
            return None
        if self.may_be_absent:
            return "None"
        if field.type == "string":
            return '""'
        if self.is_enumeration:
            return f"{self.referenced}.{field.default}"
        if field.type in REALS:
            return python_literal(float(typing.cast("float", field.default)))
        return python_literal(field.default)

    def reading(self) -> tuple[str, list[str]]:
        """The function that reads this field out of ``fields``, and what
        it is called with."""
        field = self.field
        name = f'"{field.name}"'
        kind = field.type
        if kind == "table":
            read = f"{self.referenced}.from_json"
            if field.vector:
                return "messages.tables", ["fields", name, read]
            if field.required:
                return "messages.required_table", ["fields", name, read]
            return "messages.table", ["fields", name, read]
        if self.is_enumeration:
            if field.vector:
                return "messages.enumerations", ["fields", name, self.referenced]
            if field.optional:
                return "messages.optional_enumeration", [
                    "fields",
                    name,
                    self.referenced,
                ]
            return "messages.enumeration", [
                "fields",
                name,
                typing.cast("str", self.default()),
            ]
        word = {"string": "text", "bool": "boolean"}.get(kind, "real")
        if kind in INTEGERS:
            word = "integer"
        if field.vector:
            plural = {"text": "texts", "boolean": "booleans", "integer": "integers"}
            return f"messages.{plural.get(word, 'reals')}", ["fields", name]
        if kind == "string" and field.required:
            return "messages.required_text", ["fields", name]
        if field.optional:
            return f"messages.optional_{word}", ["fields", name]
        return f"messages.{word}", ["fields", name, typing.cast("str", self.default())]

    def writing(self, indent: str) -> str:
        """The lines that write this field into ``out``."""
        field = self.field
        here = f"self.{field.name}"
        key = f'out["{field.name}"]'
        if field.vector:
            if field.type == "table":
                value = f"[item.to_json() for item in {here}]"
            elif self.is_enumeration:
                value = f"[item.value for item in {here}]"
            else:
                value = f"list({here})"
            return f"{indent}{key} = {value}\n"
        if field.optional:
            # An absent scalar is written as null, as the C++ tables write
            # it, so both clients send the same object.
            if self.is_enumeration:
                value = f"None if {here} is None else {here}.value"
            else:
                value = here
            return f"{indent}{key} = {value}\n"
        value = here
        if field.type == "table":
            value = f"{here}.to_json()"
        elif self.is_enumeration:
            value = f"{here}.value"
        if self.may_be_absent:
            return f"{indent}if {here} is not None:\n{indent}    {key} = {value}\n"
        return f"{indent}{key} = {value}\n"


def enumeration_text(enumeration: Enumeration) -> str:
    name = protocol_model.last_word(enumeration.name)
    out = f"class {name}(enum.Enum):\n"
    out += docstring(enumeration, "    ")
    for value in enumeration.values:
        out += f'\n    {value.name} = "{value.name}"\n'
        out += docstring(value, "    ")
    return out


def table_text(module: Module, table: Table) -> str:
    name = protocol_model.last_word(table.name)
    forms = [FieldForm(module, field) for field in table.fields]
    out = "@dataclasses.dataclass(frozen=True, kw_only=True)\n"
    out += f"class {name}:\n"
    out += docstring(table, "    ")
    for form in forms:
        default = form.default()
        written = f" = {default}" if default is not None else ""
        out += f"\n    {form.field.name}: {form.annotation()}{written}\n"
        out += docstring(form.field, "    ")
    out += "\n    def to_json(self) -> dict[str, messages.Json]:\n"
    out += '        """This table as the JSON object the wire carries."""\n'
    if not forms:
        out += "        return {}\n"
    else:
        out += "        out: dict[str, messages.Json] = {}\n"
        for form in forms:
            out += form.writing("        ")
        out += "        return out\n"
    out += "\n    @classmethod\n"
    out += f"    def from_json(cls, value: messages.Json) -> {name}:\n"
    out += (
        '        """The table a JSON object carries; MessageError where it does'
        ' not fit."""\n'
    )
    if not forms:
        out += "        messages.members(value, cls)\n"
        out += "        return cls()\n"
        return out
    out += "        fields = messages.members(value, cls)\n"
    out += "        return cls(\n"
    for form in forms:
        function, arguments = form.reading()
        out += split("            ", f"{form.field.name}={function}(", arguments, "),")
    out += "        )\n"
    return out


def command_text(module: Module, model: Model, command: Command) -> str:
    parameters = model.table(command.parameters)
    nothing_in = command.parameters == model.empty
    nothing_out = command.result == model.empty
    forms = [FieldForm(module, field) for field in parameters.fields]
    result = "None" if nothing_out else module.spell(command.result)
    arguments = ["self"]
    if forms:
        arguments.append("*")
        for form in forms:
            default = form.default()
            written = f" = {default}" if default is not None else ""
            arguments.append(f"{form.field.name}: {form.annotation()}{written}")
    out = "\n" + split(
        "    ",
        f"def {protocol_model.snake(command.name)}(",
        arguments,
        f") -> {result}:",
    )
    more = "Answered once the work is done." if command.asynchronous else ""
    out += docstring(command, "        ", more)
    method = f'"{command.method}"'
    if nothing_in:
        sent = "{}"
    else:
        given = [f"{form.field.name}={form.field.name}" for form in forms]
        out += split(
            "        ", f"parameters = {module.spell(command.parameters)}(", given, ")"
        )
        sent = "parameters.to_json()"
    out += split("        ", "answer = self._caller.call(", [method, sent], ")")
    shared = module.alias(SHARED) if module.space != BASE else ""
    read = f"{module.spell(command.result)}.from_json"
    check = f"{shared}.answer" if shared else "answer"
    head = f"{check}(" if nothing_out else f"return {check}("
    out += split("        ", head, [method, read, "answer"], ")")
    return out


def event_text(module: Module, event: protocol_model.Event) -> str:
    payload = module.spell(event.payload)
    listener = f"collections.abc.Callable[[{payload}], None]"
    out = "\n" + split(
        "    ",
        f"def on_{protocol_model.snake(event.name)}(",
        ["self", f"listener: {listener}"],
        ") -> None:",
    )
    out += docstring(
        event,
        "        ",
        "Every one is handed to the listener once this\nclient has called enable.",
    )
    method = f'"{event.method}"'
    hearing = f"{module.alias(SHARED)}.hearing"
    out += split(
        "        ",
        f"hear = {hearing}(",
        ["self._caller", method, f"{payload}.from_json", "listener"],
        ")",
    )
    out += split("        ", "self._caller.listen(", [method, "hear"], ")")
    return out


def domain_class_text(module: Module, model: Model, domain: Domain) -> str:
    out = f"class {domain.service}:\n"
    out += docstring(
        domain,
        "    ",
        "One method per command, sending its parameters through the caller\n"
        "and answering its result's table, and one per event, handing each\n"
        "to a listener.",
    )
    out += "\n    def __init__(self, caller: messages.Caller) -> None:\n"
    out += "        self._caller = caller\n"
    for command in domain.commands:
        out += command_text(module, model, command)
    for event in domain.event_list:
        out += event_text(module, event)
    return out


def module_text(model: Model, space: str, domain: Domain | None) -> str:
    module = Module(model, space)
    body = ""
    for enumeration in model.enumerations_in(space):
        body += "\n\n" + enumeration_text(enumeration)
    for table in model.tables_in(space):
        body += "\n\n" + table_text(module, table)
    if domain is not None:
        body += "\n\n" + domain_class_text(module, model, domain)
    if space == BASE:
        body += CLIENT_SEAM
    documentation = (
        domain.documentation
        if domain is not None
        else (
            "The tables every domain of the protocol shares, and what the client refuses.",
        )
    )
    head = HEADER + "\n" + docstring(Documented(documentation, False), "") + "\n"
    head += "from __future__ import annotations\n\n"
    standard = ["dataclasses"]
    if model.enumerations_in(space):
        standard.append("enum")
    if space == BASE or (domain is not None and domain.event_list):
        standard.insert(0, "collections.abc")
    head += "".join(f"import {name}\n" for name in standard)
    head += "\n"
    for imported in sorted({"messages", *module.imports}):
        alias = "" if imported == "messages" else f" as _{imported}"
        head += f"from . import {imported}{alias}\n"
    return head + body


def example(model: Model) -> str:
    """A table the index's documentation names, as a caller spells it: the
    first command's parameters of the first domain that takes any."""
    for domain in model.domains:
        for command in domain.commands:
            if command.parameters != model.empty:
                return f"sigil.protocol.{domain.name}.{protocol_model.last_word(command.parameters)}"
    return f"sigil.protocol.{SHARED}.{protocol_model.last_word(model.empty)}"


def index_text(model: Model) -> str:
    exported: dict[str, list[str]] = {
        "messages": ["Caller", "Json", "MessageError"],
        "connection": ["Connection", "Envelopes", "connect", "launch"],
    }
    shared = ["ProtocolError"]
    shared += [
        protocol_model.last_word(each.name) for each in model.enumerations_in(BASE)
    ]
    shared += [protocol_model.last_word(each.name) for each in model.tables_in(BASE)]
    exported[SHARED] = shared
    for domain in model.domains:
        exported[domain.name] = [domain.service]
    services = ", ".join(domain.service for domain in model.domains)
    out = HEADER + "\n"
    out += (
        '"""The Sigil protocol\'s Python client.\n\n'
        f"One class per domain over a caller — {services} —\n"
        "each method sending one command and answering its result's table. The\n"
        "tables and enumerations of a domain stand in that domain's module:\n"
        f"``{example(model)}``.\n"
        '"""\n\n'
    )
    out += "from __future__ import annotations\n\n"
    for module in sorted(exported):
        names = sorted(exported[module])
        one = f"from .{module} import {', '.join(names)}"
        if len(one) <= LINE:
            out += one + "\n"
            continue
        out += f"from .{module} import (\n"
        out += "".join(f"    {name},\n" for name in names)
        out += ")\n"
    everything = sorted(name for names in exported.values() for name in names)
    out += "\n__all__ = [\n"
    out += "".join(f'    "{name}",\n' for name in everything)
    out += "]\n"
    return out


def package(description: dict[str, typing.Any]) -> dict[str, str]:
    """Every file of the Python client, by name."""
    model = protocol_model.read(description)
    files = {
        "__init__.py": index_text(model),
        "messages.py": HEADER + "\n" + MESSAGES,
        "connection.py": COPIED + "\n" + CONNECTION.read_text(),
        f"{SHARED}.py": module_text(model, BASE, None),
    }
    for domain in model.domains:
        files[f"{domain.name}.py"] = module_text(model, domain.space, domain)
    return files
