"""Generate the package's surface from a matching, already-built extension.

Run with the development interpreter and PYTHONPATH pointing to build/python.
The generator never builds or imports user sketches. One pass produces two
trees, and each is asked for separately. `--declarations` writes the `.pyi`
files an author's editor reads into a package directory the caller names: the
build writes them beside the extension it just linked, so they are never a
file in the checkout. A plain run refreshes the package's own modules, which
are committed because the wheel ships them and importing the package must not
need a stub generator.

typing/surface.py says where each raw module surfaces, typing/refinements
describes the conversion seams pybind11's docstrings erase, and typing/additions
holds the hand-written pieces this pass splices into each module.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib.metadata
import keyword
import os
import pathlib
import re
import tempfile
import types

import pybind11_stubgen
import refinements
import surface

HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent
PACKAGE = PROJECT / "sigil"
ADDITIONS = HERE / "additions"

RAW_HEADER = "# Generated by typing/generate.py; edit its refinements, not this file.\n"
PUBLIC_HEADER = (
    "# Generated by typing/generate.py; edit typing/surface.py and\n"
    "# typing/additions, not this file.\n"
)
# The stdlib names a generated declaration can reach for. Unused ones are
# pruned, so the same block serves every module.
STANDARD_IMPORTS = (
    "import builtins\nimport collections.abc\nimport typing\nimport types\nimport os\n"
)
REFERENCE = re.compile(r"\b_sigil(?:\.[A-Za-z_][A-Za-z0-9_]*)*")


def module_name(path: pathlib.Path) -> str:
    parts = list(path.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(["_sigil", *parts])


def sanitize(text: str) -> str:
    # Python keywords cannot be used in attribute syntax. A binding that
    # exposes an escaped alias remains represented by that usable alias.
    for name in keyword.kwlist:
        text = re.sub(rf"\bdef {name}\(", f"def __keyword_{name}(", text)
        text = re.sub(rf"@{name}\.setter", f"@__keyword_{name}.setter", text)
    return text


def extension_under_pythonpath() -> None:
    """Refuse an extension PYTHONPATH did not name.

    The stubs describe whichever `_sigil` this interpreter imports, and an
    installed package — an editable one especially — is found ahead of
    PYTHONPATH. An interpreter that has one therefore writes declarations
    for a binding that is not the one in the build tree, quietly, and a
    class the current bindings no longer register comes back.
    """
    import _sigil

    roots = [
        pathlib.Path(entry).resolve()
        for entry in os.environ.get("PYTHONPATH", "").split(os.pathsep)
        if entry
    ]
    if not roots:
        return
    found = pathlib.Path(_sigil.__file__).resolve()
    if any(found.is_relative_to(root) for root in roots):
        return
    named = ", ".join(str(root) for root in roots)
    raise RuntimeError(
        f"PYTHONPATH names {named}, but _sigil was imported from {found}. "
        "An installed copy shadows the built one. Run this with an "
        "interpreter that has no sigil package installed."
    )


def registered_again(holder: object, published: str, registered: str) -> None:
    """Put the registered module back on one module's classes and functions."""
    for value in vars(holder).values():
        if not isinstance(value, (type, types.BuiltinFunctionType)):
            continue
        if getattr(value, "__module__", None) != published:
            continue
        value.__module__ = registered
        if isinstance(value, type):
            registered_again(value, published, registered)


def restore_registered_modules() -> None:
    """Undo the extension's public naming for the length of this walk.

    workaround: pybind11-stubgen decides whether a value belongs to the
    module it is walking by comparing that value's __module__ against the
    module's name, so a class named for the package it surfaces in is
    written out as an import from a module the extension does not have.
    The bindings name every registered value once, where it is registered;
    this puts those names back so the walk finds what is really there.
    """
    for raw, published in surface.PUBLIC_MODULES.items():
        if raw in surface.DECLARATION_ONLY:
            continue
        registered_again(importlib.import_module(raw), published, raw)


def generate_raw(destination: pathlib.Path) -> dict[str, str]:
    """Write the raw declarations pybind11-stubgen produces, refined."""
    version = importlib.metadata.version("pybind11-stubgen")
    if version != "2.5.5":
        raise RuntimeError(f"Use pybind11-stubgen 2.5.5, found {version}")
    extension_under_pythonpath()
    restore_registered_modules()
    # In this process, because the walk has to see the names just restored.
    pybind11_stubgen.main(["_sigil", "-o", str(destination), "--ignore-all-errors"])
    outputs: dict[str, str] = {}
    refinements.SEEN.clear()
    for path in sorted((destination / "_sigil").rglob("*.pyi")):
        relative = path.relative_to(destination / "_sigil")
        tree = ast.parse(sanitize(path.read_text()))
        refinements.refine(module_name(relative), tree)
        result = RAW_HEADER + ast.unparse(ast.fix_missing_locations(tree)) + "\n"
        # Native unhashability is represented exactly; Python's object stub
        # declares __hash__ as a method, requiring a targeted mypy exception.
        result = result.replace(
            "__hash__: typing.ClassVar[None] = None",
            "__hash__: typing.ClassVar[None] = None  # type: ignore[assignment]",
        )
        result = "\n".join(line.rstrip() for line in result.splitlines()) + "\n"
        ast.parse(result)
        outputs[str(relative)] = result
    refinements.validate()
    outputs["_types.pyi"] = (HERE / "_types.pyi").read_text()
    return outputs


def raw_module_of(relative: str) -> str:
    return module_name(pathlib.Path(relative))


def addition_path(public: str, suffix: str) -> pathlib.Path:
    """Return the addition file spliced into one public module, if written.

    The additions mirror the package, so the file holding what a module adds
    by hand sits where that module sits.
    """
    tail = public.removeprefix(surface.PUBLIC_ROOT).lstrip(".")
    parts = tail.split(".") if tail else []
    if surface.child_modules(public):
        return ADDITIONS.joinpath(*parts, "__init__" + suffix)
    return ADDITIONS.joinpath(*parts[:-1], parts[-1] + suffix)


def read_addition(public: str, suffix: str) -> str:
    path = addition_path(public, suffix)
    return path.read_text() if path.is_file() else ""


def top_level_names(text: str) -> list[str]:
    """Return the names one addition defines, in the order it defines them."""
    names: list[str] = []
    for node in ast.parse(text).body if text else []:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.append(node.name)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.append(node.target.id)
        elif isinstance(node, ast.Assign):
            names.extend(
                target.id for target in node.targets if isinstance(target, ast.Name)
            )
    return names


def split_docstring(text: str) -> tuple[str, str]:
    """Separate an addition's module docstring from the rest of its source."""
    if not text.strip():
        return "", ""
    tree = ast.parse(text)
    body = tree.body
    if (
        body
        and isinstance(body[0], ast.Expr)
        and isinstance(body[0].value, ast.Constant)
        and isinstance(body[0].value.value, str)
    ):
        lines = text.splitlines(keepends=True)
        end = body[0].end_lineno or 1
        return "".join(lines[:end]), "".join(lines[end:]).lstrip("\n")
    return "", text


def resolve(raw_path: str, current: str, holders: set[str]) -> str:
    """Rewrite one raw dotted reference into the spelling an author reads."""
    parts = raw_path.split(".")
    for size in range(len(parts), 0, -1):
        prefix = ".".join(parts[:size])
        if prefix in surface.PUBLIC_MODULES:
            break
    else:
        raise KeyError(f"{raw_path} names no module typing/surface.py knows")
    public = surface.public_module(prefix)
    rest = parts[size:]
    if not rest:
        if public == current:
            return current.rpartition(".")[2]
        if surface.parent_module(public) == current:
            return public.rpartition(".")[2]
        holders.add(public)
        return public
    member = ".".join([surface.public_name(public, rest[0]), *rest[1:]])
    if public == current:
        return member
    if surface.parent_module(public) == current:
        return public.rpartition(".")[2] + "." + member
    holders.add(public)
    return public + "." + member


def publicize(text: str, current: str, holders: set[str]) -> str:
    return REFERENCE.sub(lambda m: resolve(m.group(0), current, holders), text)


def rebase_children(raw: str, public: str, text: str, holders: set[str]) -> str:
    """Respell a bare submodule reference that no longer sits in this module.

    A generated module names its own submodules bare. When the table sends
    one of them somewhere else, that bare name has to become the path an
    author would write, or disappear where the member landed right here.
    """
    for child in sorted(surface.PUBLIC_MODULES):
        name = child.removeprefix(raw + ".")
        if not child.startswith(raw + ".") or "." in name:
            continue
        target = surface.public_module(child)
        if target == public + "." + name:
            continue
        replacement = "" if target == public else resolve(child, public, holders) + "."
        text = re.sub(rf"(?<![\w.]){name}\.", replacement, text)
    return text


def declared_targets(node: ast.stmt) -> list[ast.Name]:
    """Return the plain names one assignment statement declares."""
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return [node.target]
    if isinstance(node, ast.Assign):
        return [target for target in node.targets if isinstance(target, ast.Name)]
    return []


def declaration_body(raw: str, public: str, text: str, holders: set[str]) -> list[str]:
    """Return one raw module's declarations, spelled the way an author reads."""
    renames = surface.RENAMES.get(public, {})
    statements: list[str] = []
    for node in ast.parse(text).body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if isinstance(node, ast.ImportFrom) and node.level:
                continue
            if "_sigil" in ast.unparse(node) or ast.unparse(node).startswith(
                "from __future__"
            ):
                continue
            statements.append(ast.unparse(node))
            continue
        if isinstance(node, ast.AnnAssign) and ast.unparse(node.target) == "__all__":
            continue
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in renames:
            node.name = renames[node.name]
        # A renamed constant is declared, not defined: only the name an
        # author writes changes, never the value the extension holds.
        for target in declared_targets(node):
            target.id = renames.get(target.id, target.id)
        rebased = rebase_children(raw, public, ast.unparse(node), holders)
        statements.append(
            unshadow(publicize(rebased, public, holders), public, holders)
        )
    return statements


SELF_ALIAS = re.compile(r"^(\s+)(\w+) = \2$", re.MULTILINE)


def unshadow(text: str, public: str, holders: set[str]) -> str:
    """Spell a nested alias to a same-named module member through its module.

    A binding that registers a class both at module level and inside another
    class leaves an alias whose two sides are one word. Read inside the class
    body that word is the alias itself, so the module has to be named.
    """
    if not SELF_ALIAS.search(text):
        return text
    holders.add(public)
    return SELF_ALIAS.sub(rf"\g<1>\g<2> = {public}.\g<2>", text)


def child_import(child: str) -> str:
    name = child.rpartition(".")[2]
    return f"from . import {name} as {name}"


def member_names(raw: str, text: str) -> list[str]:
    """Return the exported members of one raw module, submodules excluded.

    A submodule reaches an author through its own row in the table, so it is
    only carried by its parent when the table puts it there.
    """
    public = surface.public_module(raw)
    exported: list[str] = []
    for node in ast.parse(text).body:
        if isinstance(node, ast.AnnAssign) and ast.unparse(node.target) == "__all__":
            value = node.value
            if not isinstance(value, ast.List):
                continue
            for item in value.elts:
                if not (isinstance(item, ast.Constant) and isinstance(item.value, str)):
                    continue
                name = item.value
                child = raw + "." + name
                if child in surface.PUBLIC_MODULES and (
                    surface.public_module(child) != public + "." + name
                ):
                    continue
                exported.append(name)
    return exported


def public_declarations(raw_texts: dict[str, str]) -> dict[str, str]:
    """Write one declaration file per public module, with nothing raw in it."""
    texts = {raw_module_of(relative): text for relative, text in raw_texts.items()}
    outputs: dict[str, str] = {}
    targets = set(surface.PUBLIC_MODULES.values()) | {surface.PUBLIC_ROOT}
    for public in sorted(targets):
        docstring, addition = split_docstring(read_addition(public, ".pyi"))
        if not docstring:
            # One module, one docstring: the addition that carries the
            # module's hand-written code carries the words describing it,
            # and the declaration says the same thing an import says.
            docstring, _ = split_docstring(read_addition(public, ".py"))
        shadowed = set(top_level_names(addition))
        holders: set[str] = set()
        declared: dict[str, str] = {}
        body: list[str] = []
        for raw in surface.raw_modules(public):
            for statement in declaration_body(raw, public, texts[raw], holders):
                names = top_level_names(statement)
                if any(name in shadowed for name in names):
                    continue
                for name in names:
                    if declared.setdefault(name, raw) != raw:
                        # Two raw modules merged into one public module and
                        # both carry this name. The table cannot decide which
                        # an author means, so the merge is refused. Overloads
                        # within one module are several statements for one
                        # name and stay together.
                        raise RuntimeError(
                            f"{public}.{name} comes from both {declared[name]} "
                            f"and {raw}; one public name, one declaration."
                        )
                body.append(statement)
        children = surface.child_modules(public) if surface.raw_modules(public) else []
        header = ["from __future__ import annotations", STANDARD_IMPORTS.strip()]
        if not any(
            raw in surface.DECLARATION_ONLY for raw in surface.raw_modules(public)
        ):
            header.append("import sigil._types as _t")
        header.extend(child_import(child) for child in children)
        header.extend(f"import {holder}" for holder in sorted(holders))
        text = "\n".join([*header, *body, addition])
        tree = ast.parse(text)
        refinements.prune_imports(
            tree, frozenset(child.rpartition(".")[2] for child in children)
        )
        opening = PUBLIC_HEADER + (docstring.rstrip("\n") + "\n" if docstring else "")
        result = opening + ast.unparse(ast.fix_missing_locations(tree)) + "\n"
        result = result.replace(
            "__hash__: typing.ClassVar[None] = None",
            "__hash__: typing.ClassVar[None] = None  # type: ignore[assignment]",
        )
        result = "\n".join(line.rstrip() for line in result.splitlines()) + "\n"
        ast.parse(result)
        outputs[declaration_file(public)] = result
    return outputs


def declaration_file(public: str) -> str:
    tail = public.removeprefix(surface.PUBLIC_ROOT).lstrip(".")
    parts = tail.split(".") if tail else []
    if surface.child_modules(public):
        return "/".join([*parts, "__init__.pyi"])
    return "/".join(parts[:-1] + [parts[-1] + ".pyi"]) if parts else "__init__.pyi"


# The standard-library roots an addition may reach for. The generated
# modules are lint-checked like every other Python file here, so they are
# written in the grouping and order the import sorter expects.
STANDARD_ROOTS = frozenset(
    {
        "__future__",
        "builtins",
        "collections",
        "functools",
        "importlib",
        "math",
        "numbers",
        "os",
        "pathlib",
        "sys",
        "types",
        "typing",
    }
)


def name_order(name: str) -> tuple[int, str, str]:
    """Order one imported name the way the sorter groups them by kind."""
    if name.isupper():
        kind = 0
    elif name[:1].isupper():
        kind = 1
    else:
        kind = 2
    return (kind, name.lower(), name)


class ImportRecord:
    """One import statement, kept apart so the whole block can be ordered."""

    def __init__(self, level: int, module: str, names: list[tuple[str, str | None]]):
        self.level = level
        self.module = module
        self.names = sorted(names, key=lambda pair: name_order(pair[0]))

    @property
    def section(self) -> int:
        if self.level:
            return 3
        if self.module == "__future__":
            return 0
        return 1 if self.module.split(".")[0] in STANDARD_ROOTS else 2

    @property
    def order(self) -> tuple[int, int, str, tuple[int, str, str]]:
        return (
            self.section,
            -self.level,
            self.module.lower(),
            name_order(self.names[0][0]),
        )

    def render(self) -> str:
        source = "." * self.level + self.module
        if len(self.names) == 1 and self.names[0][1] is not None:
            name, alias = self.names[0]
            return f"from {source} import {name} as {alias}\n"
        entries = "".join(
            f"    {name} as {alias},\n" if alias else f"    {name},\n"
            for name, alias in self.names
        )
        return f"from {source} import (\n{entries})\n"


def plain_import(statement: ast.Import) -> str:
    return ast.unparse(statement) + "\n"


def split_imports(text: str) -> tuple[list[ImportRecord], list[str], str]:
    """Split one addition's leading imports from the rest of its source."""
    records: list[ImportRecord] = []
    plain: list[str] = []
    if not text.strip():
        return records, plain, ""
    tree = ast.parse(text)
    lines = text.splitlines(keepends=True)
    consumed = 0
    for node in tree.body:
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            consumed = node.end_lineno or consumed
            continue
        if isinstance(node, ast.Import):
            plain.append(plain_import(node))
        elif isinstance(node, ast.ImportFrom):
            records.append(
                ImportRecord(
                    node.level,
                    node.module or "",
                    [(alias.name, alias.asname) for alias in node.names],
                )
            )
        else:
            break
        consumed = node.end_lineno or consumed
    return records, plain, "".join(lines[consumed:]).lstrip("\n")


def public_runtime(raw_texts: dict[str, str]) -> dict[str, str]:
    """Write the module an author imports: one re-export plus its additions."""
    outputs: dict[str, str] = {}
    texts = {raw_module_of(relative): text for relative, text in raw_texts.items()}
    for public in sorted(set(surface.PUBLIC_MODULES.values())):
        contributors = surface.raw_modules(public)
        if not contributors:
            continue
        if any(raw in surface.DECLARATION_ONLY for raw in contributors):
            continue
        addition = read_addition(public, ".py")
        docstring, _ = split_docstring(addition)
        records, plain, extra = split_imports(addition)
        shadowed = set(top_level_names(addition))
        exported: set[str] = set()
        children: list[str] = []
        for raw in contributors:
            pairs: list[tuple[str, str | None]] = []
            for name in member_names(raw, texts[raw]):
                spelling = surface.public_name(public, name)
                if spelling in exported or spelling in shadowed:
                    exported.add(spelling)
                    continue
                child = raw + "." + name
                if child in surface.PUBLIC_MODULES:
                    # A submodule is a module of the package in its own
                    # right, so the parent reaches it the way an author
                    # does rather than handing the extension's over.
                    children.append(name)
                    exported.add(name)
                    continue
                pairs.append((name, spelling if spelling != name else None))
                exported.add(spelling)
            renamed = [pair for pair in pairs if pair[1] is not None]
            kept = [pair for pair in pairs if pair[1] is None]
            if kept:
                records.append(ImportRecord(0, raw, kept))
            records.extend(ImportRecord(0, raw, [pair]) for pair in renamed)
        if children:
            records.append(
                ImportRecord(1, "", [(name, None) for name in sorted(children)])
            )
        exported.update(name for name in shadowed if not name.startswith("_"))
        grouped: dict[int, list[str]] = {}
        for statement in plain:
            grouped.setdefault(1, []).append(statement)
        for record in records:
            grouped.setdefault(record.section, []).append(record.render())
        imports = "\n".join(
            "".join(sorted(statements, key=section_order))
            for _, statements in sorted(grouped.items())
        ).rstrip("\n")
        head = [PUBLIC_HEADER.rstrip("\n")]
        if docstring:
            head.append(docstring.rstrip("\n"))
        head.append(imports)
        tail: list[str] = []
        if extra.strip():
            tail.append(extra.rstrip("\n"))
        tail.append(
            "__all__ = [\n"
            + "".join(f'    "{name}",\n' for name in sorted(exported, key=export_order))
            + "]"
        )
        # The import sorter wants one blank line after the imports, and the
        # formatter wants two before a definition; they overlap here.
        opening = "\n\n\n" if tail[0].startswith(("def ", "class ", "@")) else "\n\n"
        body = "\n\n".join(head) + opening + "\n\n\n".join(tail) + "\n"
        ast.parse(body)
        outputs[runtime_file(public)] = body
    return outputs


def export_order(name: str) -> tuple[int, str]:
    """Order one exported name the way the sorted-__all__ rule expects."""
    return (name_order(name)[0], name)


def section_order(statement: str) -> tuple[int, int, str, tuple[int, str, str]]:
    """Order one rendered import statement within its section."""
    node = ast.parse(statement).body[0]
    if isinstance(node, ast.Import):
        return (0, 0, node.names[0].name.lower(), name_order(node.names[0].name))
    assert isinstance(node, ast.ImportFrom)
    return (
        1,
        -node.level,
        (node.module or "").lower(),
        name_order(node.names[0].name),
    )


def runtime_file(public: str) -> str:
    tail = public.removeprefix(surface.PUBLIC_ROOT).lstrip(".")
    parts = tail.split(".")
    if surface.child_modules(public):
        return "/".join([*parts, "__init__.py"])
    return "/".join(parts[:-1] + [parts[-1] + ".py"])


def existing(
    root: pathlib.Path, suffixes: tuple[str, ...], owned: bool
) -> dict[str, str]:
    """Read the files already on disk that this pass is responsible for."""
    found: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix not in suffixes:
            continue
        text = path.read_text()
        if owned and not text.startswith(PUBLIC_HEADER.splitlines()[0]):
            continue
        found[str(path.relative_to(root))] = text
    return found


def report(old: dict[str, str], new: dict[str, str], label: str) -> bool:
    for name in sorted(old.keys() | new.keys()):
        if old.get(name) != new.get(name):
            print(
                "".join(
                    difflib.unified_diff(
                        old.get(name, "").splitlines(keepends=True),
                        new.get(name, "").splitlines(keepends=True),
                        fromfile=f"checked-in/{label}/{name}",
                        tofile=f"generated/{label}/{name}",
                    )
                ),
                end="",
            )
    return old != new


def write(root: pathlib.Path, old: dict[str, str], new: dict[str, str]) -> None:
    for name in old.keys() - new.keys():
        (root / name).unlink()
    for name, text in new.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def write_declarations(root: pathlib.Path, files: dict[str, str]) -> None:
    """Lay one declaration tree down as a package a type checker will read."""
    write(root, existing(root, (".pyi",), owned=False), files)
    marker = root / "py.typed"
    if not marker.is_file():
        marker.write_text("")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--declarations",
        type=pathlib.Path,
        help="write the declarations an author's editor reads into this "
        "package directory instead of refreshing the package's modules",
    )
    parser.add_argument(
        "--raw",
        type=pathlib.Path,
        help="write the extension's own declarations, which nothing installs, "
        "into this package directory",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report the package modules this extension no longer agrees with",
    )
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="sigil-declarations-") as directory:
        raw = generate_raw(pathlib.Path(directory))
    runtime = public_runtime(raw)
    if args.raw:
        write_declarations(args.raw, raw)
        print(f"Wrote {len(raw)} extension declaration modules to {args.raw}.")
    if args.declarations:
        public = public_declarations(raw)
        write_declarations(args.declarations, public)
        print(f"Wrote {len(public)} declaration modules to {args.declarations}.")
    if args.check:
        return int(report(existing(PACKAGE, (".py",), owned=True), runtime, "sigil"))
    if args.declarations or args.raw:
        return 0
    write(PACKAGE, existing(PACKAGE, (".py",), owned=True), runtime)
    print(f"Refreshed {len(runtime)} package modules under {PACKAGE}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
