"""Generate the native stubs from a matching, already-built extension.

Run with the development interpreter and PYTHONPATH pointing to build/python.
The generator never builds or imports user sketches. Explicit refinements
describe conversion seams that pybind11's runtime docstrings erase.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib.metadata
import keyword
import os
import pathlib
import re
import subprocess
import sys
import tempfile

import refinements

HERE = pathlib.Path(__file__).resolve().parent
DESTINATION = HERE.parent / "stubs" / "_sigil"


def module_name(path: pathlib.Path) -> str:
    parts = list(path.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(["_sigil", *parts])


def sanitize(text: str) -> str:
    # Python keywords cannot be used in attribute syntax. A binding that
    # exposes an escaped alias remains represented by that usable alias.
    for name in keyword.kwlist:
        text = re.sub(rf"\bdef {name}\(", f"def __keyword_{name}(", text)
        text = re.sub(rf"@{name}\.setter", f"@__keyword_{name}.setter", text)
    return text


def extension_under_pythonpath() -> None:
    """Refuse an extension PYTHONPATH did not name.

    The stubs describe whichever `_sigil` this interpreter imports, and an
    installed package — an editable one especially — is found ahead of
    PYTHONPATH. An interpreter that has one therefore writes declarations
    for a binding that is not the one in the build tree, quietly, and a
    class the current bindings no longer register comes back.
    """
    import _sigil

    roots = [
        pathlib.Path(entry).resolve()
        for entry in os.environ.get("PYTHONPATH", "").split(os.pathsep)
        if entry
    ]
    if not roots:
        return
    found = pathlib.Path(_sigil.__file__).resolve()
    if any(found.is_relative_to(root) for root in roots):
        return
    named = ", ".join(str(root) for root in roots)
    raise RuntimeError(
        f"PYTHONPATH names {named}, but _sigil was imported from {found}. "
        "An installed copy shadows the built one. Run this with an "
        "interpreter that has no sigil package installed."
    )


def generate(destination: pathlib.Path) -> dict[str, str]:
    version = importlib.metadata.version("pybind11-stubgen")
    if version != "2.5.5":
        raise RuntimeError(f"Use pybind11-stubgen 2.5.5, found {version}")
    extension_under_pythonpath()
    subprocess.run(
        [
            sys.executable,
            "-m",
            "pybind11_stubgen",
            "_sigil",
            "-o",
            str(destination),
            "--ignore-all-errors",
        ],
        check=True,
    )
    outputs: dict[str, str] = {}
    refinements.SEEN.clear()
    for path in sorted((destination / "_sigil").rglob("*.pyi")):
        relative = path.relative_to(destination / "_sigil")
        tree = ast.parse(sanitize(path.read_text()))
        refinements.refine(module_name(relative), tree)
        result = (
            "# Generated by typing/generate.py; edit its refinements, not this file.\n"
            + ast.unparse(ast.fix_missing_locations(tree))
            + "\n"
        )
        # Native unhashability is represented exactly; Python's object stub
        # declares __hash__ as a method, requiring a targeted mypy exception.
        result = result.replace(
            "__hash__: typing.ClassVar[None] = None",
            "__hash__: typing.ClassVar[None] = None  # type: ignore[assignment]",
        )
        result = "\n".join(line.rstrip() for line in result.splitlines()) + "\n"
        ast.parse(result)
        outputs[str(relative)] = result
    refinements.validate()
    outputs["_types.pyi"] = (HERE / "_types.pyi").read_text()
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Reject generated-stub drift"
    )
    parser.add_argument("--output", type=pathlib.Path, default=DESTINATION)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="sigil-stubs-") as directory:
        outputs = generate(pathlib.Path(directory))
    old = {
        str(p.relative_to(args.output)): p.read_text()
        for p in args.output.rglob("*.pyi")
    }
    if args.check:
        for name in sorted(old.keys() | outputs.keys()):
            if old.get(name) != outputs.get(name):
                print(
                    "".join(
                        difflib.unified_diff(
                            old.get(name, "").splitlines(keepends=True),
                            outputs.get(name, "").splitlines(keepends=True),
                            fromfile=f"checked-in/{name}",
                            tofile=f"generated/{name}",
                        )
                    ),
                    end="",
                )
        return int(old != outputs)
    for name in old.keys() - outputs.keys():
        (args.output / name).unlink()
    for name, text in outputs.items():
        path = args.output / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(f"Generated {len(outputs)} native stub modules in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
