"""Generate PARITY.md, the Python ledger, from the built extension.

Run with the interpreter that matches the extension and PYTHONPATH pointing
to build/python, like generate.py. Three sources meet here and nothing else
is read:

- the extension, imported through the package's own modules in this
  checkout: whether a surface is bound is whether its Python spellings
  resolve there, and which public modules export nothing yet comes from
  walking typing/surface.py's table;
- the sketch registrations under src/sketch/sketches: which C++ sketches
  exist, the collection each files under, and which Python studies ship;
- typing/ledger: what each sketch needs, which Python spellings stand for
  each native surface, what each study combines, and what each library
  row claims.

Everything else in PARITY.md is prose an author wrote. It sits between
`<!-- prose: NAME -->` and `<!-- /prose -->` markers, and this pass carries
it over verbatim from the file already on disk. A prose block holds no
table: every table in the ledger is generated, so a row written by hand
inside a block stops the pass rather than riding along unjudged.

`--check` writes nothing and exits non-zero at the first line the checked-in
ledger does not agree with.

The ledger describes an extension built with every licensed SDK. One built
without them cannot judge it, so this exits with SKIPPED, which the drift
test reports as skipped and the `generate` target as a failure: in neither
mode is PARITY.md read or written.
"""

from __future__ import annotations

import argparse
import dataclasses
import difflib
import importlib
import pathlib
import re
import sys
from collections.abc import Iterable

import surface
import tomllib

HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent
LEDGER = HERE / "ledger"
TARGET = PROJECT / "PARITY.md"
SKETCHES = PROJECT.parents[1] / "spell-circle-canvas" / "src" / "sketch" / "sketches"
# How a study row links to its source from PARITY.md.
STUDY_LINK = "../../spell-circle-canvas/src/sketch/sketches"

HEADER = (
    "<!-- Generated by typing/parity.py from the built extension, the sketch\n"
    "registrations and typing/ledger. Edit those, or the prose between the\n"
    "markers; typing/parity.py --check fails on any other edit. -->"
)
# The prose blocks the ledger carries, in the order they appear.
PROSE = (
    "introduction",
    "status",
    "hosting",
    "composition",
    "typography",
    "motion",
    "drawing",
    "material-geometry-world",
    "data-io",
    "unbound-libraries",
    "studies",
    "studies-after",
    "translating",
    "verification",
)
PROSE_OPEN = re.compile(r"^<!-- prose: ([a-z-]+) -->$")
PROSE_CLOSE = "<!-- /prose -->"
# A surface needed by at least this many sketches is listed under Status.
WIDELY_NEEDED = 8
# The exit status for an extension that cannot judge the ledger; the drift
# test names it as its skip status.
SKIPPED = 77


class LedgerError(Exception):
    """The ledger's data disagrees with the tree or the extension."""


# ---------------------------------------------------------------------------
# The extension


class Extension:
    """Answers whether a Python spelling resolves in the built extension."""

    def __init__(self) -> None:
        self._known: dict[str, bool] = {}

    def resolves(self, spelling: str) -> bool:
        if spelling not in self._known:
            self._known[spelling] = self._resolve(spelling)
        return self._known[spelling]

    def all_resolve(self, spellings: Iterable[str]) -> bool:
        return all(self.resolves(spelling) for spelling in spellings)

    def _resolve(self, spelling: str) -> bool:
        match = re.fullmatch(r"([\w.]+)(?:\((.*)\))?", spelling)
        if not match:
            raise LedgerError(f"`{spelling}` is not a dotted Python spelling")
        found = self._lookup(f"{surface.PUBLIC_ROOT}.{match.group(1)}")
        if found is None:
            return False
        if match.group(2) is None:
            return True
        wanted = [name.strip() for name in match.group(2).split(",") if name.strip()]
        return any(
            parameters[: len(wanted)] == wanted
            for parameters in overload_parameters(found)
        )

    @staticmethod
    def _lookup(dotted: str) -> object | None:
        parts = dotted.split(".")
        for size in range(len(parts), 0, -1):
            try:
                found: object = importlib.import_module(".".join(parts[:size]))
            except ImportError:
                continue
            for part in parts[size:]:
                found = getattr(found, part, None)
                if found is None:
                    return None
            return found
        return None

    def silent_modules(self) -> list[str]:
        """The public modules with no children that export no name yet."""
        silent = []
        for public in sorted(set(surface.PUBLIC_MODULES.values())):
            raws = surface.raw_modules(public)
            if (
                surface.child_modules(public)
                or any(raw in surface.DECLARATION_ONLY for raw in raws)
                or any(raw in surface.OPTIONAL_MODULES for raw in raws)
            ):
                continue
            module = importlib.import_module(public)
            if not list(getattr(module, "__all__", [])):
                silent.append(public)
        return silent


def overload_parameters(value: object) -> list[list[str]]:
    """The parameter names of each signature a bound callable documents."""
    signatures = []
    for line in (getattr(value, "__doc__", None) or "").splitlines():
        match = re.match(r"^\s*(?:\d+\.\s*)?\w+\((.*)\)\s*->", line)
        if not match:
            continue
        names = []
        depth = 0
        current = ""
        for character in match.group(1) + ",":
            if character in "[(":
                depth += 1
            elif character in "])":
                depth -= 1
            if character == "," and depth == 0:
                name = current.split(":")[0].split("=")[0].strip().lstrip("*")
                if name and name != "self":
                    names.append(name)
                current = ""
            else:
                current += character
        signatures.append(names)
    return signatures


def absent_optional_modules() -> list[str]:
    """The licensed-SDK modules this extension was built without."""
    absent = []
    for raw in sorted(surface.OPTIONAL_MODULES):
        try:
            importlib.import_module(raw)
        except ModuleNotFoundError:
            absent.append(raw)
    return absent


# ---------------------------------------------------------------------------
# The sketch tree

REGISTRATION = re.compile(r"\bSIGIL_SKETCH(_AS)?\s*\(")
LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')


@dataclasses.dataclass(frozen=True)
class Registration:
    name: str
    collection: str


def macro_arguments(text: str, start: int) -> list[str]:
    """Split one macro call's arguments at its top-level commas."""
    arguments: list[str] = []
    current = ""
    depth = 0
    quoted = False
    index = start
    while index < len(text):
        character = text[index]
        current += character
        if quoted:
            if character == "\\":
                current += text[index + 1]
                index += 1
            elif character == '"':
                quoted = False
        elif character == '"':
            quoted = True
        elif character == "(":
            depth += 1
        elif character == ")":
            if depth == 0:
                arguments.append(current[:-1].strip())
                return arguments
            depth -= 1
        elif character == "," and depth == 0:
            arguments.append(current[:-1].strip())
            current = ""
        index += 1
    raise LedgerError("a sketch registration never closes its parentheses")


def literal(argument: str) -> str | None:
    """The string an argument of adjacent literals spells, or None for nullptr."""
    if argument == "nullptr":
        return None
    return "".join(LITERAL.findall(argument))


def registrations(root: pathlib.Path) -> dict[str, Registration]:
    """Every C++ sketch the directory registers, by the name it files under.

    A sketch files under its own name when SIGIL_SKETCH_AS gives one and
    under its stem otherwise: the file's, or its directory's when the
    sketch is a directory.
    """
    found: dict[str, Registration] = {}
    for path in sorted(root.rglob("*")):
        if path.suffix not in {".cpp", ".mm", ".h"}:
            continue
        # A hidden directory is a tool's, an interpreter environment above all.
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        text = path.read_text(errors="replace")
        for match in REGISTRATION.finditer(text):
            opening = text.rfind("\n", 0, match.start()) + 1
            if text[opening : match.start()].strip().startswith(("//", "*", "#")):
                continue
            arguments = macro_arguments(text, match.end())
            relative = path.relative_to(root)
            stem = relative.parts[0] if len(relative.parts) > 1 else path.stem
            if match.group(1):
                name = literal(arguments[1]) or stem
                collection = literal(arguments[2]) or ""
            else:
                name, collection = stem, literal(arguments[1]) or ""
            found[name] = Registration(name, collection)
    return found


def studies(root: pathlib.Path) -> list[str]:
    return sorted(path.stem for path in root.glob("python_*.py"))


# ---------------------------------------------------------------------------
# The ledger data


def load(name: str) -> dict:
    with (LEDGER / name).open("rb") as handle:
        return tomllib.load(handle)


@dataclasses.dataclass
class Requirement:
    key: str
    native: str
    library: str
    python: list[str]
    bound: bool
    # Why no Python name can stand for this surface, when none can.
    no_python_spelling: str | None = None


@dataclasses.dataclass
class Sketch:
    name: str
    collection: str
    needs: str | None
    requires: list[Requirement]
    study: tuple[str, str] | None = None  # (relation, study stem)

    @property
    def unbound(self) -> list[Requirement]:
        return [requirement for requirement in self.requires if not requirement.bound]

    @property
    def bound(self) -> bool:
        return self.needs is not None and not self.unbound


@dataclasses.dataclass
class Study:
    stem: str
    combines: str | None
    relation: str | None
    native: str | None


class Ledger:
    """The ledger's data joined to the tree and judged against the extension."""

    def __init__(self, extension: Extension, sketch_root: pathlib.Path) -> None:
        self.extension = extension
        self.requirements = self._requirements(load("requirements.toml"))
        sketch_data = load("sketches.toml")
        registered = registrations(sketch_root)
        self.collections = self._collection_order(sketch_data, registered)
        self.studies = self._studies(
            load("studies.toml"), studies(sketch_root), registered
        )
        self.sketches = self._sketches(sketch_data, registered)
        self.coverage = load("coverage.toml")

    def _requirements(self, data: dict) -> dict[str, Requirement]:
        found = {}
        for key, record in data.get("requirement", {}).items():
            python = list(record.get("python", []))
            reason = record.get("no_python_spelling")
            if bool(python) == bool(reason):
                raise LedgerError(
                    f"typing/ledger/requirements.toml: `{key}` must give either "
                    "the Python spellings that stand for it in `python`, or why "
                    "none can in `no_python_spelling`, and not both"
                )
            bound = bool(python) and self.extension.all_resolve(python)
            found[key] = Requirement(
                key, record["native"], record["library"], python, bound, reason
            )
        return found

    @staticmethod
    def _collection_order(data: dict, registered: dict[str, Registration]) -> list[str]:
        order = list(data.get("collections", []))
        rest = sorted({entry.collection for entry in registered.values()} - set(order))
        present = {entry.collection for entry in registered.values()}
        return [collection for collection in order + rest if collection in present]

    @staticmethod
    def _studies(
        data: dict, stems: list[str], registered: dict[str, Registration]
    ) -> list[Study]:
        records = data.get("study", {})
        for stem in records:
            if stem not in stems:
                raise LedgerError(
                    f"typing/ledger/studies.toml describes {stem}, and no "
                    f"{stem}.py ships under src/sketch/sketches"
                )
        found = []
        for stem in stems:
            record = records.get(stem, {})
            relation = native = None
            if "ports" in record:
                relation, native = "Port", record["ports"]
            elif "adapts" in record:
                relation, native = "Adaptation", record["adapts"]
            if native is not None and native not in registered:
                raise LedgerError(
                    f"{stem} names {native}, which no C++ sketch registers"
                )
            found.append(Study(stem, record.get("combines"), relation, native))
        return found

    def _sketches(
        self, data: dict, registered: dict[str, Registration]
    ) -> list[Sketch]:
        records = data.get("sketch", {})
        for name in records:
            if name not in registered:
                raise LedgerError(
                    f"typing/ledger/sketches.toml describes `{name}`, which no "
                    "C++ sketch registers"
                )
        by_native = {study.native: study for study in self.studies if study.native}
        found = []
        for name, entry in registered.items():
            record = records.get(name)
            requires = []
            for key in record.get("requires", []) if record else []:
                if key not in self.requirements:
                    raise LedgerError(
                        f"`{name}` requires `{key}`, which typing/ledger/"
                        "requirements.toml does not record"
                    )
                requires.append(self.requirements[key])
            study = by_native.get(name)
            found.append(
                Sketch(
                    name,
                    entry.collection,
                    record["needs"] if record else None,
                    requires,
                    (study.relation, study.stem) if study and study.relation else None,
                )
            )
        return sorted(found, key=lambda sketch: sketch.name.casefold())

    def in_collection(self, collection: str) -> list[Sketch]:
        return [sketch for sketch in self.sketches if sketch.collection == collection]


# ---------------------------------------------------------------------------
# Rendering


def cell(text: str) -> str:
    """Text a table cell can hold: an unescaped pipe would end the cell."""
    return re.sub(r"(?<!\\)\|", r"\\|", text)


def row(*cells: str) -> str:
    return "| " + " | ".join(cell(text) for text in cells) + " |"


def listing(names: list[str]) -> str:
    """`a`, `a and b`, `a, b and c`."""
    if len(names) <= 1:
        return "".join(names)
    return ", ".join(names[:-1]) + " and " + names[-1]


NUMBERS = (
    "no",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
)


def number(count: int, capital: bool = False) -> str:
    """A count as prose writes it: words up to twelve, digits above."""
    word = NUMBERS[count] if count < len(NUMBERS) else str(count)
    return word[:1].upper() + word[1:] if capital else word


def spelled(python: list[str]) -> str:
    return listing([f"`{name}`" for name in python])


def wrap(text: str, width: int = 79, hanging: str = "") -> list[str]:
    """Break one generated paragraph the way the prose around it breaks.

    Every line after the first opens with @p hanging, which is how a list
    item's continuation stays inside the item.
    """
    lines: list[str] = []
    current = ""
    for word in text.split(" "):
        if current.strip() and len(current) + 1 + len(word) > width:
            lines.append(current)
            current = hanging + word
        else:
            current = f"{current} {word}" if current.strip() else current + word
    lines.append(current)
    return lines


class Writer:
    def __init__(self, ledger: Ledger, prose: dict[str, str]) -> None:
        self.ledger = ledger
        self.prose = prose
        self.lines: list[str] = []

    def emit(self, *lines: str) -> None:
        self.lines.extend(lines)

    def paragraph(self, text: str) -> None:
        self.emit(*wrap(text), "")

    def block(self, name: str) -> None:
        self.emit(f"<!-- prose: {name} -->")
        text = self.prose.get(name, "")
        if text:
            self.emit(*text.split("\n"))
        self.emit(PROSE_CLOSE, "")

    def document(self) -> str:
        self.emit(HEADER, "", "# Python authoring coverage", "")
        self.block("introduction")
        self.status()
        self.library_coverage()
        self.python_studies()
        self.catalog_audit()
        self.emit("## Translating a C++ source", "")
        self.block("translating")
        self.emit("## Verification", "")
        self.block("verification")
        while self.lines and self.lines[-1] == "":
            self.lines.pop()
        return "\n".join(self.lines) + "\n"

    # -- Status ------------------------------------------------------------

    def status(self) -> None:
        ledger = self.ledger
        self.emit("## Status", "")
        self.paragraph(
            "A sketch counts as bound when every requirement the catalog audit "
            "records for it resolves to its Python spelling in the built "
            "extension. A sketch nobody has audited counts as unbound. The "
            "Python study column counts the bundled studies that port or adapt "
            "a sketch in that collection."
        )
        self.block("status")
        self.emit(
            "| Collection | Sketches | Every requirement bound | Python study |",
            "| --- | ---: | ---: | ---: |",
        )
        totals = [0, 0, 0]
        complete = []
        for collection in ledger.collections:
            sketches = ledger.in_collection(collection)
            counts = [
                len(sketches),
                sum(sketch.bound for sketch in sketches),
                sum(sketch.study is not None for sketch in sketches),
            ]
            totals = [total + count for total, count in zip(totals, counts)]
            if counts[0] == counts[1]:
                complete.append(collection)
            self.emit(row(collection, *(str(count) for count in counts)))
        self.emit(row("**All**", *(f"**{total}**" for total in totals)), "")
        if complete:
            self.paragraph(f"Every sketch in {listing(complete)} is bound.")
        self.one_surface_away()
        self.widely_needed()
        self.unjudged()

    def one_surface_away(self) -> None:
        waiting: dict[str, list[str]] = {}
        natives: dict[str, str] = {}
        for sketch in self.ledger.sketches:
            if sketch.needs is not None and len(sketch.unbound) == 1:
                requirement = sketch.unbound[0]
                waiting.setdefault(requirement.key, []).append(f"`{sketch.name}`")
                natives[requirement.key] = requirement.native
        if not waiting:
            return
        self.paragraph(
            "One surface alone stands between each of these sketches and a translation:"
        )
        for key in sorted(waiting, key=lambda key: (-len(waiting[key]), natives[key])):
            self.emit(
                *wrap(f"- {natives[key]}: {listing(waiting[key])}.", hanging="  ")
            )
        self.emit("")

    def widely_needed(self) -> None:
        counts: dict[str, int] = {}
        for sketch in self.ledger.sketches:
            for requirement in sketch.unbound:
                counts[requirement.key] = counts.get(requirement.key, 0) + 1
        wide = [key for key, count in counts.items() if count >= WIDELY_NEEDED]
        if not wide:
            return
        requirements = self.ledger.requirements
        self.paragraph(
            "These surfaces stand between the most sketches and a translation. "
            f"Each is needed by {number(WIDELY_NEEDED)} or more; the catalog audit names "
            "every surface each sketch needs."
        )
        self.emit("| Not yet bound | Library | Sketches |", "| --- | --- | ---: |")
        for key in sorted(
            wide, key=lambda key: (-counts[key], requirements[key].native)
        ):
            requirement = requirements[key]
            self.emit(row(requirement.native, requirement.library, str(counts[key])))
        self.emit("")

    def unjudged(self) -> None:
        requirements = [
            requirement
            for requirement in self.ledger.requirements.values()
            if requirement.no_python_spelling
        ]
        if not requirements:
            return
        self.paragraph(
            "No Python name can stand for these surfaces, so the extension cannot "
            "judge them and every sketch that needs one counts as unbound. Each is "
            "a claim the audit makes, with its reason:"
        )
        for requirement in sorted(requirements, key=lambda item: item.native):
            needing = sum(
                any(item.key == requirement.key for item in sketch.requires)
                for sketch in self.ledger.sketches
            )
            self.emit(
                *wrap(
                    f"- {requirement.native}, needed by {number(needing)} "
                    f"{'sketch' if needing == 1 else 'sketches'}. "
                    f"{requirement.no_python_spelling}.",
                    hanging="  ",
                )
            )
        self.emit("")

    # -- Library coverage --------------------------------------------------

    def library_coverage(self) -> None:
        extension = self.ledger.extension
        self.emit("## Library coverage", "")
        self.paragraph(
            "Each row states what a Python author can reach today and what the "
            "native library has that Python cannot yet reach. Names under Bound "
            "are spelled as Python reaches them, and each resolves in the built "
            "extension; names under Not yet bound are native C++ spellings."
        )
        silent = extension.silent_modules()
        if silent:
            self.paragraph(
                "These public modules are registered and export nothing yet: "
                + listing([f"`{module}`" for module in silent])
                + "."
            )
        for section in self.ledger.coverage.get("section", []):
            self.emit(f"### {section['title']}", "")
            self.emit("| Surface | Bound | Not yet bound |", "| --- | --- | --- |")
            for entry in section.get("surface", []):
                bound, unbound = self.split(entry)
                self.emit(
                    row(
                        entry["name"],
                        "; ".join(bound) or "Nothing",
                        "; ".join(unbound) or "Nothing",
                    )
                )
            self.emit("")
            self.block(section["prose"])
        self.unbound_libraries()

    def split(self, entry: dict) -> tuple[list[str], list[str]]:
        extension = self.ledger.extension
        bound: list[str] = []
        unbound: list[str] = []
        for item in entry.get("item", []):
            python = list(item.get("python", []))
            if "bound" in item:
                missing = [name for name in python if not extension.resolves(name)]
                if missing:
                    raise LedgerError(
                        f"The {entry['name']} row claims {item['bound']!r} is bound, "
                        f"and the extension has no {spelled(missing)}. Correct "
                        "the item in typing/ledger/coverage.toml."
                    )
                bound.append(item["bound"])
            elif python and extension.all_resolve(python):
                bound.append(item.get("bound_text") or spelled(python))
            else:
                unbound.append(item["native"])
        return bound, unbound

    def unbound_libraries(self) -> None:
        extension = self.ledger.extension
        rows = []
        for label, record in self.ledger.coverage.get("library", {}).items():
            modules = [
                f"{surface.PUBLIC_ROOT}.{module}" for module in record["modules"]
            ]
            if any(
                getattr(importlib.import_module(module), "__all__", [])
                for module in modules
                if extension.resolves(module.removeprefix(surface.PUBLIC_ROOT + "."))
            ):
                continue
            needed = [
                requirement
                for requirement in self.ledger.requirements.values()
                if requirement.library == label
            ]
            names = {requirement.key for requirement in needed}
            sketches = [
                f"`{sketch.name}`"
                for sketch in self.ledger.sketches
                if any(requirement.key in names for requirement in sketch.requires)
            ]
            surfaces = "; ".join(sorted(requirement.native for requirement in needed))
            rows.append(
                row(record["native"], surfaces or "—", ", ".join(sketches) or "—")
            )
        if not rows:
            return
        self.emit("### Libraries without bindings", "")
        self.paragraph("No Python module exports anything from these libraries.")
        self.block("unbound-libraries")
        self.emit("| Library | Native surface the catalog uses | Sketches |")
        self.emit("| --- | --- | --- |", *rows, "")

    # -- Studies -----------------------------------------------------------

    def python_studies(self) -> None:
        studies = self.ledger.studies
        ports = sum(study.relation == "Port" for study in studies)
        adapts = sum(study.relation == "Adaptation" for study in studies)
        self.emit("## Python studies", "")
        self.paragraph(
            f"The {number(len(studies))} bundled Python sketches are authoring studies. "
            f"{number(ports, capital=True)} port a native sketch, {number(adapts)} adapt one, "
            "and the rest "
            "exercise the Python surface without a native counterpart."
        )
        self.block("studies")
        self.emit("| Study | What it combines | Native sketch |", "| --- | --- | --- |")
        for study in studies:
            native = "—"
            if study.relation:
                verb = "Ports" if study.relation == "Port" else "Adapts"
                native = f"{verb} `{study.native}`"
            self.emit(
                row(f"`{study.stem}`", study.combines or "Not yet described", native)
            )
        self.emit("")
        self.block("studies-after")

    # -- Catalog audit -----------------------------------------------------

    def catalog_audit(self) -> None:
        self.emit("## Catalog audit", "")
        self.paragraph(
            "Every registered C++ sketch appears once, under its collection. "
            "**Needs** summarizes the native capabilities its source uses beyond "
            "basic pen verbs. **Not yet bound** names each native surface a "
            "translation still needs, in native spelling; a dash means every "
            "requirement is bound. The sketch's own model, arithmetic and data "
            "become Python code and are not listed."
        )
        groups: dict[str, list[str]] = {}
        for collection in self.ledger.collections:
            groups.setdefault(collection.split(" · ")[0], []).append(collection)
        for group, collections in groups.items():
            nested = len(collections) > 1
            if nested:
                self.emit(f"### {group}", "")
            for collection in collections:
                self.emit(f"{'####' if nested else '###'} {collection}", "")
                self.audit_table(self.ledger.in_collection(collection))

    def audit_table(self, sketches: list[Sketch]) -> None:
        with_study = any(sketch.study for sketch in sketches)
        header = ["Sketch", "Needs", "Not yet bound"] + (
            ["Python study"] if with_study else []
        )
        self.emit("| " + " | ".join(header) + " |", "|" + " --- |" * len(header))
        for sketch in sketches:
            unbound = "; ".join(requirement.native for requirement in sketch.unbound)
            cells = [
                f"`{sketch.name}`",
                sketch.needs if sketch.needs is not None else "Not yet audited",
                (unbound or "—") if sketch.needs is not None else "Not yet audited",
            ]
            if with_study:
                cells.append(self.study_cell(sketch))
            self.emit(row(*cells))
        self.emit("")

    @staticmethod
    def study_cell(sketch: Sketch) -> str:
        if not sketch.study:
            return ""
        relation, stem = sketch.study
        return f"{relation}: [`{stem}.py`]({STUDY_LINK}/{stem}.py)"


# ---------------------------------------------------------------------------
# The file on disk


def read_prose(text: str) -> dict[str, str]:
    """The prose blocks an author wrote, by name, exactly as written."""
    blocks: dict[str, str] = {}
    name: str | None = None
    body: list[str] = []
    for number, line in enumerate(text.splitlines(), start=1):
        opening = PROSE_OPEN.match(line)
        if opening:
            if name is not None:
                raise LedgerError(
                    f"PARITY.md:{number}: a prose block opens inside {name}"
                )
            name, body = opening.group(1), []
        elif line == PROSE_CLOSE:
            if name is None:
                raise LedgerError(
                    f"PARITY.md:{number}: a prose block closes that never opened"
                )
            if name not in PROSE:
                raise LedgerError(
                    f"PARITY.md:{number}: the prose block `{name}` has no place in "
                    f"the ledger; its places are {', '.join(PROSE)}"
                )
            blocks[name] = "\n".join(body)
            name = None
        elif name is not None:
            if line.lstrip().startswith("|"):
                raise LedgerError(
                    f"PARITY.md:{number}: the prose block `{name}` holds a table "
                    "row; the ledger's tables are generated, so state the fact "
                    "in typing/ledger instead"
                )
            body.append(line)
    if name is not None:
        raise LedgerError(f"PARITY.md: the prose block {name} never closes")
    return blocks


def first_difference(old: str, new: str) -> str:
    old_lines = old.splitlines()
    new_lines = new.splitlines()
    for number, (was, wants) in enumerate(zip(old_lines, new_lines), start=1):
        if was != wants:
            return (
                f"PARITY.md:{number} disagrees with the extension and typing/ledger.\n"
                f"  checked in: {was}\n  generated:  {wants}"
            )
    number = min(len(old_lines), len(new_lines)) + 1
    return f"PARITY.md:{number}: the checked-in ledger and the generated one differ in length."


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit non-zero at the first line PARITY.md disagrees on",
    )
    parser.add_argument(
        "--sketches",
        type=pathlib.Path,
        default=SKETCHES,
        help="the directory the C++ sketches and Python studies are registered in",
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="with --check, print the whole difference rather than its first line",
    )
    args = parser.parse_args()

    from generate import extension_under_pythonpath

    extension_under_pythonpath()
    # The package's own modules as the checkout holds them, over the
    # extension PYTHONPATH names: the modules generate.py has just
    # refreshed, not the copy a build staged beside the extension.
    sys.path.insert(0, str(PROJECT))
    absent = absent_optional_modules()
    if absent:
        # The ledger describes a build with every optional SDK, so one
        # without them cannot say what it should read.
        print(
            "typing/parity.py: SKIPPED: this extension was built without "
            f"{', '.join(absent)}, so it cannot judge PARITY.md, and "
            + ("nothing was checked." if args.check else "PARITY.md was not written."),
            file=sys.stderr,
        )
        return SKIPPED
    old = TARGET.read_text() if TARGET.is_file() else ""
    try:
        new = Writer(Ledger(Extension(), args.sketches), read_prose(old)).document()
    except LedgerError as error:
        print(f"typing/parity.py: {error}", file=sys.stderr)
        return 1
    if args.check:
        if old == new:
            return 0
        print(first_difference(old, new), file=sys.stderr)
        if args.diff:
            sys.stderr.writelines(
                difflib.unified_diff(
                    old.splitlines(keepends=True),
                    new.splitlines(keepends=True),
                    "checked-in/PARITY.md",
                    "generated/PARITY.md",
                )
            )
        print(
            "Regenerate it with typing/parity.py and commit the result.",
            file=sys.stderr,
        )
        return 1
    if old != new:
        TARGET.write_text(new)
        print(f"Wrote {TARGET}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
