# Demo assets, fetched from the network into the build tree.
#
# The studies in src/common/compose/gallery and sketch/sketches are
# reference-grounded, and a reference set in whatever face the host OS
# happens to ship is only half-grounded. This target downloads the real
# open-licensed faces those studies want, so a study can name a typeface
# the way it names a hex value.
#
# Opt in — nothing here runs as part of `all`:
#
#     cmake --build build --config Release --target fetch_assets
#
# and the result lands in ${CMAKE_BINARY_DIR}/assets/, which the sketch
# host reads with `--assets <dir>` and the gallery finds through the
# SIGILCOMPOSE_ASSET_DIR compile definition.
#
# Rules for anything added to the manifest below:
#  * an OPEN licence, and the licence file is fetched alongside the asset;
#  * pinned to an immutable commit, never a branch, so the URL cannot
#    change under the hash;
#  * an EXPECTED_HASH, so a changed byte is a hard failure and not a
#    silent substitution;
#  * no game, film or museum rips. The studies reproduce GEOMETRY and
#    PALETTES, which are facts about a design; they do not ship its art.

set(SIGIL_ASSET_DIR "${CMAKE_BINARY_DIR}/assets" CACHE PATH
    "Where fetch_assets writes downloaded demo assets")

# google/fonts, pinned. Every entry is SIL Open Font License 1.1.
set(_gfonts_commit 684b69db51d59a3137ec0152fa3a3afc6f1b3814)
set(_gfonts_base
    "https://raw.githubusercontent.com/google/fonts/${_gfonts_commit}")

# path-under-google/fonts | destination | sha256
set(SIGIL_ASSET_MANIFEST
    # Archivo — grotesque with a width axis: the HUD and Y2K studies
    "ofl/archivo/Archivo%5Bwdth,wght%5D.ttf|fonts/Archivo.ttf|0e094a7d3c7c4c25cf1310c4b30014f1dae9332220b1c2c88f4fa996f0b05053"
    "ofl/archivo/OFL.txt|fonts/Archivo.OFL.txt|108b4e57c9c796d3d38d0428ca7ee39de47ad93187302718d9b2d8864b9b716b"
    # Inter — the Swiss workhorse: the Gerstner and Brockmann grids
    "ofl/inter/Inter%5Bopsz,wght%5D.ttf|fonts/Inter.ttf|29160a80ff49ddcab2c97711247e08b1fab27a484a329ce8b813d820dc559031"
    "ofl/inter/OFL.txt|fonts/Inter.OFL.txt|5b9321a4298cfeb6b34354164a1c3afc3db114569984c502b9b35d988fd58c57"
    # JetBrains Mono — the console and every readout
    "ofl/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf|fonts/JetBrainsMono.ttf|48715a42ec242c21e9f02692891e147d022299a52e48d5e413e1a942193ffeda"
    "ofl/jetbrainsmono/OFL.txt|fonts/JetBrainsMono.OFL.txt|b2fe5e8987594e9ffd1d2ca52a2f5d73eb8335243893c5d6254b5ad69269591d"
    # EB Garamond — the manuscript, the plate lettering, the inscriptions
    "ofl/ebgaramond/EBGaramond%5Bwght%5D.ttf|fonts/EBGaramond.ttf|ef9512f92f6d579e5dc75af59a5a4b1b8b47d2eda89e00b954d44520e5369027"
    "ofl/ebgaramond/OFL.txt|fonts/EBGaramond.OFL.txt|0985066662eb755ed3683ae5482a81a9195b49ce3f7e165cc2388b3dbece7dd7"
    # Bebas Neue — condensed display, the poster studies
    "ofl/bebasneue/BebasNeue-Regular.ttf|fonts/BebasNeue.ttf|08e4623805102d819f58601e46e345648846075e363b2ceb23313c2d1c83ec73"
    "ofl/bebasneue/OFL.txt|fonts/BebasNeue.OFL.txt|72082f6cb4d04be2ecf7cc7d9e1e7d73787f0af8a5a278a47cade70c16b78341"
)

# The fetch itself runs at BUILD time in script mode, so configuring the
# project never touches the network.
set(_fetch_script "${CMAKE_CURRENT_BINARY_DIR}/fetch_assets.cmake")
file(WRITE "${_fetch_script}" "# generated by cmake/FetchAssets.cmake\n")
file(APPEND "${_fetch_script}" "set(base \"${_gfonts_base}\")\n")
file(APPEND "${_fetch_script}" "set(out \"${SIGIL_ASSET_DIR}\")\n")
foreach(entry IN LISTS SIGIL_ASSET_MANIFEST)
  string(REPLACE "|" ";" parts "${entry}")
  list(GET parts 0 src)
  list(GET parts 1 dst)
  list(GET parts 2 hash)
  file(APPEND "${_fetch_script}" "
if(EXISTS \"\${out}/${dst}\")
  file(SHA256 \"\${out}/${dst}\" have)
  if(have STREQUAL \"${hash}\")
    message(STATUS \"have ${dst}\")
    set(skip TRUE)
  else()
    set(skip FALSE)
  endif()
else()
  set(skip FALSE)
endif()
if(NOT skip)
  message(STATUS \"fetch ${dst}\")
  file(DOWNLOAD \"\${base}/${src}\" \"\${out}/${dst}\"
       EXPECTED_HASH SHA256=${hash}
       TLS_VERIFY ON
       STATUS status)
  list(GET status 0 code)
  if(NOT code EQUAL 0)
    list(GET status 1 why)
    file(REMOVE \"\${out}/${dst}\")
    message(FATAL_ERROR \"${dst}: \${why}\")
  endif()
endif()
")
endforeach()
file(APPEND "${_fetch_script}"
     "message(STATUS \"assets in \${out}\")\n")

add_custom_target(fetch_assets
  COMMAND ${CMAKE_COMMAND} -P "${_fetch_script}"
  COMMENT "Fetching demo assets into ${SIGIL_ASSET_DIR}"
  VERBATIM)
