# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import _sigil.draw
import _sigil.skia
from . import format
__all__: list[str] = ['BleedDirection', 'Catalogue', 'Curl', 'Curve', 'Dab', 'DepositOptions', 'Direction', 'Drive', 'Dynamics', 'Engine', 'Gaussian', 'Grain', 'GrainSpace', 'Hatch', 'ImageMask', 'Input', 'Line', 'Mass', 'PlacedPlot', 'Plot', 'PlotType', 'Polygon', 'Position', 'Pressure', 'Response', 'Rotation', 'Sample', 'Sampler', 'Shape', 'Stroke', 'Tip', 'Tool', 'Variation', 'Vortex', 'Wash', 'Wave', 'charcoal', 'dabs', 'deposit', 'flowLine', 'format', 'hatch', 'hatchArray', 'line', 'marker', 'mass', 'massArray', 'paint', 'pencil', 'prepareStroke', 'randomBelow', 'segment', 'spacingOf', 'spline', 'spray', 'stockFields', 'trace', 'warp', 'wash', 'watercolor']

class BleedDirection:
    """
    Members:

      Out

      In
    """
    In: typing.ClassVar[BleedDirection]
    Out: typing.ClassVar[BleedDirection]
    __members__: typing.ClassVar[dict[str, BleedDirection]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Catalogue:

    @staticmethod
    def stock() -> Catalogue:
        ...

    def __init__(self) -> None:
        ...

    def add(self, arg0: str, arg1: Tool) -> _sigil.draw.brush.Tool | None:
        ...

    def contains(self, arg0: str) -> bool:
        ...

    def find(self, arg0: str) -> _sigil.draw.brush.Tool | None:
        ...

    def names(self) -> list[str]:
        ...

    def scale(self, arg0: typing.SupportsFloat) -> None:
        ...

class Curl:

    def __call__(self, position: _t.PointLike, seconds: typing.SupportsFloat=0.0) -> float:
        ...

    def __init__(self, seed: typing.SupportsInt=0, scale: typing.SupportsFloat=0.004000000189989805, drift: typing.SupportsFloat=0.07999999821186066) -> None:
        ...

    @property
    def drift(self) -> float:
        ...

    @property
    def scale(self) -> float:
        ...

    @property
    def seed(self) -> int:
        ...

class Curve:

    @staticmethod
    def flat(arg0: typing.SupportsFloat) -> Curve:
        ...

    def __init__(self, *, bend: _t.FloatLike=..., curve: _t.ScalarFunction | None=..., maximum: _t.FloatLike=..., minimum: _t.FloatLike=...) -> None:
        ...

    def at(self, arg0: typing.SupportsFloat) -> float:
        ...

    def copy(self) -> Curve:
        ...

    @property
    def bend(self) -> float:
        ...

    @bend.setter
    def bend(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def curve(self) -> collections.abc.Callable[[typing.SupportsFloat], float]:
        ...

    @curve.setter
    def curve(self, arg1: _t.ScalarFunction | None) -> None:
        ...

    @property
    def maximum(self) -> float:
        ...

    @maximum.setter
    def maximum(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def minimum(self) -> float:
        ...

    @minimum.setter
    def minimum(self, arg1: _t.FloatLike) -> None:
        ...

class Dab:

    def __init__(self, *, barrelRotation: _t.FloatLike=..., direction: _t.FloatLike=..., distance: _t.FloatLike=..., position: _t.PointLike=..., pressure: _t.FloatLike=..., progress: _t.FloatLike=..., speed: _t.FloatLike=..., tilt: _t.FloatLike=..., tiltDirection: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Dab:
        ...

    @property
    def barrelRotation(self) -> float:
        ...

    @barrelRotation.setter
    def barrelRotation(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def direction(self) -> float:
        ...

    @direction.setter
    def direction(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def distance(self) -> float:
        ...

    @distance.setter
    def distance(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def position(self) -> _sigil.skia.Point:
        ...

    @position.setter
    def position(self, arg1: _t.PointLike) -> None:
        ...

    @property
    def pressure(self) -> float:
        ...

    @pressure.setter
    def pressure(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def progress(self) -> float:
        ...

    @progress.setter
    def progress(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def speed(self) -> float:
        ...

    @speed.setter
    def speed(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tilt(self) -> float:
        ...

    @tilt.setter
    def tilt(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tiltDirection(self) -> float:
        ...

    @tiltDirection.setter
    def tiltDirection(self, arg1: _t.FloatLike) -> None:
        ...

class DepositOptions:

    def __init__(self, *, end: bool=..., start: bool=...) -> None:
        ...

    def copy(self) -> DepositOptions:
        ...

    @property
    def end(self) -> bool:
        ...

    @end.setter
    def end(self, arg1: bool) -> None:
        ...

    @property
    def start(self) -> bool:
        ...

    @start.setter
    def start(self, arg1: bool) -> None:
        ...

class Direction:

    def __call__(self, position: _t.PointLike, seconds: typing.SupportsFloat=0.0) -> float:
        ...

    def __init__(self, arg0: _t.DirectionLike) -> None:
        ...

class Drive:
    """
    Members:

      Pressure

      Velocity

      Tilt
    """
    Pressure: typing.ClassVar[Drive]
    Tilt: typing.ClassVar[Drive]
    Velocity: typing.ClassVar[Drive]
    __members__: typing.ClassVar[dict[str, Drive]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Dynamics:
    flow: _sigil.draw.brush.Response | None
    opacity: _sigil.draw.brush.Response | None
    size: _sigil.draw.brush.Response | None

    def __init__(self, *, flow: _sigil.draw.brush.Response | None=..., opacity: _sigil.draw.brush.Response | None=..., size: _sigil.draw.brush.Response | None=...) -> None:
        ...

    def copy(self) -> Dynamics:
        ...

    def empty(self) -> bool:
        ...

class Engine:

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: Catalogue) -> None:
        ...

    def add(self, arg0: str, arg1: Tool) -> _sigil.draw.brush.Tool | None:
        ...

    def addField(self, name: str, field: _t.DirectionLike, units: _sigil.draw.Constant=...) -> bool:
        ...

    def arc(self, arg0: _sigil.draw.Pen, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat) -> _sigil.draw.brush.PlacedPlot | None:
        ...

    def beginInput(self, arg0: _sigil.draw.Pen, arg1: Input) -> None:
        ...

    def beginShape(self, curvature: typing.SupportsFloat=0.0) -> None:
        ...

    def beginStroke(self, arg0: PlotType, arg1: _t.PointLike) -> None:
        ...

    def cancelInput(self) -> None:
        ...

    def cancelStroke(self) -> None:
        ...

    def circle(self, pen: _sigil.draw.Pen, x: typing.SupportsFloat, y: typing.SupportsFloat, radius: typing.SupportsFloat, irregularity: typing.SupportsFloat=0.0) -> PlacedPlot:
        ...

    @typing.overload
    def clip(self, arg0: _t.RectLike) -> None:
        ...

    @typing.overload
    def clip(self, arg0: _sigil.draw.Pen, arg1: _t.RectLike) -> None:
        ...

    @typing.overload
    def draw(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    @typing.overload
    def draw(self, pen: _sigil.draw.Pen, plot: Plot, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def endInput(self, arg0: _sigil.draw.Pen, arg1: Input) -> None:
        ...

    def endShape(self, pen: _sigil.draw.Pen, close: bool=False) -> _sigil.draw.brush.PlacedPlot | None:
        ...

    def endStroke(self, pen: _sigil.draw.Pen, angle: typing.SupportsFloat, pressure: typing.SupportsFloat=1.0) -> list[Sample]:
        ...

    def field(self, arg0: str) -> bool:
        ...

    @typing.overload
    def fill(self, color: _t.ColorLike, opacity: typing.SupportsFloat=0.5882353186607361) -> None:
        ...

    @typing.overload
    def fill(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    @typing.overload
    def fill(self, pen: _sigil.draw.Pen, plot: Plot, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def fillBleed(self, bleed: typing.SupportsFloat, direction: BleedDirection=..., angle: typing.SupportsFloat | None=None) -> None:
        ...

    def fillTexture(self, texture: typing.SupportsFloat=0.4000000059604645, border: typing.SupportsFloat=0.4000000059604645, scatter: bool=True) -> None:
        ...

    def flowLine(self, pen: _sigil.draw.Pen, start: _t.PointLike, length: typing.SupportsFloat, direction: typing.SupportsFloat) -> None:
        ...

    def hasStroke(self) -> bool:
        ...

    @typing.overload
    def hatch(self, style: Hatch=...) -> None:
        ...

    @typing.overload
    def hatch(self, pen: _sigil.draw.Pen, spacing: typing.SupportsFloat, angle: typing.SupportsFloat, jitter: typing.SupportsFloat=0.0, gradient: typing.SupportsFloat=0.0, continuous: bool=False) -> None:
        ...

    @typing.overload
    def hatch(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    @typing.overload
    def hatch(self, pen: _sigil.draw.Pen, plot: Plot, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def hatchArray(self, arg0: _sigil.draw.Pen, arg1: collections.abc.Sequence[Polygon]) -> None:
        ...

    @typing.overload
    def hatchArray(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    def hatchStyle(self, name: str, color: _t.ColorLike='#000000', weight: typing.SupportsFloat=1.0) -> _sigil.draw.brush.Tool | None:
        ...

    def line(self, pen: _sigil.draw.Pen, from_: _t.PointLike, to: _t.PointLike, startPressure: typing.SupportsFloat=1.0, endPressure: typing.SupportsFloat=1.0) -> None:
        ...

    def listFields(self) -> list[str]:
        ...

    @typing.overload
    def mass(self, name: str, color: _t.ColorLike, style: Mass=...) -> _sigil.draw.brush.Tool | None:
        ...

    @typing.overload
    def mass(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    @typing.overload
    def mass(self, pen: _sigil.draw.Pen, plot: Plot, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def massArray(self, arg0: _sigil.draw.Pen, arg1: collections.abc.Sequence[Polygon]) -> None:
        ...

    @typing.overload
    def massArray(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    def move(self, pen: _sigil.draw.Pen, angle: typing.SupportsFloat, length: typing.SupportsFloat, pressure: typing.SupportsFloat=1.0) -> None:
        ...

    def moveInput(self, arg0: _sigil.draw.Pen, arg1: Input) -> None:
        ...

    def names(self) -> list[str]:
        ...

    def noClip(self) -> None:
        ...

    def noField(self) -> None:
        ...

    def noFill(self) -> None:
        ...

    def noHatch(self) -> None:
        ...

    def noMass(self) -> None:
        ...

    def noStroke(self) -> None:
        ...

    def noWash(self) -> None:
        ...

    def paint(self, arg0: _sigil.draw.Pen, arg1: collections.abc.Iterable[_t.SampleLike]) -> None:
        ...

    def pick(self, arg0: str) -> _sigil.draw.brush.Tool | None:
        ...

    @typing.overload
    def polygon(self, arg0: _sigil.draw.Pen, arg1: collections.abc.Iterable[_t.PointLike]) -> Polygon:
        ...

    @typing.overload
    def polygon(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    def pop(self) -> None:
        ...

    @typing.overload
    def position(self, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0) -> Position:
        ...

    @typing.overload
    def position(self, pen: _sigil.draw.Pen, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0) -> Position:
        ...

    def push(self) -> None:
        ...

    @typing.overload
    def rect(self, pen: _sigil.draw.Pen, x: typing.SupportsFloat, y: typing.SupportsFloat, width: typing.SupportsFloat, height: typing.SupportsFloat, mode: _sigil.draw.Constant=...) -> None:
        ...

    @typing.overload
    def rect(self, pen: _sigil.draw.Pen, x: typing.SupportsFloat, y: typing.SupportsFloat, width: typing.SupportsFloat, height: typing.SupportsFloat, radius: typing.SupportsFloat) -> None:
        ...

    def scaleBrushes(self, arg0: typing.SupportsFloat) -> None:
        ...

    def set(self, name: str, color: _t.ColorLike, weight: typing.SupportsFloat=1.0) -> _sigil.draw.brush.Tool | None:
        ...

    def spline(self, pen: _sigil.draw.Pen, controls: collections.abc.Iterable[_t.SampleLike], curvature: typing.SupportsFloat=0.5) -> PlacedPlot:
        ...

    def stroke(self, arg0: _t.ColorLike) -> None:
        ...

    def strokeWeight(self, arg0: typing.SupportsFloat) -> None:
        ...

    def tool(self) -> Tool:
        ...

    def vertex(self, x: typing.SupportsFloat, y: typing.SupportsFloat, pressure: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def wash(self, color: _t.ColorLike, opacity: typing.SupportsFloat=0.5882353186607361) -> None:
        ...

    @typing.overload
    def wash(self, arg0: _sigil.draw.Pen, arg1: Polygon) -> None:
        ...

    @typing.overload
    def wash(self, pen: _sigil.draw.Pen, plot: Plot, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def wiggle(self, amount: typing.SupportsFloat=1.0) -> None:
        ...

class Gaussian:

    def __init__(self, *, center: _t.FloatLike=..., centerJitter: _t.FloatLike=..., maximum: _t.FloatLike=..., minimum: _t.FloatLike=..., sharpness: _t.FloatLike=..., width: _t.FloatLike=..., widthJitter: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Gaussian:
        ...

    @property
    def center(self) -> float:
        ...

    @center.setter
    def center(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def centerJitter(self) -> float:
        ...

    @centerJitter.setter
    def centerJitter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def maximum(self) -> float:
        ...

    @maximum.setter
    def maximum(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def minimum(self) -> float:
        ...

    @minimum.setter
    def minimum(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def sharpness(self) -> float:
        ...

    @sharpness.setter
    def sharpness(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def width(self) -> float:
        ...

    @width.setter
    def width(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def widthJitter(self) -> float:
        ...

    @widthJitter.setter
    def widthJitter(self, arg1: _t.FloatLike) -> None:
        ...

class Grain:

    def __init__(self, *, depth: _t.FloatLike=..., image: _sigil.skia.Image=..., scale: _t.FloatLike=..., space: GrainSpace=...) -> None:
        ...

    def copy(self) -> Grain:
        ...

    @property
    def depth(self) -> float:
        ...

    @depth.setter
    def depth(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def image(self) -> _sigil.skia.Image:
        ...

    @image.setter
    def image(self, arg1: _sigil.skia.Image) -> None:
        ...

    @property
    def scale(self) -> float:
        ...

    @scale.setter
    def scale(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def space(self) -> GrainSpace:
        ...

    @space.setter
    def space(self, arg1: GrainSpace) -> None:
        ...

class GrainSpace:
    """
    Members:

      Stroke

      Dab
    """
    Dab: typing.ClassVar[GrainSpace]
    Stroke: typing.ClassVar[GrainSpace]
    __members__: typing.ClassVar[dict[str, GrainSpace]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Hatch:

    def __init__(self, *, angle: _t.FloatLike=..., continuous: bool=..., gradient: _t.FloatLike=..., jitter: _t.FloatLike=..., spacing: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Hatch:
        ...

    @property
    def angle(self) -> float:
        ...

    @angle.setter
    def angle(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def continuous(self) -> bool:
        ...

    @continuous.setter
    def continuous(self, arg1: bool) -> None:
        ...

    @property
    def gradient(self) -> float:
        ...

    @gradient.setter
    def gradient(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def jitter(self) -> float:
        ...

    @jitter.setter
    def jitter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def spacing(self) -> float:
        ...

    @spacing.setter
    def spacing(self, arg1: _t.FloatLike) -> None:
        ...

class ImageMask:
    """
    Members:

      InvertedLuminance

      Alpha
    """
    Alpha: typing.ClassVar[ImageMask]
    InvertedLuminance: typing.ClassVar[ImageMask]
    __members__: typing.ClassVar[dict[str, ImageMask]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Input:

    @typing.overload
    def __init__(self, *, barrelRotation: _t.FloatLike=..., position: _t.PointLike=..., pressure: _t.FloatLike=..., seconds: _t.FloatLike=..., tilt: _t.FloatLike=..., tiltDirection: _t.FloatLike=...) -> None:
        ...

    @typing.overload
    def __init__(self, position: _t.PointLike, pressure: typing.SupportsFloat=1.0, tilt: typing.SupportsFloat=0.0, barrelRotation: typing.SupportsFloat=0.0, seconds: typing.SupportsFloat=0.0, tiltDirection: typing.SupportsFloat=0.0) -> None:
        ...

    def copy(self) -> Input:
        ...

    @property
    def barrelRotation(self) -> float:
        ...

    @barrelRotation.setter
    def barrelRotation(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def position(self) -> _sigil.skia.Point:
        ...

    @position.setter
    def position(self, arg1: _t.PointLike) -> None:
        ...

    @property
    def pressure(self) -> float:
        ...

    @pressure.setter
    def pressure(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def seconds(self) -> float:
        ...

    @seconds.setter
    def seconds(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tilt(self) -> float:
        ...

    @tilt.setter
    def tilt(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tiltDirection(self) -> float:
        ...

    @tiltDirection.setter
    def tiltDirection(self, arg1: _t.FloatLike) -> None:
        ...

class Line:

    @typing.overload
    def __init__(self, *, from_: _t.PointLike=..., to: _t.PointLike=...) -> None:
        ...

    @typing.overload
    def __init__(self, start: _t.PointLike, end: _t.PointLike) -> None:
        ...

    def copy(self) -> Line:
        ...

    @property
    def from_(self) -> _sigil.skia.Point:
        ...

    @from_.setter
    def from_(self, arg1: _t.PointLike) -> None:
        ...

    @property
    def to(self) -> _sigil.skia.Point:
        ...

    @to.setter
    def to(self, arg1: _t.PointLike) -> None:
        ...

class Mass:

    def __init__(self, *, gradient: _t.FloatLike=..., outline: bool=..., precision: _t.FloatLike=..., strength: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Mass:
        ...

    @property
    def gradient(self) -> float:
        ...

    @gradient.setter
    def gradient(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def outline(self) -> bool:
        ...

    @outline.setter
    def outline(self, arg1: bool) -> None:
        ...

    @property
    def precision(self) -> float:
        ...

    @precision.setter
    def precision(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def strength(self) -> float:
        ...

    @strength.setter
    def strength(self, arg1: _t.FloatLike) -> None:
        ...

class PlacedPlot:

    def __init__(self, *, origin: _t.PointLike=..., plot: Plot=...) -> None:
        ...

    def copy(self) -> PlacedPlot:
        ...

    def empty(self) -> bool:
        ...

    @property
    def origin(self) -> _sigil.skia.Point:
        ...

    @origin.setter
    def origin(self, arg1: _t.PointLike) -> None:
        ...

    @property
    def plot(self) -> Plot:
        ...

    @plot.setter
    def plot(self, arg1: Plot) -> None:
        ...

class Plot:

    @staticmethod
    def fromStroke(stroke: collections.abc.Iterable[_t.SampleLike], type: PlotType=...) -> Plot:
        ...

    def __init__(self, type: PlotType=...) -> None:
        ...

    def addSegment(self, angle: typing.SupportsFloat, length: typing.SupportsFloat, pressure: typing.SupportsFloat=1.0) -> None:
        ...

    def angle(self, arg0: typing.SupportsFloat) -> float:
        ...

    def copy(self) -> Plot:
        ...

    @typing.overload
    def draw(self, pen: _sigil.draw.Pen, tool: Tool, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def draw(self, pen: _sigil.draw.Pen, engine: Engine, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def empty(self) -> bool:
        ...

    def endPlot(self, angle: typing.SupportsFloat, pressure: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def fill(self, pen: _sigil.draw.Pen, style: Wash, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def fill(self, pen: _sigil.draw.Pen, engine: Engine, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def hatch(self, pen: _sigil.draw.Pen, tool: Tool, style: Hatch=..., x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def hatch(self, pen: _sigil.draw.Pen, engine: Engine, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def length(self) -> float:
        ...

    @typing.overload
    def mass(self, pen: _sigil.draw.Pen, tool: Tool, style: Mass=..., x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def mass(self, pen: _sigil.draw.Pen, engine: Engine, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def path(self, origin: _t.PointLike=(0, 0), spacing: typing.SupportsFloat=1.0, curvature: typing.SupportsFloat=0.5, scale: typing.SupportsFloat=1.0) -> list[Sample]:
        ...

    def polygon(self, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, spacing: typing.SupportsFloat=1.0, curvature: typing.SupportsFloat=0.5, scale: typing.SupportsFloat=1.0) -> Polygon:
        ...

    def pressure(self, arg0: typing.SupportsFloat) -> float:
        ...

    def rotate(self, arg0: typing.SupportsFloat) -> None:
        ...

    def show(self, pen: _sigil.draw.Pen, engine: Engine, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    def type(self) -> PlotType:
        ...

    @typing.overload
    def wash(self, pen: _sigil.draw.Pen, style: Wash, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

    @typing.overload
    def wash(self, pen: _sigil.draw.Pen, engine: Engine, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, scale: typing.SupportsFloat=1.0) -> None:
        ...

class PlotType:
    """
    Members:

      Curve

      Segments
    """
    Curve: typing.ClassVar[PlotType]
    Segments: typing.ClassVar[PlotType]
    __members__: typing.ClassVar[dict[str, PlotType]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Polygon:

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, vertices: collections.abc.Iterable[_t.PointLike]) -> None:
        ...

    def copy(self) -> Polygon:
        ...

    @typing.overload
    def draw(self, arg0: _sigil.draw.Pen, arg1: Tool) -> None:
        ...

    @typing.overload
    def draw(self, arg0: _sigil.draw.Pen, arg1: Engine) -> None:
        ...

    def empty(self) -> bool:
        ...

    @typing.overload
    def fill(self, arg0: _sigil.draw.Pen, arg1: Wash) -> None:
        ...

    @typing.overload
    def fill(self, arg0: _sigil.draw.Pen, arg1: Engine) -> None:
        ...

    @typing.overload
    def hatch(self, pen: _sigil.draw.Pen, tool: Tool, style: Hatch=...) -> None:
        ...

    @typing.overload
    def hatch(self, arg0: _sigil.draw.Pen, arg1: Engine) -> None:
        ...

    def intersect(self, arg0: Line) -> list[_sigil.skia.Point]:
        ...

    @typing.overload
    def mass(self, pen: _sigil.draw.Pen, tool: Tool, style: Mass=...) -> None:
        ...

    @typing.overload
    def mass(self, arg0: _sigil.draw.Pen, arg1: Engine) -> None:
        ...

    def show(self, arg0: _sigil.draw.Pen, arg1: Engine) -> None:
        ...

    def translated(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Polygon:
        ...

    @typing.overload
    def wash(self, arg0: _sigil.draw.Pen, arg1: Wash) -> None:
        ...

    @typing.overload
    def wash(self, arg0: _sigil.draw.Pen, arg1: Engine) -> None:
        ...

    @property
    def vertices(self) -> list[_sigil.skia.Point]:
        ...

    @vertices.setter
    def vertices(self, arg1: collections.abc.Iterable[_t.PointLike]) -> None:
        ...

class Position:

    def __init__(self, x: typing.SupportsFloat=0.0, y: typing.SupportsFloat=0.0, field: _t.DirectionLike | None=None, seconds: typing.SupportsFloat=0.0, bounds: _t.RectLike | None=None) -> None:
        ...

    @typing.overload
    def angle(self) -> float:
        ...

    @typing.overload
    def angle(self, field: _t.DirectionLike, seconds: typing.SupportsFloat=0.0) -> float:
        ...

    def field(self, value: _t.DirectionLike, seconds: typing.SupportsFloat=0.0) -> None:
        ...

    def isIn(self) -> bool:
        ...

    def isInCanvas(self) -> bool:
        ...

    def moveTo(self, direction: typing.SupportsFloat, length: typing.SupportsFloat, stepLength: typing.SupportsFloat=1.0, field: _t.DirectionLike | None=None, seconds: typing.SupportsFloat=0.0) -> list[Sample]:
        ...

    def place(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    def plotTo(self, plot: Plot, length: typing.SupportsFloat, stepLength: typing.SupportsFloat, scale: typing.SupportsFloat=1.0) -> list[Sample]:
        ...

    def plotted(self) -> float:
        ...

    def reset(self) -> None:
        ...

    def x(self) -> float:
        ...

    def y(self) -> float:
        ...

class Pressure:
    Gaussian = _sigil.draw.brush.Gaussian
    Variation = _sigil.draw.brush.Variation
    gaussian: _sigil.draw.brush.Gaussian | None
    variation: _sigil.draw.brush.Variation | None

    @staticmethod
    def gaussianProfile(centerJitter: typing.SupportsFloat, widthJitter: typing.SupportsFloat, minimum: typing.SupportsFloat, maximum: typing.SupportsFloat) -> Pressure:
        ...

    @typing.overload
    def __init__(self, *, gaussian: _sigil.draw.brush.Gaussian | None=..., variation: _sigil.draw.brush.Variation | None=..., curve: _t.ScalarFunction | None=..., end: _t.FloatLike=..., middle: _t.FloatLike=..., start: _t.FloatLike=...) -> None:
        ...

    @typing.overload
    def __init__(self, start: typing.SupportsFloat, middle: typing.SupportsFloat, end: typing.SupportsFloat) -> None:
        ...

    def at(self, arg0: typing.SupportsFloat) -> float:
        ...

    def copy(self) -> Pressure:
        ...

    @property
    def curve(self) -> collections.abc.Callable[[typing.SupportsFloat], float]:
        ...

    @curve.setter
    def curve(self, arg1: _t.ScalarFunction | None) -> None:
        ...

    @property
    def end(self) -> float:
        ...

    @end.setter
    def end(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def middle(self) -> float:
        ...

    @middle.setter
    def middle(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def start(self) -> float:
        ...

    @start.setter
    def start(self, arg1: _t.FloatLike) -> None:
        ...

class Response:

    def __init__(self, *, curve: Curve=..., drive: Drive=...) -> None:
        ...

    def at(self, dab: Dab, pressure: typing.SupportsFloat, speedReference: typing.SupportsFloat) -> float:
        ...

    def copy(self) -> Response:
        ...

    @property
    def curve(self) -> Curve:
        ...

    @curve.setter
    def curve(self, arg1: Curve) -> None:
        ...

    @property
    def drive(self) -> Drive:
        ...

    @drive.setter
    def drive(self, arg1: Drive) -> None:
        ...

class Rotation:
    """
    Members:

      Fixed

      Natural

      Random

      Tilt
    """
    Fixed: typing.ClassVar[Rotation]
    Natural: typing.ClassVar[Rotation]
    Random: typing.ClassVar[Rotation]
    Tilt: typing.ClassVar[Rotation]
    __members__: typing.ClassVar[dict[str, Rotation]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Sample:

    @typing.overload
    def __init__(self, *, position: _t.PointLike=..., pressure: _t.FloatLike=...) -> None:
        ...

    @typing.overload
    def __init__(self, position: _t.PointLike, pressure: typing.SupportsFloat=1.0) -> None:
        ...

    def copy(self) -> Sample:
        ...

    @property
    def position(self) -> _sigil.skia.Point:
        ...

    @position.setter
    def position(self, arg1: _t.PointLike) -> None:
        ...

    @property
    def pressure(self) -> float:
        ...

    @pressure.setter
    def pressure(self, arg1: _t.FloatLike) -> None:
        ...

class Sampler:

    def __init__(self, speedFilterSeconds: typing.SupportsFloat=0.03999999910593033) -> None:
        ...

    def active(self) -> bool:
        ...

    def begin(self, arg0: Input) -> list[Dab]:
        ...

    def cancel(self) -> None:
        ...

    def distance(self) -> float:
        ...

    def end(self, arg0: Input, arg1: typing.SupportsFloat) -> list[Dab]:
        ...

    def move(self, arg0: Input, arg1: typing.SupportsFloat) -> list[Dab]:
        ...

class Shape:

    def __init__(self, *, angleJitter: _t.FloatLike=..., image: _sigil.skia.Image=..., mask: ImageMask=..., scatter: _t.FloatLike=..., spacing: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Shape:
        ...

    @property
    def angleJitter(self) -> float:
        ...

    @angleJitter.setter
    def angleJitter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def image(self) -> _sigil.skia.Image:
        ...

    @image.setter
    def image(self, arg1: _sigil.skia.Image) -> None:
        ...

    @property
    def mask(self) -> ImageMask:
        ...

    @mask.setter
    def mask(self, arg1: ImageMask) -> None:
        ...

    @property
    def scatter(self) -> float:
        ...

    @scatter.setter
    def scatter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def spacing(self) -> float:
        ...

    @spacing.setter
    def spacing(self, arg1: _t.FloatLike) -> None:
        ...

class Tip:
    """
    Members:

      Dust

      Fibres

      Nib

      Scatter

      Image

      Custom
    """
    Custom: typing.ClassVar[Tip]
    Dust: typing.ClassVar[Tip]
    Fibres: typing.ClassVar[Tip]
    Image: typing.ClassVar[Tip]
    Nib: typing.ClassVar[Tip]
    Scatter: typing.ClassVar[Tip]
    __members__: typing.ClassVar[dict[str, Tip]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Tool:
    customTip: collections.abc.Callable[[], None] | _t.DrawCallback | collections.abc.Callable[[_sigil.draw.Pen, Dab], None] | None
    grain: _sigil.draw.brush.Grain | None
    shape: _sigil.draw.brush.Shape | None

    def __init__(self, *, customTip: collections.abc.Callable[[], None] | _t.DrawCallback | collections.abc.Callable[[_sigil.draw.Pen, Dab], None] | None=..., grain: _sigil.draw.brush.Grain | None=..., shape: _sigil.draw.brush.Shape | None=..., angle: _t.FloatLike=..., aspect: _t.FloatLike=..., blend: _sigil.draw.Constant=..., bristles: typing.SupportsInt=..., color: _t.ColorLike=..., density: _t.FloatLike=..., dynamics: Dynamics=..., markerTip: bool=..., noise: _t.FloatLike=..., opacity: _t.FloatLike=..., opacityJitter: _t.FloatLike=..., pressure: Pressure=..., pressureOpacity: _t.FloatLike=..., pressureSize: _t.FloatLike=..., rotation: Rotation=..., scatter: _t.FloatLike=..., sharpness: _t.FloatLike=..., sizeJitter: _t.FloatLike=..., spacing: _t.FloatLike=..., spacingJitter: _t.FloatLike=..., speedOpacity: _t.FloatLike=..., speedReference: _t.FloatLike=..., speedSize: _t.FloatLike=..., tiltAspect: _t.FloatLike=..., tiltOffset: _t.FloatLike=..., tiltOpacity: _t.FloatLike=..., tiltSize: _t.FloatLike=..., tip: Tip=..., width: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Tool:
        ...

    @property
    def angle(self) -> float:
        ...

    @angle.setter
    def angle(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def aspect(self) -> float:
        ...

    @aspect.setter
    def aspect(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def blend(self) -> _sigil.draw.Constant:
        ...

    @blend.setter
    def blend(self, arg1: _sigil.draw.Constant) -> None:
        ...

    @property
    def bristles(self) -> int:
        ...

    @bristles.setter
    def bristles(self, arg1: typing.SupportsInt) -> None:
        ...

    @property
    def color(self) -> _sigil.skia.Color:
        ...

    @color.setter
    def color(self, arg1: _t.ColorLike) -> None:
        ...

    @property
    def density(self) -> float:
        ...

    @density.setter
    def density(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def dynamics(self) -> Dynamics:
        ...

    @dynamics.setter
    def dynamics(self, arg1: Dynamics) -> None:
        ...

    @property
    def markerTip(self) -> bool:
        ...

    @markerTip.setter
    def markerTip(self, arg1: bool) -> None:
        ...

    @property
    def noise(self) -> float:
        ...

    @noise.setter
    def noise(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def opacity(self) -> float:
        ...

    @opacity.setter
    def opacity(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def opacityJitter(self) -> float:
        ...

    @opacityJitter.setter
    def opacityJitter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def pressure(self) -> Pressure:
        ...

    @pressure.setter
    def pressure(self, arg1: Pressure) -> None:
        ...

    @property
    def pressureOpacity(self) -> float:
        ...

    @pressureOpacity.setter
    def pressureOpacity(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def pressureSize(self) -> float:
        ...

    @pressureSize.setter
    def pressureSize(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def rotation(self) -> Rotation:
        ...

    @rotation.setter
    def rotation(self, arg1: Rotation) -> None:
        ...

    @property
    def scatter(self) -> float:
        ...

    @scatter.setter
    def scatter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def sharpness(self) -> float:
        ...

    @sharpness.setter
    def sharpness(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def sizeJitter(self) -> float:
        ...

    @sizeJitter.setter
    def sizeJitter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def spacing(self) -> float:
        ...

    @spacing.setter
    def spacing(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def spacingJitter(self) -> float:
        ...

    @spacingJitter.setter
    def spacingJitter(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def speedOpacity(self) -> float:
        ...

    @speedOpacity.setter
    def speedOpacity(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def speedReference(self) -> float:
        ...

    @speedReference.setter
    def speedReference(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def speedSize(self) -> float:
        ...

    @speedSize.setter
    def speedSize(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tiltAspect(self) -> float:
        ...

    @tiltAspect.setter
    def tiltAspect(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tiltOffset(self) -> float:
        ...

    @tiltOffset.setter
    def tiltOffset(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tiltOpacity(self) -> float:
        ...

    @tiltOpacity.setter
    def tiltOpacity(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tiltSize(self) -> float:
        ...

    @tiltSize.setter
    def tiltSize(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tip(self) -> Tip:
        ...

    @tip.setter
    def tip(self, arg1: Tip) -> None:
        ...

    @property
    def width(self) -> float:
        ...

    @width.setter
    def width(self, arg1: _t.FloatLike) -> None:
        ...

class Variation:

    def __init__(self, *, offset: _t.FloatLike=..., scale: _t.FloatLike=..., tilt: _t.FloatLike=..., warp: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Variation:
        ...

    @property
    def offset(self) -> float:
        ...

    @offset.setter
    def offset(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def scale(self) -> float:
        ...

    @scale.setter
    def scale(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def tilt(self) -> float:
        ...

    @tilt.setter
    def tilt(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def warp(self) -> float:
        ...

    @warp.setter
    def warp(self, arg1: _t.FloatLike) -> None:
        ...

class Vortex:

    def __call__(self, position: _t.PointLike, seconds: typing.SupportsFloat=0.0) -> float:
        ...

    def __init__(self, *, center: _t.PointLike=..., direction: _t.FloatLike=..., pull: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Vortex:
        ...

    @property
    def center(self) -> _sigil.skia.Point:
        ...

    @center.setter
    def center(self, arg1: _t.PointLike) -> None:
        ...

    @property
    def direction(self) -> float:
        ...

    @direction.setter
    def direction(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def pull(self) -> float:
        ...

    @pull.setter
    def pull(self, arg1: _t.FloatLike) -> None:
        ...

class Wash:

    def __init__(self, *, bleed: _t.FloatLike=..., bleedAngle: typing.SupportsFloat | None=..., bleedDirection: BleedDirection=..., blend: _sigil.draw.Constant=..., border: _t.FloatLike=..., color: _t.ColorLike=..., layers: typing.SupportsInt=..., opacity: _t.FloatLike=..., scatter: bool=..., texture: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Wash:
        ...

    @property
    def bleed(self) -> float:
        ...

    @bleed.setter
    def bleed(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def bleedAngle(self) -> float | None:
        ...

    @bleedAngle.setter
    def bleedAngle(self, arg1: typing.SupportsFloat | None) -> None:
        ...

    @property
    def bleedDirection(self) -> BleedDirection:
        ...

    @bleedDirection.setter
    def bleedDirection(self, arg1: BleedDirection) -> None:
        ...

    @property
    def blend(self) -> _sigil.draw.Constant:
        ...

    @blend.setter
    def blend(self, arg1: _sigil.draw.Constant) -> None:
        ...

    @property
    def border(self) -> float:
        ...

    @border.setter
    def border(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def color(self) -> _sigil.skia.Color:
        ...

    @color.setter
    def color(self, arg1: _t.ColorLike) -> None:
        ...

    @property
    def layers(self) -> int:
        ...

    @layers.setter
    def layers(self, arg1: typing.SupportsInt) -> None:
        ...

    @property
    def opacity(self) -> float:
        ...

    @opacity.setter
    def opacity(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def scatter(self) -> bool:
        ...

    @scatter.setter
    def scatter(self, arg1: bool) -> None:
        ...

    @property
    def texture(self) -> float:
        ...

    @texture.setter
    def texture(self, arg1: _t.FloatLike) -> None:
        ...

class Wave:

    def __call__(self, position: _t.PointLike, seconds: typing.SupportsFloat=0.0) -> float:
        ...

    def __init__(self, *, amplitude: _t.FloatLike=..., direction: _t.FloatLike=..., speed: _t.FloatLike=..., wavelength: _t.FloatLike=...) -> None:
        ...

    def copy(self) -> Wave:
        ...

    @property
    def amplitude(self) -> float:
        ...

    @amplitude.setter
    def amplitude(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def direction(self) -> float:
        ...

    @direction.setter
    def direction(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def speed(self) -> float:
        ...

    @speed.setter
    def speed(self, arg1: _t.FloatLike) -> None:
        ...

    @property
    def wavelength(self) -> float:
        ...

    @wavelength.setter
    def wavelength(self, arg1: _t.FloatLike) -> None:
        ...

def charcoal(color: _t.ColorLike, width: typing.SupportsFloat=9.0) -> Tool:
    ...

def dabs(input: collections.abc.Sequence[Input], spacing: typing.SupportsFloat, speedFilterSeconds: typing.SupportsFloat=0.03999999910593033) -> list[Dab]:
    ...

def deposit(pen: _sigil.draw.Pen, tool: Tool, dabs: collections.abc.Sequence[Dab], options: DepositOptions=...) -> None:
    ...

def flowLine(pen: _sigil.draw.Pen, tool: Tool, start: _t.PointLike, length: typing.SupportsFloat, seconds: typing.SupportsFloat, field: _t.DirectionLike, pressure: typing.SupportsFloat=1.0) -> None:
    ...

def hatch(pen: _sigil.draw.Pen, tool: Tool, polygon: collections.abc.Iterable[_t.PointLike], style: Hatch=...) -> None:
    ...

def hatchArray(pen: _sigil.draw.Pen, tool: Tool, polygons: collections.abc.Sequence[Polygon], style: Hatch=...) -> None:
    ...

def line(pen: _sigil.draw.Pen, tool: Tool, from_: _t.PointLike, to: _t.PointLike, startPressure: typing.SupportsFloat=1.0, endPressure: typing.SupportsFloat=1.0) -> None:
    ...

def marker(color: _t.ColorLike, width: typing.SupportsFloat=16.0) -> Tool:
    ...

def mass(pen: _sigil.draw.Pen, tool: Tool, polygon: collections.abc.Iterable[_t.PointLike], style: Mass=...) -> None:
    ...

def massArray(pen: _sigil.draw.Pen, tool: Tool, polygons: collections.abc.Sequence[Polygon], style: Mass=...) -> None:
    ...

def paint(arg0: _sigil.draw.Pen, arg1: Tool, arg2: collections.abc.Iterable[_t.SampleLike]) -> None:
    ...

def pencil(color: _t.ColorLike, width: typing.SupportsFloat=1.399999976158142) -> Tool:
    ...

def prepareStroke(arg0: _sigil.draw.Pen, arg1: Tool) -> Tool:
    ...

def randomBelow(arg0: _sigil.draw.Pen, arg1: typing.SupportsFloat) -> float:
    ...

def segment(from_: _t.PointLike, to: _t.PointLike, spacing: typing.SupportsFloat=1.0, startPressure: typing.SupportsFloat=1.0, endPressure: typing.SupportsFloat=1.0) -> list[Sample]:
    ...

def spacingOf(arg0: Tool) -> float:
    ...

@typing.overload
def spline(controls: collections.abc.Iterable[_t.SampleLike], spacing: typing.SupportsFloat=1.0, curvature: typing.SupportsFloat=0.5) -> list[Sample]:
    ...

@typing.overload
def spline(pen: _sigil.draw.Pen, tool: Tool, controls: collections.abc.Iterable[_t.SampleLike], curvature: typing.SupportsFloat=0.5) -> None:
    ...

def spray(color: _t.ColorLike, width: typing.SupportsFloat=18.0) -> Tool:
    ...

def stockFields() -> dict[str, Direction]:
    ...

def trace(start: _t.PointLike, length: typing.SupportsFloat, spacing: typing.SupportsFloat, seconds: typing.SupportsFloat, field: _t.DirectionLike, pressure: typing.SupportsFloat=1.0) -> list[Sample]:
    ...

def warp(polygon: collections.abc.Iterable[_t.PointLike], spacing: typing.SupportsFloat, amount: typing.SupportsFloat, seconds: typing.SupportsFloat, field: _t.DirectionLike, pressure: typing.SupportsFloat=1.0) -> list[Sample]:
    ...

def wash(arg0: _sigil.draw.Pen, arg1: Wash, arg2: collections.abc.Iterable[_t.PointLike]) -> None:
    ...

def watercolor(color: _t.ColorLike, width: typing.SupportsFloat=22.0) -> Tool:
    ...
Stroke: typing.TypeAlias = list[Sample]
