# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil.draw.brush
__all__: list[str] = ['assembleBrush', 'decodeBrush', 'decodePhotoshopBrushes', 'decodeProcreateBrush', 'encodeBrush', 'isPhotoshopBrushes']

def assembleBrush(description: bytes=b'', shape: bytes=b'', grain: bytes=b'') -> _sigil.draw.brush.Tool | None:
    ...

def decodeBrush(bytes: bytes, hint: str='') -> _sigil.draw.brush.Tool | None:
    ...

def decodePhotoshopBrushes(arg0: bytes) -> list[_sigil.draw.brush.Tool]:
    ...

def decodeProcreateBrush(arg0: bytes) -> _sigil.draw.brush.Tool | None:
    ...

def encodeBrush(arg0: _sigil.draw.brush.Tool) -> str:
    ...

def isPhotoshopBrushes(arg0: bytes) -> bool:
    ...
