# Generated by typing/generate.py; edit typing/surface.py and
# typing/additions, not this file.

from _sigil.material.pattern import (
    Tile,
    checker,
    ditherBits,
    gridLines,
    halftone,
    scanlines,
    stipple,
    stripes,
)

__all__ = [
    "Tile",
    "checker",
    "ditherBits",
    "gridLines",
    "halftone",
    "scanlines",
    "stipple",
    "stripes",
]
