# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import builtins
import collections.abc
import typing
import os
import pathlib
__all__: list[str] = ['Arrival', 'Feed', 'FeedPolicy', 'Hub', 'NetworkPolicy', 'RecordingWriter', 'ResourceInfo', 'SharedMemoryWriter', 'readRecording', 'registerGrpc', 'registerMidi', 'registerQuic', 'registerSerial', 'registerSharedMemory', 'registerTransports', 'registerUdp', 'registerWebRtc', 'registerWebSocket', 'registerWebSocketClient']

class Arrival:
    from_: str

    def __init__(self, at: typing.SupportsFloat=0, bytes: collections.abc.Buffer=b'', from_: str='', generation: typing.SupportsInt=0) -> None:
        ...

    @property
    def at(self) -> float:
        ...

    @at.setter
    def at(self, arg0: typing.SupportsFloat) -> None:
        ...

    @property
    def bytes(self) -> bytes:
        ...

    @bytes.setter
    def bytes(self, arg1: collections.abc.Buffer) -> None:
        ...

    @property
    def generation(self) -> int:
        ...

    @generation.setter
    def generation(self, arg0: typing.SupportsInt) -> None:
        ...

class Feed:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, arg0: builtins.object) -> bool:
        ...

    def __init__(self, uri: str, policy: FeedPolicy=...) -> None:
        ...

    def address(self) -> str:
        ...

    def advance(self, seconds: typing.SupportsFloat) -> None:
        ...

    def close(self) -> None:
        ...

    def closed(self) -> bool:
        ...

    @typing.overload
    def deliver(self, bytes: collections.abc.Buffer) -> None:
        ...

    @typing.overload
    def deliver(self, bytes: collections.abc.Buffer, from_: str) -> None:
        ...

    @typing.overload
    def deliver(self, bytes: collections.abc.Buffer, at: typing.SupportsFloat) -> None:
        ...

    def dropped(self) -> int:
        ...

    def error(self) -> str:
        ...

    def fail(self, why: str) -> None:
        ...

    def generation(self) -> int:
        ...

    def latest(self) -> bytes | None:
        ...

    def newest(self) -> _sigil.io.Arrival | None:
        ...

    def opened(self) -> bool:
        ...

    def receive(self) -> _sigil.io.Arrival | None:
        ...

    def record(self, path: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> None:
        ...

    def replay(self, recording: collections.abc.Sequence[Arrival]) -> None:
        ...

    def send(self, bytes: collections.abc.Buffer) -> bool:
        ...

    def sendTo(self, to: str, bytes: collections.abc.Buffer) -> bool:
        ...

    def uri(self) -> str:
        ...

class FeedPolicy:

    def __init__(self, capacity: typing.SupportsInt=256) -> None:
        ...

    @property
    def capacity(self) -> int:
        ...

    @capacity.setter
    def capacity(self, arg0: typing.SupportsInt) -> None:
        ...

class Hub:

    def __init__(self) -> None:
        ...

    def blob(self, uri: str) -> bytes | None:
        ...

    @typing.overload
    def dispatch(self) -> None:
        ...

    @typing.overload
    def dispatch(self, seconds: typing.SupportsFloat) -> None:
        ...

    def feed(self, uri: str, policy: FeedPolicy=...) -> Feed:
        ...

    def feeds(self) -> list[Feed]:
        ...

    def fetch(self, uri: str) -> bytes | None:
        ...

    def mount(self, prefix: str, path: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> None:
        ...

    def poll(self) -> bool:
        ...

    def probe(self, uri: str) -> _sigil.io.ResourceInfo | None:
        ...

    def resolve(self, uri: str) -> pathlib.Path:
        ...

    def select(self, uri: str) -> list[str]:
        ...

    def setNetworkCacheDirectory(self, path: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> None:
        ...

    def setNetworkPolicy(self, policy: NetworkPolicy) -> None:
        ...

    def text(self, uri: str) -> str | None:
        ...

    def write(self, uri: str, bytes: collections.abc.Buffer) -> bool:
        ...

class NetworkPolicy:
    """
    Members:

      CacheFirst

      Refresh

      Offline
    """
    CacheFirst: typing.ClassVar[NetworkPolicy]
    Offline: typing.ClassVar[NetworkPolicy]
    Refresh: typing.ClassVar[NetworkPolicy]
    __members__: typing.ClassVar[dict[str, NetworkPolicy]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class RecordingWriter:

    def __init__(self, path: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> None:
        ...

    def append(self, arrival: Arrival) -> bool:
        ...

    def good(self) -> bool:
        ...

class ResourceInfo:

    @property
    def byteSize(self) -> int:
        ...

    @property
    def path(self) -> pathlib.Path:
        ...

class SharedMemoryWriter:

    def __init__(self, name: str, capacity: typing.SupportsInt) -> None:
        ...

    def open(self) -> bool:
        ...

    def write(self, bytes: collections.abc.Buffer) -> bool:
        ...

def readRecording(path: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> list[Arrival] | None:
    ...

def registerGrpc(hub: Hub) -> None:
    ...

def registerMidi(hub: Hub) -> None:
    ...

def registerQuic(hub: Hub) -> None:
    ...

def registerSerial(hub: Hub) -> None:
    ...

def registerSharedMemory(hub: Hub) -> None:
    ...

def registerTransports(hub: Hub) -> None:
    ...

def registerUdp(hub: Hub) -> None:
    ...

def registerWebRtc(hub: Hub) -> None:
    ...

def registerWebSocket(hub: Hub) -> None:
    ...

def registerWebSocketClient(hub: Hub) -> None:
    ...
