# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import os
import _sigil.io
import pathlib
__all__: list[str] = ['Column', 'ColumnType', 'CsvOptions', 'Database', 'Engine', 'Flag', 'Group', 'Instant', 'Interval', 'Json', 'JsonKind', 'Order', 'Overflow', 'Scale', 'Schema', 'Table', 'Transform', 'decodeArtNet', 'decodeCsv', 'decodeInstant', 'decodeJson', 'decodeMidi', 'decodeOsc', 'encodeArtNet', 'encodeJson', 'encodeMidi', 'encodeOsc', 'engineOf', 'maxOscPacketBytes', 'registerDecoders', 'tableFromJson']

class Column:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getitem__(self, row: typing.SupportsInt) -> _t.CellValue:
        ...

    def __init__(self, name: str, values: collections.abc.Iterable[_t.CellInput], type: _sigil.data.ColumnType | None=None) -> None:
        ...

    def __len__(self) -> int:
        ...

    def at(self, row: typing.SupportsInt) -> _t.CellValue:
        ...

    def copy(self) -> Column:
        ...

    def empty(self) -> bool:
        ...

    def markMissing(self, row: typing.SupportsInt) -> None:
        ...

    def missing(self, row: typing.SupportsInt) -> bool:
        ...

    def name(self) -> str:
        ...

    def rename(self, name: str) -> None:
        ...

    def size(self) -> int:
        ...

    def take(self, rows: collections.abc.Sequence[typing.SupportsInt]) -> Column:
        ...

    def type(self) -> ColumnType:
        ...

    def values(self) -> list[_t.CellValue]:
        ...

class ColumnType:
    """
    Members:

      Number

      Text

      Boolean

      Time
    """
    Boolean: typing.ClassVar[ColumnType]
    Number: typing.ClassVar[ColumnType]
    Text: typing.ClassVar[ColumnType]
    Time: typing.ClassVar[ColumnType]
    __members__: typing.ClassVar[dict[str, ColumnType]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class CsvOptions:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]
    comment: str
    delimiter: str
    header: bool

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __init__(self, *, comment: str=..., delimiter: str=..., header: bool=...) -> None:
        ...

    def copy(self) -> CsvOptions:
        ...

class Database:

    @staticmethod
    def fromBytes(bytes: bytes, hint: str='data.sqlite') -> Database:
        ...

    @staticmethod
    def memory(engine: Engine=...) -> Database:
        ...

    @staticmethod
    def open(path: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> Database:
        ...

    def engine(self) -> Engine:
        ...

    def execute(self, sql: str) -> None:
        ...

    def file(self) -> pathlib.Path:
        ...

    def insert(self, name: str, rows: Table) -> None:
        ...

    def query(self, sql: str) -> Table:
        ...

class Engine:
    """
    Members:

      Sqlite

      Duck
    """
    Duck: typing.ClassVar[Engine]
    Sqlite: typing.ClassVar[Engine]
    __members__: typing.ClassVar[dict[str, Engine]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Flag:
    set: bool

    def __bool__(self) -> bool:
        ...

    def __init__(self, set: bool=False) -> None:
        ...

class Group:

    @property
    def key(self) -> _t.CellValue:
        ...

    @property
    def rows(self) -> list[int]:
        ...

class Instant:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __float__(self) -> float:
        ...

    def __init__(self, seconds: typing.SupportsFloat=0) -> None:
        ...

    @property
    def seconds(self) -> float:
        ...

    @seconds.setter
    def seconds(self, value: typing.SupportsFloat, /) -> None:
        ...

class Interval:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __init__(self, low: typing.SupportsFloat=0, high: typing.SupportsFloat=1) -> None:
        ...

    def degenerate(self) -> bool:
        ...

    def extent(self) -> float:
        ...

    @property
    def high(self) -> float:
        ...

    @high.setter
    def high(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def low(self) -> float:
        ...

    @low.setter
    def low(self, value: typing.SupportsFloat, /) -> None:
        ...

class Json:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    @staticmethod
    def object(items: collections.abc.Iterable[tuple[str, _t.JsonInput]]) -> Json:
        ...

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getitem__(self, key: str | typing.SupportsInt) -> Json:
        ...

    def __init__(self, value: _t.JsonInput | None=None) -> None:
        ...

    def __len__(self) -> int:
        ...

    def __repr__(self) -> str:
        ...

    def boolean(self, fallback: bool=False) -> bool:
        ...

    def copy(self) -> Json:
        ...

    def fields(self) -> list[tuple[str, Json]]:
        ...

    def items(self) -> list[Json]:
        ...

    def kind(self) -> JsonKind:
        ...

    def null(self) -> bool:
        ...

    def number(self, fallback: typing.SupportsFloat=0) -> float:
        ...

    def size(self) -> int:
        ...

    def text(self, fallback: str='') -> str:
        ...

    def to_python(self) -> _t.JsonValue:
        """
        A detached Python value; duplicate object keys keep the first member.
        """

class JsonKind:
    """
    Members:

      Null

      Boolean

      Number

      Text

      List

      Record
    """
    Boolean: typing.ClassVar[JsonKind]
    List: typing.ClassVar[JsonKind]
    Null: typing.ClassVar[JsonKind]
    Number: typing.ClassVar[JsonKind]
    Record: typing.ClassVar[JsonKind]
    Text: typing.ClassVar[JsonKind]
    __members__: typing.ClassVar[dict[str, JsonKind]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Order:
    """
    Members:

      Ascending

      Descending
    """
    Ascending: typing.ClassVar[Order]
    Descending: typing.ClassVar[Order]
    __members__: typing.ClassVar[dict[str, Order]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Overflow:
    """
    Members:

      Extend

      Clamp

      Wrap

      PingPong
    """
    Clamp: typing.ClassVar[Overflow]
    Extend: typing.ClassVar[Overflow]
    PingPong: typing.ClassVar[Overflow]
    Wrap: typing.ClassVar[Overflow]
    __members__: typing.ClassVar[dict[str, Overflow]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Scale:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]
    overflow: Overflow
    transform: Transform

    def __call__(self, value: typing.SupportsFloat) -> float:
        ...

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __init__(self, *, overflow: Overflow=..., transform: Transform=..., base: typing.SupportsFloat=..., domain: Interval | collections.abc.Sequence[_t.FloatLike]=..., exponent: typing.SupportsFloat=..., outerPadding: typing.SupportsFloat=..., padding: typing.SupportsFloat=..., range: Interval | collections.abc.Sequence[_t.FloatLike]=..., steps: typing.SupportsInt=..., threshold: typing.SupportsFloat=..., thresholds: collections.abc.Sequence[typing.SupportsFloat]=...) -> None:
        ...

    def apply(self, value: typing.SupportsFloat) -> float:
        ...

    def bandwidth(self) -> float:
        ...

    def copy(self) -> Scale:
        ...

    def invert(self, value: typing.SupportsFloat) -> float:
        ...

    def nice(self, count: typing.SupportsInt=10) -> Scale:
        ...

    def position(self, index: typing.SupportsFloat) -> float:
        ...

    def slot(self, value: typing.SupportsFloat) -> int:
        ...

    def stepWidth(self) -> float:
        ...

    def through[Result](self, input: _t.FloatLike, interpolate: collections.abc.Callable[[float], Result]) -> Result:
        ...

    def tickStep(self, count: typing.SupportsInt=10) -> float:
        ...

    def ticks(self, count: typing.SupportsInt=10) -> list[float]:
        ...

    @property
    def base(self) -> float:
        ...

    @base.setter
    def base(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def domain(self) -> Interval:
        ...

    @domain.setter
    def domain(self, value: Interval | collections.abc.Sequence[_t.FloatLike], /) -> None:
        ...

    @property
    def exponent(self) -> float:
        ...

    @exponent.setter
    def exponent(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def outerPadding(self) -> float:
        ...

    @outerPadding.setter
    def outerPadding(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def padding(self) -> float:
        ...

    @padding.setter
    def padding(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def range(self) -> Interval:
        ...

    @range.setter
    def range(self, value: Interval | collections.abc.Sequence[_t.FloatLike], /) -> None:
        ...

    @property
    def steps(self) -> int:
        ...

    @steps.setter
    def steps(self, value: typing.SupportsInt, /) -> None:
        ...

    @property
    def threshold(self) -> float:
        ...

    @threshold.setter
    def threshold(self, value: typing.SupportsFloat, /) -> None:
        ...

    @property
    def thresholds(self) -> list[float]:
        ...

    @thresholds.setter
    def thresholds(self, value: collections.abc.Sequence[typing.SupportsFloat], /) -> None:
        ...

class Schema:

    @staticmethod
    def fromBinarySchema(bytes: bytes) -> Schema:
        ...

    def __bool__(self) -> bool:
        ...

    def __init__(self) -> None:
        ...

    def binary(self, json: str) -> bytes:
        ...

    def rootName(self) -> str:
        ...

    def text(self, binary: bytes) -> str:
        ...

class Table:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __init__(self, columns: collections.abc.Sequence[Column]=[]) -> None:
        ...

    def __len__(self) -> int:
        ...

    @typing.overload
    def add(self, column: Column) -> None:
        ...

    @typing.overload
    def add(self, name: str, values: collections.abc.Iterable[_t.CellInput], type: ColumnType | None=None) -> None:
        ...

    def cell(self, name: str, row: typing.SupportsInt) -> _t.CellValue:
        ...

    def column(self, name: str) -> _sigil.data.Column | None:
        ...

    def columns(self) -> list[Column]:
        ...

    def copy(self) -> Table:
        ...

    def derive(self, name: str, value: collections.abc.Callable[[int], _t.CellInput], type: ColumnType | None=None) -> None:
        ...

    def empty(self) -> bool:
        ...

    def filter(self, predicate: collections.abc.Callable[[int], bool]) -> Table:
        ...

    def group(self, names: str) -> list[Group]:
        ...

    def has(self, name: str) -> bool:
        ...

    def remove(self, name: str) -> bool:
        ...

    def row(self, row: typing.SupportsInt) -> dict[str, _t.CellValue]:
        ...

    def select(self, names: collections.abc.Sequence[str]) -> Table:
        ...

    def size(self) -> int:
        ...

    def sort(self, name: str, order: Order=...) -> Table:
        ...

    def take(self, rows: collections.abc.Sequence[typing.SupportsInt]) -> Table:
        ...

class Transform:
    """
    Members:

      Linear

      Log

      Pow

      Sqrt

      Symlog

      Time

      Quantize

      Threshold

      Ordinal

      Band

      Point
    """
    Band: typing.ClassVar[Transform]
    Linear: typing.ClassVar[Transform]
    Log: typing.ClassVar[Transform]
    Ordinal: typing.ClassVar[Transform]
    Point: typing.ClassVar[Transform]
    Pow: typing.ClassVar[Transform]
    Quantize: typing.ClassVar[Transform]
    Sqrt: typing.ClassVar[Transform]
    Symlog: typing.ClassVar[Transform]
    Threshold: typing.ClassVar[Transform]
    Time: typing.ClassVar[Transform]
    __members__: typing.ClassVar[dict[str, Transform]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

def decodeArtNet(packet: bytes) -> _sigil.data.Json | None:
    ...

def decodeCsv(text: str, options: CsvOptions=..., name: str='') -> _sigil.data.Table | None:
    ...

def decodeInstant(text: str) -> _sigil.data.Instant | None:
    ...

def decodeJson(text: str) -> _sigil.data.Json | None:
    ...

def decodeMidi(message: bytes) -> _sigil.data.Json | None:
    ...

def decodeOsc(packet: bytes) -> _sigil.data.Json | None:
    ...

def encodeArtNet(message: _t.JsonInput) -> bytes:
    ...

def encodeJson(value: _t.JsonInput) -> str:
    ...

def encodeMidi(message: _t.JsonInput) -> bytes:
    ...

@typing.overload
def encodeOsc(message: _t.JsonInput) -> bytes:
    ...

@typing.overload
def encodeOsc(address: str, arguments: _t.JsonInput) -> bytes:
    ...

def engineOf(uri: os.PathLike[str] | os.PathLike[bytes] | str | bytes) -> _sigil.data.Engine | None:
    ...

def registerDecoders(hub: _sigil.io.Hub) -> None:
    ...

def tableFromJson(value: _t.JsonInput) -> Table | None:
    ...
maxOscPacketBytes: int = 65507
