# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
__all__: list[str] = ['BlendMode', 'Color', 'FilterMode', 'Image', 'Matrix', 'MipmapMode', 'Paint', 'PaintStyle', 'Path', 'PathBuilder', 'PathDirection', 'PathFillType', 'PathOp', 'Picture', 'Point', 'Rect', 'RuntimeEffect', 'SamplingOptions', 'Size', 'StrokeCap', 'StrokeJoin', 'TileMode', 'Typeface', 'VertexMode', 'Vertices', 'pathOp']

class BlendMode:
    """
    Members:

      Clear

      Src

      Dst

      SrcOver

      DstOver

      SrcIn

      DstIn

      SrcOut

      DstOut

      SrcATop

      DstATop

      Xor

      Plus

      Modulate

      Screen

      Overlay

      Darken

      Lighten

      ColorDodge

      ColorBurn

      HardLight

      SoftLight

      Difference

      Exclusion

      Multiply

      Hue

      Saturation

      Color

      Luminosity
    """
    Clear: typing.ClassVar[BlendMode]
    Color: typing.ClassVar[BlendMode]
    ColorBurn: typing.ClassVar[BlendMode]
    ColorDodge: typing.ClassVar[BlendMode]
    Darken: typing.ClassVar[BlendMode]
    Difference: typing.ClassVar[BlendMode]
    Dst: typing.ClassVar[BlendMode]
    DstATop: typing.ClassVar[BlendMode]
    DstIn: typing.ClassVar[BlendMode]
    DstOut: typing.ClassVar[BlendMode]
    DstOver: typing.ClassVar[BlendMode]
    Exclusion: typing.ClassVar[BlendMode]
    HardLight: typing.ClassVar[BlendMode]
    Hue: typing.ClassVar[BlendMode]
    Lighten: typing.ClassVar[BlendMode]
    Luminosity: typing.ClassVar[BlendMode]
    Modulate: typing.ClassVar[BlendMode]
    Multiply: typing.ClassVar[BlendMode]
    Overlay: typing.ClassVar[BlendMode]
    Plus: typing.ClassVar[BlendMode]
    Saturation: typing.ClassVar[BlendMode]
    Screen: typing.ClassVar[BlendMode]
    SoftLight: typing.ClassVar[BlendMode]
    Src: typing.ClassVar[BlendMode]
    SrcATop: typing.ClassVar[BlendMode]
    SrcIn: typing.ClassVar[BlendMode]
    SrcOut: typing.ClassVar[BlendMode]
    SrcOver: typing.ClassVar[BlendMode]
    Xor: typing.ClassVar[BlendMode]
    __members__: typing.ClassVar[dict[str, BlendMode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Color:

    @typing.overload
    def __init__(self, r: typing.SupportsFloat, g: typing.SupportsFloat, b: typing.SupportsFloat, a: typing.SupportsFloat=1) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: _t.ColorLike) -> None:
        ...

    @property
    def a(self) -> float:
        ...

    @a.setter
    def a(self, arg0: typing.SupportsFloat) -> None:
        ...

    @property
    def b(self) -> float:
        ...

    @b.setter
    def b(self, arg0: typing.SupportsFloat) -> None:
        ...

    @property
    def g(self) -> float:
        ...

    @g.setter
    def g(self, arg0: typing.SupportsFloat) -> None:
        ...

    @property
    def r(self) -> float:
        ...

    @r.setter
    def r(self, arg0: typing.SupportsFloat) -> None:
        ...

class FilterMode:
    """
    Members:

      Nearest

      Linear
    """
    Linear: typing.ClassVar[FilterMode]
    Nearest: typing.ClassVar[FilterMode]
    __members__: typing.ClassVar[dict[str, FilterMode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Image:

    def height(self) -> int:
        ...

    def rgba(self) -> bytes:
        ...

    def width(self) -> int:
        ...

class Matrix:

    @staticmethod
    def RotateDeg(arg0: typing.SupportsFloat) -> Matrix:
        ...

    @staticmethod
    def Scale(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Matrix:
        ...

    @staticmethod
    def Translate(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Matrix:
        ...

    def __init__(self) -> None:
        ...

    def postRotate(self, arg0: typing.SupportsFloat) -> Matrix:
        ...

    def postScale(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Matrix:
        ...

    def postTranslate(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Matrix:
        ...

class MipmapMode:
    """
    Members:

      None_

      Nearest

      Linear
    """
    Linear: typing.ClassVar[MipmapMode]
    Nearest: typing.ClassVar[MipmapMode]
    None_: typing.ClassVar[MipmapMode]
    __members__: typing.ClassVar[dict[str, MipmapMode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Paint:

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: Paint) -> None:
        ...

    def setAlphaf(self, arg0: typing.SupportsFloat) -> None:
        ...

    def setAntiAlias(self, arg0: bool) -> None:
        ...

    def setBlendMode(self, arg0: BlendMode) -> None:
        ...

    def setColor(self, arg0: _t.ColorLike) -> None:
        ...

    def setStrokeCap(self, arg0: StrokeCap) -> None:
        ...

    def setStrokeJoin(self, arg0: StrokeJoin) -> None:
        ...

    def setStrokeWidth(self, arg0: typing.SupportsFloat) -> None:
        ...

    def setStyle(self, arg0: PaintStyle) -> None:
        ...

class PaintStyle:
    """
    Members:

      Fill

      Stroke

      StrokeAndFill
    """
    Fill: typing.ClassVar[PaintStyle]
    Stroke: typing.ClassVar[PaintStyle]
    StrokeAndFill: typing.ClassVar[PaintStyle]
    __members__: typing.ClassVar[dict[str, PaintStyle]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Path:

    @staticmethod
    def Circle(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> Path:
        ...

    @staticmethod
    def Oval(arg0: _t.RectLike) -> Path:
        ...

    @staticmethod
    def Rect(arg0: _t.RectLike) -> Path:
        ...

    def __init__(self) -> None:
        ...

    def contains(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> bool:
        ...

    def getBounds(self) -> _sigil.skia.Rect:
        ...

    def isEmpty(self) -> bool:
        ...

    def offset(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Path:
        ...

    def transform(self, arg0: Matrix) -> Path:
        ...

class PathBuilder:

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: Path) -> None:
        ...

    def addArc(self, arg0: _t.RectLike, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> PathBuilder:
        ...

    def addCircle(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> PathBuilder:
        ...

    def addOval(self, arg0: _t.RectLike) -> PathBuilder:
        ...

    def addPath(self, arg0: Path) -> PathBuilder:
        ...

    def addPolygon(self, points: collections.abc.Sequence[Point], close: bool=True) -> PathBuilder:
        ...

    def addRect(self, rect: _t.RectLike, direction: PathDirection=...) -> PathBuilder:
        ...

    def close(self) -> PathBuilder:
        ...

    def conicTo(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> PathBuilder:
        ...

    def cubicTo(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat) -> PathBuilder:
        ...

    def detach(self) -> Path:
        ...

    @typing.overload
    def lineTo(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> PathBuilder:
        ...

    @typing.overload
    def lineTo(self, arg0: Point) -> PathBuilder:
        ...

    @typing.overload
    def moveTo(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> PathBuilder:
        ...

    @typing.overload
    def moveTo(self, arg0: Point) -> PathBuilder:
        ...

    def offset(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> PathBuilder:
        ...

    def quadTo(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> PathBuilder:
        ...

    def reset(self) -> PathBuilder:
        ...

    def setFillType(self, arg0: PathFillType) -> PathBuilder:
        ...

    def setIsVolatile(self, arg0: bool) -> PathBuilder:
        ...

    def snapshot(self) -> Path:
        ...

    def transform(self, arg0: Matrix) -> PathBuilder:
        ...

class PathDirection:
    """
    Members:

      CW

      CCW
    """
    CCW: typing.ClassVar[PathDirection]
    CW: typing.ClassVar[PathDirection]
    __members__: typing.ClassVar[dict[str, PathDirection]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class PathFillType:
    """
    Members:

      Winding

      EvenOdd

      InverseWinding

      InverseEvenOdd
    """
    EvenOdd: typing.ClassVar[PathFillType]
    InverseEvenOdd: typing.ClassVar[PathFillType]
    InverseWinding: typing.ClassVar[PathFillType]
    Winding: typing.ClassVar[PathFillType]
    __members__: typing.ClassVar[dict[str, PathFillType]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class PathOp:
    """
    Members:

      Difference

      Intersect

      Union

      Xor

      ReverseDifference
    """
    Difference: typing.ClassVar[PathOp]
    Intersect: typing.ClassVar[PathOp]
    ReverseDifference: typing.ClassVar[PathOp]
    Union: typing.ClassVar[PathOp]
    Xor: typing.ClassVar[PathOp]
    __members__: typing.ClassVar[dict[str, PathOp]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Picture:

    def cullRect(self) -> _sigil.skia.Rect:
        ...

    def uniqueID(self) -> int:
        ...

class Point:

    def __add__(self, arg0: Point) -> Point:
        ...

    @typing.overload
    def __init__(self, x: typing.SupportsFloat=0, y: typing.SupportsFloat=0) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[_t.FloatLike]) -> None:
        ...

    def __mul__(self, arg0: typing.SupportsFloat) -> Point:
        ...

    def __sub__(self, arg0: Point) -> Point:
        ...

    def __truediv__(self, arg0: typing.SupportsFloat) -> Point:
        ...

    def length(self) -> float:
        ...

    @property
    def x(self) -> float:
        ...

    @x.setter
    def x(self, arg0: typing.SupportsFloat) -> None:
        ...

    @property
    def y(self) -> float:
        ...

    @y.setter
    def y(self, arg0: typing.SupportsFloat) -> None:
        ...

class Rect:

    @staticmethod
    def MakeEmpty() -> Rect:
        ...

    @staticmethod
    def MakeLTRB(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> Rect:
        ...

    @staticmethod
    def MakeWH(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Rect:
        ...

    @staticmethod
    def MakeXYWH(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> Rect:
        ...

    @typing.overload
    def __init__(self, x: typing.SupportsFloat, y: typing.SupportsFloat, width: typing.SupportsFloat, height: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[_t.FloatLike]) -> None:
        ...

    def bottom(self) -> float:
        ...

    def centerX(self) -> float:
        ...

    def centerY(self) -> float:
        ...

    def contains(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> bool:
        ...

    def height(self) -> float:
        ...

    def join(self, arg0: Rect) -> None:
        ...

    def left(self) -> float:
        ...

    def right(self) -> float:
        ...

    def top(self) -> float:
        ...

    def width(self) -> float:
        ...

class RuntimeEffect:

    @staticmethod
    def MakeForShader(arg0: str) -> RuntimeEffect:
        ...

class SamplingOptions:

    @typing.overload
    def __init__(self) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: FilterMode) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: FilterMode, arg1: MipmapMode) -> None:
        ...

class Size:

    @typing.overload
    def __init__(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def __init__(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsFloat], 'FixedSize(2)']) -> None:
        ...

    def height(self) -> float:
        ...

    def width(self) -> float:
        ...

class StrokeCap:
    """
    Members:

      Butt

      Round

      Square
    """
    Butt: typing.ClassVar[StrokeCap]
    Round: typing.ClassVar[StrokeCap]
    Square: typing.ClassVar[StrokeCap]
    __members__: typing.ClassVar[dict[str, StrokeCap]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class StrokeJoin:
    """
    Members:

      Miter

      Round

      Bevel
    """
    Bevel: typing.ClassVar[StrokeJoin]
    Miter: typing.ClassVar[StrokeJoin]
    Round: typing.ClassVar[StrokeJoin]
    __members__: typing.ClassVar[dict[str, StrokeJoin]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class TileMode:
    """
    Members:

      Clamp

      Repeat

      Mirror

      Decal
    """
    Clamp: typing.ClassVar[TileMode]
    Decal: typing.ClassVar[TileMode]
    Mirror: typing.ClassVar[TileMode]
    Repeat: typing.ClassVar[TileMode]
    __members__: typing.ClassVar[dict[str, TileMode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Typeface:

    def familyName(self) -> str:
        ...

class VertexMode:
    """
    Members:

      Triangles

      TriangleStrip

      TriangleFan
    """
    TriangleFan: typing.ClassVar[VertexMode]
    TriangleStrip: typing.ClassVar[VertexMode]
    Triangles: typing.ClassVar[VertexMode]
    __members__: typing.ClassVar[dict[str, VertexMode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Vertices:

    @staticmethod
    def MakeCopy(mode: VertexMode, positions: collections.abc.Sequence[Point], texCoords: collections.abc.Sequence[Point]=[], colors: collections.abc.Sequence[Color]=[], indices: collections.abc.Sequence[typing.SupportsInt]=[]) -> Vertices:
        ...

def pathOp(arg0: Path, arg1: Path, arg2: PathOp) -> Path:
    ...
