# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import _sigil.compose
import _sigil.skia
import _sigil.weave
from . import brush
__all__: list[str] = ['ADD', 'BASELINE', 'BEVEL', 'BLEND', 'BOLD', 'BOLDITALIC', 'BOTTOM', 'BURN', 'CANVAS', 'CENTER', 'CHORD', 'CLOSE', 'CORNER', 'CORNERS', 'Canvas', 'Constant', 'DARKEST', 'DEGREES', 'DIFFERENCE', 'DODGE', 'EXCLUSION', 'Graphics', 'HALF_PI', 'HARD_LIGHT', 'HSB', 'HSL', 'ITALIC', 'LEFT', 'LIGHTEST', 'LINES', 'MITER', 'MULTIPLY', 'NORMAL', 'NoiseField', 'OPEN', 'OVERLAY', 'PI', 'PIE', 'POINTS', 'POLYGON', 'PROJECT', 'Pen', 'PointMode', 'QUADS', 'QUAD_STRIP', 'QUARTER_PI', 'RADIANS', 'RADIUS', 'REMOVE', 'REPLACE', 'RGB', 'RIGHT', 'ROUND', 'SCREEN', 'SHAPE', 'SOFT_LIGHT', 'SQUARE', 'SUBTRACT', 'TAU', 'TOP', 'TRIANGLES', 'TRIANGLE_FAN', 'TRIANGLE_STRIP', 'TWO_PI', 'brush', 'constrain', 'degrees', 'dist', 'lerp', 'lerpColor', 'mag', 'map', 'norm', 'on', 'radians', 'sq']

class Canvas:

    def clear(self, arg0: _t.ColorLike) -> None:
        ...

    def clipPath(self, path: _sigil.skia.Path, invert: bool=False) -> None:
        ...

    def clipRect(self, rect: _t.RectLike, invert: bool=False) -> None:
        ...

    def drawCircle(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: _sigil.skia.Paint) -> None:
        ...

    def drawPath(self, arg0: _sigil.skia.Path, arg1: _sigil.skia.Paint) -> None:
        ...

    def drawPoints(self, arg0: PointMode, arg1: _t.PointBatch, arg2: _sigil.skia.Paint) -> None:
        ...

    def drawRect(self, arg0: _t.RectLike, arg1: _sigil.skia.Paint) -> None:
        ...

    def drawVertices(self, arg0: _sigil.skia.Vertices, arg1: _sigil.skia.BlendMode, arg2: _sigil.skia.Paint) -> None:
        ...

    def getSaveCount(self) -> int:
        ...

    def resetMatrix(self) -> None:
        ...

    def restore(self) -> None:
        ...

    def restoreToCount(self, arg0: typing.SupportsInt) -> None:
        ...

    def rotate(self, arg0: typing.SupportsFloat) -> None:
        ...

    def save(self) -> int:
        ...

    def scale(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    def translate(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

class Constant:
    """
    Members:

      CORNER

      CORNERS

      CENTER

      RADIUS

      RADIANS

      DEGREES

      RGB

      HSB

      HSL

      OPEN

      CHORD

      PIE

      CLOSE

      ROUND

      SQUARE

      PROJECT

      MITER

      BEVEL

      LEFT

      RIGHT

      TOP

      BOTTOM

      BASELINE

      NORMAL

      ITALIC

      BOLD

      BOLDITALIC

      POLYGON

      POINTS

      LINES

      TRIANGLES

      TRIANGLE_FAN

      TRIANGLE_STRIP

      QUADS

      QUAD_STRIP

      BLEND

      ADD

      MULTIPLY

      SCREEN

      REPLACE

      REMOVE

      DARKEST

      LIGHTEST

      DIFFERENCE

      EXCLUSION

      OVERLAY

      HARD_LIGHT

      SOFT_LIGHT

      DODGE

      BURN

      SUBTRACT

      CANVAS

      SHAPE
    """
    ADD: typing.ClassVar[Constant]
    BASELINE: typing.ClassVar[Constant]
    BEVEL: typing.ClassVar[Constant]
    BLEND: typing.ClassVar[Constant]
    BOLD: typing.ClassVar[Constant]
    BOLDITALIC: typing.ClassVar[Constant]
    BOTTOM: typing.ClassVar[Constant]
    BURN: typing.ClassVar[Constant]
    CANVAS: typing.ClassVar[Constant]
    CENTER: typing.ClassVar[Constant]
    CHORD: typing.ClassVar[Constant]
    CLOSE: typing.ClassVar[Constant]
    CORNER: typing.ClassVar[Constant]
    CORNERS: typing.ClassVar[Constant]
    DARKEST: typing.ClassVar[Constant]
    DEGREES: typing.ClassVar[Constant]
    DIFFERENCE: typing.ClassVar[Constant]
    DODGE: typing.ClassVar[Constant]
    EXCLUSION: typing.ClassVar[Constant]
    HARD_LIGHT: typing.ClassVar[Constant]
    HSB: typing.ClassVar[Constant]
    HSL: typing.ClassVar[Constant]
    ITALIC: typing.ClassVar[Constant]
    LEFT: typing.ClassVar[Constant]
    LIGHTEST: typing.ClassVar[Constant]
    LINES: typing.ClassVar[Constant]
    MITER: typing.ClassVar[Constant]
    MULTIPLY: typing.ClassVar[Constant]
    NORMAL: typing.ClassVar[Constant]
    OPEN: typing.ClassVar[Constant]
    OVERLAY: typing.ClassVar[Constant]
    PIE: typing.ClassVar[Constant]
    POINTS: typing.ClassVar[Constant]
    POLYGON: typing.ClassVar[Constant]
    PROJECT: typing.ClassVar[Constant]
    QUADS: typing.ClassVar[Constant]
    QUAD_STRIP: typing.ClassVar[Constant]
    RADIANS: typing.ClassVar[Constant]
    RADIUS: typing.ClassVar[Constant]
    REMOVE: typing.ClassVar[Constant]
    REPLACE: typing.ClassVar[Constant]
    RGB: typing.ClassVar[Constant]
    RIGHT: typing.ClassVar[Constant]
    ROUND: typing.ClassVar[Constant]
    SCREEN: typing.ClassVar[Constant]
    SHAPE: typing.ClassVar[Constant]
    SOFT_LIGHT: typing.ClassVar[Constant]
    SQUARE: typing.ClassVar[Constant]
    SUBTRACT: typing.ClassVar[Constant]
    TOP: typing.ClassVar[Constant]
    TRIANGLES: typing.ClassVar[Constant]
    TRIANGLE_FAN: typing.ClassVar[Constant]
    TRIANGLE_STRIP: typing.ClassVar[Constant]
    __members__: typing.ClassVar[dict[str, Constant]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

class Graphics:

    def __init__(self, width: typing.SupportsFloat, height: typing.SupportsFloat) -> None:
        ...

    def begin(self, arg0: Pen) -> Pen:
        ...

    def draw(self, host: Pen, program: _t.DrawCallback) -> None:
        ...

    def end(self) -> None:
        ...

    def extent(self) -> tuple[float, float]:
        ...

    def height(self) -> float:
        ...

    def image(self) -> _sigil.skia.Image:
        ...

    def resize(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    def setDensityFloor(self, arg0: typing.SupportsFloat) -> None:
        ...

    def width(self) -> float:
        ...

class NoiseField:

    @staticmethod
    def corner(arg0: typing.SupportsInt, arg1: typing.SupportsInt, arg2: typing.SupportsInt, arg3: typing.SupportsInt) -> float:
        ...

    def __init__(self, seed: typing.SupportsInt=0) -> None:
        ...

    def at(self, x: typing.SupportsFloat, y: typing.SupportsFloat=0.0, z: typing.SupportsFloat=0.0) -> float:
        ...

    def detail(self, arg0: typing.SupportsInt, arg1: typing.SupportsFloat) -> None:
        ...

    def falloff(self) -> float:
        ...

    def octaves(self) -> int:
        ...

    @typing.overload
    def seed(self, arg0: typing.SupportsInt) -> None:
        ...

    @typing.overload
    def seed(self) -> int:
        ...

class Pen:

    @staticmethod
    def lerpColor(arg0: _t.ColorLike, arg1: _t.ColorLike, arg2: typing.SupportsFloat) -> _sigil.skia.Color:
        ...

    @typing.overload
    def angleMode(self, arg0: Constant) -> None:
        ...

    @typing.overload
    def angleMode(self) -> Constant:
        ...

    def applyMatrix(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat) -> None:
        ...

    def arc(self, x: typing.SupportsFloat, y: typing.SupportsFloat, width: typing.SupportsFloat, height: typing.SupportsFloat, start: typing.SupportsFloat, stop: typing.SupportsFloat, mode: Constant=...) -> None:
        ...

    @typing.overload
    def background(self, value: _t.ColorLike, /) -> None:
        ...

    @typing.overload
    def background(self, gray: _t.FloatLike, alpha: _t.FloatLike=..., /) -> None:
        ...

    @typing.overload
    def background(self, red: _t.FloatLike, green: _t.FloatLike, blue: _t.FloatLike, alpha: _t.FloatLike=..., /) -> None:
        ...

    def beginContour(self) -> None:
        ...

    def beginShape(self, kind: Constant=...) -> None:
        ...

    def bezier(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: typing.SupportsFloat, arg7: typing.SupportsFloat) -> None:
        ...

    def bezierVertex(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat) -> None:
        ...

    def blendMode(self, arg0: Constant) -> None:
        ...

    def canvas(self) -> Canvas:
        ...

    @typing.overload
    def circle(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def circle(self, arg0: _t.PointLike, arg1: typing.SupportsFloat) -> None:
        ...

    def clear(self) -> None:
        ...

    def clip(self, shape: _t.DrawCallback, invert: bool=False) -> None:
        ...

    @typing.overload
    def color(self, value: _t.ColorLike, /) -> _sigil.skia.Color:
        ...

    @typing.overload
    def color(self, gray: _t.FloatLike, alpha: _t.FloatLike=..., /) -> _sigil.skia.Color:
        ...

    @typing.overload
    def color(self, red: _t.FloatLike, green: _t.FloatLike, blue: _t.FloatLike, alpha: _t.FloatLike=..., /) -> _sigil.skia.Color:
        ...

    @typing.overload
    def colorMode(self, arg0: Constant) -> None:
        ...

    @typing.overload
    def colorMode(self, arg0: Constant, arg1: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def colorMode(self, arg0: Constant, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def colorMode(self, arg0: Constant, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> None:
        ...

    def contentScale(self) -> float:
        ...

    def curve(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: typing.SupportsFloat, arg7: typing.SupportsFloat) -> None:
        ...

    def curveTightness(self, arg0: typing.SupportsFloat) -> None:
        ...

    def curveVertex(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    def element(self, element: _sigil.compose.Element, box: _t.RectLike, index: typing.SupportsInt=0) -> None:
        ...

    @typing.overload
    def ellipse(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def ellipse(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    def ellipseMode(self, arg0: Constant) -> None:
        ...

    def endContour(self) -> None:
        ...

    def endShape(self, mode: Constant=...) -> None:
        ...

    @typing.overload
    def fill(self, value: _t.ColorLike | _sigil.material.skia.Paint, /) -> None:
        ...

    @typing.overload
    def fill(self, gray: _t.FloatLike, alpha: _t.FloatLike=..., /) -> None:
        ...

    @typing.overload
    def fill(self, red: _t.FloatLike, green: _t.FloatLike, blue: _t.FloatLike, alpha: _t.FloatLike=..., /) -> None:
        ...

    def fillPaint(self) -> _sigil.skia.Paint | None:
        ...

    @typing.overload
    def frameRate(self) -> float:
        ...

    @typing.overload
    def frameRate(self, arg0: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def image(self, arg0: _sigil.skia.Image, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def image(self, arg0: _sigil.skia.Image, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def image(self, arg0: _sigil.skia.Image, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: typing.SupportsFloat, arg7: typing.SupportsFloat, arg8: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def image(self, arg0: Graphics, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def image(self, arg0: Graphics, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> None:
        ...

    def imageMode(self, arg0: Constant) -> None:
        ...

    def inherit(self, arg0: _t.ColorLike, arg1: _sigil.weave.Type) -> None:
        ...

    def inheritedFont(self) -> _sigil.weave.Type:
        ...

    def inheritedInk(self) -> _sigil.skia.Color:
        ...

    def isLooping(self) -> bool:
        ...

    def keyIsDown(self, arg0: typing.SupportsInt) -> bool:
        ...

    def keysDown(self) -> list[int]:
        ...

    @typing.overload
    def line(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def line(self, arg0: _t.PointLike, arg1: _t.PointLike) -> None:
        ...

    def loop(self) -> None:
        ...

    def millis(self) -> float:
        ...

    def noDash(self) -> None:
        ...

    def noFill(self) -> None:
        ...

    def noLoop(self) -> None:
        ...

    def noSmooth(self) -> None:
        ...

    def noStroke(self) -> None:
        ...

    def noise(self, x: typing.SupportsFloat, y: typing.SupportsFloat=0.0, z: typing.SupportsFloat=0.0) -> float:
        ...

    def noiseDetail(self, arg0: typing.SupportsInt, arg1: typing.SupportsFloat) -> None:
        ...

    def noiseSeed(self, arg0: typing.SupportsInt) -> None:
        ...

    @typing.overload
    def point(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def point(self, arg0: _t.PointLike) -> None:
        ...

    def pop(self) -> None:
        ...

    def push(self) -> None:
        ...

    def quad(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: typing.SupportsFloat, arg7: typing.SupportsFloat) -> None:
        ...

    def quadraticVertex(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def random(self) -> float:
        ...

    @typing.overload
    def random(self, arg0: typing.SupportsFloat) -> float:
        ...

    @typing.overload
    def random(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> float:
        ...

    def randomGaussian(self, mean: typing.SupportsFloat=0.0, sd: typing.SupportsFloat=1.0) -> float:
        ...

    def randomSeed(self, arg0: typing.SupportsInt) -> None:
        ...

    @typing.overload
    def rect(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def rect(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def rect(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: typing.SupportsFloat, arg7: typing.SupportsFloat) -> None:
        ...

    def rectMode(self, arg0: Constant) -> None:
        ...

    def redraw(self) -> None:
        ...

    def resetMatrix(self) -> None:
        ...

    def rotate(self, arg0: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def scale(self, arg0: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def scale(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def shape(self, arg0: _sigil.skia.Path) -> None:
        ...

    @typing.overload
    def shape(self, arg0: _sigil.skia.Path, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> None:
        ...

    def shearX(self, arg0: typing.SupportsFloat) -> None:
        ...

    def shearY(self, arg0: typing.SupportsFloat) -> None:
        ...

    def smooth(self) -> None:
        ...

    @typing.overload
    def square(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def square(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def square(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat, arg6: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def stroke(self, value: _t.ColorLike | _sigil.material.skia.Paint, /) -> None:
        ...

    @typing.overload
    def stroke(self, gray: _t.FloatLike, alpha: _t.FloatLike=..., /) -> None:
        ...

    @typing.overload
    def stroke(self, red: _t.FloatLike, green: _t.FloatLike, blue: _t.FloatLike, alpha: _t.FloatLike=..., /) -> None:
        ...

    def strokeCap(self, arg0: Constant) -> None:
        ...

    def strokeDash(self, intervals: collections.abc.Sequence[typing.SupportsFloat], phase: typing.SupportsFloat=0.0) -> None:
        ...

    def strokeJoin(self, arg0: Constant) -> None:
        ...

    def strokePaint(self) -> _sigil.skia.Paint | None:
        ...

    def strokeWeight(self, arg0: typing.SupportsFloat) -> None:
        ...

    def targetFrameRate(self) -> float:
        ...

    @typing.overload
    def text(self, arg0: str, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def text(self, arg0: str, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def text(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def textAlign(self, arg0: Constant) -> None:
        ...

    @typing.overload
    def textAlign(self, arg0: Constant, arg1: Constant) -> None:
        ...

    def textAscent(self) -> float:
        ...

    def textDescent(self) -> float:
        ...

    @typing.overload
    def textFont(self, arg0: str) -> None:
        ...

    @typing.overload
    def textFont(self, arg0: str, arg1: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def textFont(self, arg0: _sigil.weave.Type) -> None:
        ...

    @typing.overload
    def textFont(self, arg0: _sigil.skia.Typeface) -> None:
        ...

    @typing.overload
    def textLeading(self, arg0: typing.SupportsFloat) -> None:
        ...

    @typing.overload
    def textLeading(self) -> float:
        ...

    def textSize(self, arg0: typing.SupportsFloat) -> None:
        ...

    def textStyle(self, arg0: Constant) -> None:
        ...

    def textWidth(self, arg0: str) -> float:
        ...

    def translate(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    def triangle(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat, arg4: typing.SupportsFloat, arg5: typing.SupportsFloat) -> None:
        ...

    def vertex(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> None:
        ...

    def vertices(self, arg0: _sigil.skia.Vertices) -> None:
        ...

    @property
    def deltaTime(self) -> float:
        ...

    @property
    def frameCount(self) -> int:
        ...

    @property
    def height(self) -> float:
        ...

    @property
    def key(self) -> str:
        ...

    @property
    def keyCode(self) -> int:
        ...

    @property
    def keyIsPressed(self) -> bool:
        ...

    @property
    def mouseIsPressed(self) -> bool:
        ...

    @property
    def mouseX(self) -> float:
        ...

    @property
    def mouseY(self) -> float:
        ...

    @property
    def pmouseX(self) -> float:
        ...

    @property
    def pmouseY(self) -> float:
        ...

    @property
    def width(self) -> float:
        ...

class PointMode:
    """
    Members:

      Points

      Lines

      Polygon
    """
    Lines: typing.ClassVar[PointMode]
    Points: typing.ClassVar[PointMode]
    Polygon: typing.ClassVar[PointMode]
    __members__: typing.ClassVar[dict[str, PointMode]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

def constrain(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> float:
    ...

def degrees(arg0: typing.SupportsFloat) -> float:
    ...

def dist(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat, arg3: typing.SupportsFloat) -> float:
    ...

def lerp(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> float:
    ...

def lerpColor(arg0: _t.ColorLike, arg1: _t.ColorLike, arg2: typing.SupportsFloat) -> _sigil.skia.Color:
    ...

def mag(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> float:
    ...

def map(value: typing.SupportsFloat, start1: typing.SupportsFloat, stop1: typing.SupportsFloat, start2: typing.SupportsFloat, stop2: typing.SupportsFloat, withinBounds: bool=False) -> float:
    ...

def norm(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> float:
    ...

def on(canvas: Canvas, size: tuple[typing.SupportsFloat, typing.SupportsFloat], program: _t.DrawCallback) -> None:
    ...

def radians(arg0: typing.SupportsFloat) -> float:
    ...

def sq(arg0: typing.SupportsFloat) -> float:
    ...
ADD: Constant
BASELINE: Constant
BEVEL: Constant
BLEND: Constant
BOLD: Constant
BOLDITALIC: Constant
BOTTOM: Constant
BURN: Constant
CANVAS: Constant
CENTER: Constant
CHORD: Constant
CLOSE: Constant
CORNER: Constant
CORNERS: Constant
DARKEST: Constant
DEGREES: Constant
DIFFERENCE: Constant
DODGE: Constant
EXCLUSION: Constant
HALF_PI: float = 1.5707963705062866
HARD_LIGHT: Constant
HSB: Constant
HSL: Constant
ITALIC: Constant
LEFT: Constant
LIGHTEST: Constant
LINES: Constant
MITER: Constant
MULTIPLY: Constant
NORMAL: Constant
OPEN: Constant
OVERLAY: Constant
PI: float = 3.1415927410125732
PIE: Constant
POINTS: Constant
POLYGON: Constant
PROJECT: Constant
QUADS: Constant
QUAD_STRIP: Constant
QUARTER_PI: float = 0.7853981852531433
RADIANS: Constant
RADIUS: Constant
REMOVE: Constant
REPLACE: Constant
RGB: Constant
RIGHT: Constant
ROUND: Constant
SCREEN: Constant
SHAPE: Constant
SOFT_LIGHT: Constant
SQUARE: Constant
SUBTRACT: Constant
TAU: float = 6.2831854820251465
TOP: Constant
TRIANGLES: Constant
TRIANGLE_FAN: Constant
TRIANGLE_STRIP: Constant
TWO_PI: float = 6.2831854820251465
