# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil._types as _t
import builtins
import collections.abc
import typing
import _sigil.skia
from . import camera
from . import render
__all__: list[str] = ['BoxOptions', 'Mesh', 'Platonic', 'box', 'camera', 'cylinderPanel', 'extrude', 'grid', 'platonic', 'quad', 'render', 'revolve', 'superellipsoid', 'torus']

class BoxOptions:
    back: bool
    bottom: bool
    front: bool
    left: bool
    right: bool

    @property
    def tint(self) -> _t.Vec4:
        ...

    @tint.setter
    def tint(self, value: _t.Vec4Like) -> None:
        ...
    top: bool

    def __init__(self) -> None:
        ...

    @property
    def sideShade(self) -> float:
        ...

    @sideShade.setter
    def sideShade(self, arg0: typing.SupportsFloat) -> None:
        ...

class Mesh:

    def __init__(self) -> None:
        ...

    def append(self, arg0: Mesh) -> None:
        ...

    def bounds(self) -> tuple[_t.Vec3, _t.Vec3]:
        ...

    def computeNormals(self) -> None:
        ...

    def copy(self) -> Mesh:
        ...

    def transform(self, arg0: camera.Matrix) -> None:
        ...

    def triangleCount(self) -> int:
        ...

    def vertexCount(self) -> int:
        ...

    @property
    def colors(self) -> list[_t.Vec4]:
        ...

    @colors.setter
    def colors(self, arg0: collections.abc.Sequence[_t.Vec4Like]) -> None:
        ...

    @property
    def indices(self) -> list[int]:
        ...

    @indices.setter
    def indices(self, arg0: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...

    @property
    def normals(self) -> list[_t.Vec3]:
        ...

    @normals.setter
    def normals(self, arg0: collections.abc.Sequence[_t.Vec3Like]) -> None:
        ...

    @property
    def positions(self) -> list[_t.Vec3]:
        ...

    @positions.setter
    def positions(self, arg0: collections.abc.Sequence[_t.Vec3Like]) -> None:
        ...

    @property
    def uvs(self) -> list[_t.Vec2]:
        ...

    @uvs.setter
    def uvs(self, arg0: collections.abc.Sequence[_t.Vec2Like]) -> None:
        ...

class Platonic:
    """
    Members:
    
      Tetrahedron
    
      Cube
    
      Octahedron
    
      Dodecahedron
    
      Icosahedron
    """
    Cube: typing.ClassVar[Platonic]
    Dodecahedron: typing.ClassVar[Platonic]
    Icosahedron: typing.ClassVar[Platonic]
    Octahedron: typing.ClassVar[Platonic]
    Tetrahedron: typing.ClassVar[Platonic]
    __members__: typing.ClassVar[dict[str, Platonic]]

    def __eq__(self, other: builtins.object) -> bool:
        ...

    def __getstate__(self) -> int:
        ...

    def __hash__(self) -> int:
        ...

    def __index__(self) -> int:
        ...

    def __init__(self, value: typing.SupportsInt) -> None:
        ...

    def __int__(self) -> int:
        ...

    def __ne__(self, other: builtins.object) -> bool:
        ...

    def __repr__(self) -> str:
        ...

    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...

    def __str__(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def value(self) -> int:
        ...

def box(lo: _t.Vec3Like, hi: _t.Vec3Like, options: BoxOptions=...) -> Mesh:
    ...

def cylinderPanel(width: typing.SupportsFloat, height: typing.SupportsFloat, radius: typing.SupportsFloat, nu: typing.SupportsInt=32, nv: typing.SupportsInt=8) -> Mesh:
    ...

def extrude(path: _sigil.skia.Path, depth: typing.SupportsFloat=24, tolerance: typing.SupportsFloat=0.25) -> Mesh:
    ...

def grid(nu: typing.SupportsInt, nv: typing.SupportsInt, surface: collections.abc.Callable[[float, float], _t.Vec3Like]) -> Mesh:
    ...

def platonic(solid: Platonic, radius: typing.SupportsFloat=1, sharedVertices: bool=False) -> Mesh:
    ...

def quad(arg0: typing.SupportsFloat, arg1: typing.SupportsFloat) -> Mesh:
    ...

def revolve(profile: collections.abc.Sequence[_t.Vec2Like], segments: typing.SupportsInt=48, sweepDeg: typing.SupportsFloat=360, close: bool=True) -> Mesh:
    ...

def superellipsoid(radii: _t.Vec3Like, exponent: typing.SupportsFloat, nu: typing.SupportsInt=48, nv: typing.SupportsInt=32) -> Mesh:
    ...

def torus(radius: typing.SupportsFloat, tube: typing.SupportsFloat, nu: typing.SupportsInt=64, nv: typing.SupportsInt=32) -> Mesh:
    ...
