# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import builtins
import collections.abc
import typing
import _sigil.compose
import _sigil.weave
__all__: builtins.list[str] = ['article', 'caption', 'code', 'eyebrow', 'figure', 'footer', 'gap', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'heading', 'item', 'label', 'lead', 'list', 'listGap', 'measure', 'paragraph', 'quote', 'quoteInset', 'rule', 'section']

@typing.overload
def article(children: collections.abc.Iterable[_sigil.compose.Element], /) -> _sigil.compose.Element:
    ...

@typing.overload
def article(*children: _sigil.compose.Element) -> _sigil.compose.Element:
    ...

def caption(words: str) -> _sigil.compose.Element:
    ...

def code(words: str) -> _sigil.compose.Element:
    ...

def eyebrow(words: str) -> _sigil.compose.Element:
    ...

def figure(body: _sigil.compose.Element, note: str='') -> _sigil.compose.Element:
    ...

def footer(words: str) -> _sigil.compose.Element:
    ...

def h1(words: str) -> _sigil.compose.Element:
    ...

def h2(words: str) -> _sigil.compose.Element:
    ...

def h3(words: str) -> _sigil.compose.Element:
    ...

def h4(words: str) -> _sigil.compose.Element:
    ...

def h5(words: str) -> _sigil.compose.Element:
    ...

def h6(words: str) -> _sigil.compose.Element:
    ...

def heading(level: typing.SupportsInt, words: str) -> _sigil.compose.Element:
    ...

@typing.overload
def item(words: str, marker: str='•') -> _sigil.compose.Element:
    ...

@typing.overload
def item(body: _sigil.compose.Element, marker: str='•') -> _sigil.compose.Element:
    ...

def label(words: str) -> _sigil.compose.Element:
    ...

def lead(words: str) -> _sigil.compose.Element:
    ...

@typing.overload
def list(children: collections.abc.Iterable[_sigil.compose.Element], /) -> _sigil.compose.Element:
    ...

@typing.overload
def list(*children: _sigil.compose.Element) -> _sigil.compose.Element:
    ...

@typing.overload
def paragraph(words: str) -> _sigil.compose.Element:
    ...

@typing.overload
def paragraph(words: _sigil.weave.RichText) -> _sigil.compose.Element:
    ...

@typing.overload
def quote(children: collections.abc.Iterable[_sigil.compose.Element], /) -> _sigil.compose.Element:
    ...

@typing.overload
def quote(*children: _sigil.compose.Element) -> _sigil.compose.Element:
    ...

@typing.overload
def quote(words: str) -> _sigil.compose.Element:
    ...

def rule() -> _sigil.compose.Element:
    ...

@typing.overload
def section(children: collections.abc.Iterable[_sigil.compose.Element], /) -> _sigil.compose.Element:
    ...

@typing.overload
def section(*children: _sigil.compose.Element) -> _sigil.compose.Element:
    ...
gap: str = 'document.gap'
listGap: str = 'document.listGap'
measure: str = 'document.measure'
quoteInset: str = 'document.quoteInset'
