# Generated by typing/generate.py; edit its refinements, not this file.
from __future__ import annotations
import _sigil
import _sigil.weave
__all__: list[str] = ['inFrame', 'style']

def inFrame(key: str) -> _sigil.weave.Selector:
    ...

def style(name: str) -> _sigil.weave.Selector:
    ...
